// Indian Emerging / Uncapped Players (65 players)
export const part4a = [
// 1. Yash Dhull
{
  name: 'Yash Dhull',
  fullName: 'Yash Dhull',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 22,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 8,
  runs: 180,
  battingAverage: 22.5,
  strikeRate: 122.5,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 4,
  stumpings: 0,
  overallRating: 58,
  battingRating: 60,
  bowlingRating: 10,
  fieldingRating: 55,
  fitnessRating: 72,
  formRating: 58,
  marketDemand: 45,
  basePrice: 50,
  isMarquee: false,
  isCapped: false
},
// 2. Ravi Kumar
{
  name: 'Ravi Kumar',
  fullName: 'Ravi Kumar',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 24,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 5,
  runs: 3,
  battingAverage: 1.5,
  strikeRate: 35.0,
  hundreds: 0,
  fifties: 0,
  wickets: 4,
  bowlingAverage: 32.5,
  economy: 9.25,
  bowlingStrikeRate: 21.1,
  bestBowling: '2/22',
  catches: 1,
  stumpings: 0,
  overallRating: 50,
  battingRating: 5,
  bowlingRating: 52,
  fieldingRating: 42,
  fitnessRating: 68,
  formRating: 48,
  marketDemand: 32,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 3. Prabhsimran Singh
{
  name: 'Prabhsimran Singh',
  fullName: 'Prabhsimran Singh',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 23,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 15,
  runs: 280,
  battingAverage: 21.5,
  strikeRate: 145.8,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 8,
  stumpings: 4,
  overallRating: 55,
  battingRating: 58,
  bowlingRating: 5,
  fieldingRating: 60,
  fitnessRating: 72,
  formRating: 52,
  marketDemand: 40,
  basePrice: 40,
  isMarquee: false,
  isCapped: false
},
// 4. Ayush Badoni
{
  name: 'Ayush Badoni',
  fullName: 'Ayush Badoni',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 24,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 25,
  runs: 550,
  battingAverage: 23.8,
  strikeRate: 142.5,
  hundreds: 0,
  fifties: 3,
  wickets: 2,
  bowlingAverage: 48.0,
  economy: 9.5,
  bowlingStrikeRate: 30.3,
  bestBowling: '1/15',
  catches: 10,
  stumpings: 0,
  overallRating: 62,
  battingRating: 65,
  bowlingRating: 15,
  fieldingRating: 58,
  fitnessRating: 75,
  formRating: 65,
  marketDemand: 52,
  basePrice: 50,
  isMarquee: false,
  isCapped: false
},
// 5. Harpreet Brar
{
  name: 'Harpreet Brar',
  fullName: 'Harpreet Brar',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SPIN_ALL_ROUNDER',
  age: 28,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_ORTHODOX',
  matches: 30,
  runs: 180,
  battingAverage: 12.0,
  strikeRate: 118.5,
  hundreds: 0,
  fifties: 0,
  wickets: 25,
  bowlingAverage: 28.8,
  economy: 7.85,
  bowlingStrikeRate: 22.0,
  bestBowling: '3/19',
  catches: 8,
  stumpings: 0,
  overallRating: 62,
  battingRating: 35,
  bowlingRating: 65,
  fieldingRating: 55,
  fitnessRating: 72,
  formRating: 62,
  marketDemand: 48,
  basePrice: 50,
  isMarquee: false,
  isCapped: false
},
// 6. Mohit Sharma
{
  name: 'Mohit Sharma',
  fullName: 'Mohit Sharma',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 36,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 80,
  runs: 42,
  battingAverage: 4.2,
  strikeRate: 72.5,
  hundreds: 0,
  fifties: 0,
  wickets: 72,
  bowlingAverage: 27.5,
  economy: 8.35,
  bowlingStrikeRate: 19.8,
  bestBowling: '4/14',
  catches: 15,
  stumpings: 0,
  overallRating: 65,
  battingRating: 10,
  bowlingRating: 72,
  fieldingRating: 55,
  fitnessRating: 62,
  formRating: 58,
  marketDemand: 48,
  basePrice: 50,
  isMarquee: false,
  isCapped: true
},
// 7. Sandeep Sharma
{
  name: 'Sandeep Sharma',
  fullName: 'Sandeep Sharma',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 31,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 65,
  runs: 18,
  battingAverage: 3.0,
  strikeRate: 55.0,
  hundreds: 0,
  fifties: 0,
  wickets: 62,
  bowlingAverage: 26.8,
  economy: 7.92,
  bowlingStrikeRate: 20.3,
  bestBowling: '4/20',
  catches: 10,
  stumpings: 0,
  overallRating: 65,
  battingRating: 8,
  bowlingRating: 70,
  fieldingRating: 52,
  fitnessRating: 68,
  formRating: 58,
  marketDemand: 48,
  basePrice: 50,
  isMarquee: false,
  isCapped: true
},
// 8. Jaydev Unadkat
{
  name: 'Jaydev Unadkat',
  fullName: 'Jaydev Unadkat',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 32,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
  matches: 90,
  runs: 35,
  battingAverage: 3.5,
  strikeRate: 62.5,
  hundreds: 0,
  fifties: 0,
  wickets: 85,
  bowlingAverage: 28.5,
  economy: 8.75,
  bowlingStrikeRate: 19.5,
  bestBowling: '5/25',
  catches: 18,
  stumpings: 0,
  overallRating: 68,
  battingRating: 8,
  bowlingRating: 72,
  fieldingRating: 55,
  fitnessRating: 70,
  formRating: 62,
  marketDemand: 52,
  basePrice: 50,
  isMarquee: false,
  isCapped: true
},
// 9. Siddharth Kaul
{
  name: 'Siddharth Kaul',
  fullName: 'Siddharth Kaul',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 31,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 55,
  runs: 15,
  battingAverage: 3.0,
  strikeRate: 52.5,
  hundreds: 0,
  fifties: 0,
  wickets: 48,
  bowlingAverage: 29.5,
  economy: 8.85,
  bowlingStrikeRate: 20.0,
  bestBowling: '3/18',
  catches: 8,
  stumpings: 0,
  overallRating: 62,
  battingRating: 5,
  bowlingRating: 65,
  fieldingRating: 50,
  fitnessRating: 65,
  formRating: 55,
  marketDemand: 42,
  basePrice: 40,
  isMarquee: false,
  isCapped: true
},
// 10. Ankit Rajpoot
{
  name: 'Ankit Rajpoot',
  fullName: 'Ankit Rajpoot',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 30,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 25,
  runs: 5,
  battingAverage: 1.7,
  strikeRate: 42.0,
  hundreds: 0,
  fifties: 0,
  wickets: 18,
  bowlingAverage: 35.8,
  economy: 9.55,
  bowlingStrikeRate: 22.5,
  bestBowling: '2/18',
  catches: 4,
  stumpings: 0,
  overallRating: 52,
  battingRating: 5,
  bowlingRating: 55,
  fieldingRating: 42,
  fitnessRating: 62,
  formRating: 45,
  marketDemand: 30,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 11. Basil Thampi
{
  name: 'Basil Thampi',
  fullName: 'Basil Thampi',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 30,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 20,
  runs: 3,
  battingAverage: 1.5,
  strikeRate: 38.0,
  hundreds: 0,
  fifties: 0,
  wickets: 15,
  bowlingAverage: 35.2,
  economy: 9.85,
  bowlingStrikeRate: 21.4,
  bestBowling: '2/24',
  catches: 3,
  stumpings: 0,
  overallRating: 52,
  battingRating: 5,
  bowlingRating: 55,
  fieldingRating: 42,
  fitnessRating: 62,
  formRating: 45,
  marketDemand: 30,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 12. Kartik Tyagi
{
  name: 'Kartik Tyagi',
  fullName: 'Kartik Tyagi',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 24,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST',
  matches: 15,
  runs: 5,
  battingAverage: 2.5,
  strikeRate: 42.0,
  hundreds: 0,
  fifties: 0,
  wickets: 12,
  bowlingAverage: 32.5,
  economy: 9.15,
  bowlingStrikeRate: 21.3,
  bestBowling: '2/29',
  catches: 3,
  stumpings: 0,
  overallRating: 55,
  battingRating: 5,
  bowlingRating: 58,
  fieldingRating: 45,
  fitnessRating: 72,
  formRating: 55,
  marketDemand: 40,
  basePrice: 40,
  isMarquee: false,
  isCapped: false
},
// 13. Akash Deep
{
  name: 'Akash Deep',
  fullName: 'Akash Deep',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 27,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 12,
  runs: 5,
  battingAverage: 2.5,
  strikeRate: 38.5,
  hundreds: 0,
  fifties: 0,
  wickets: 10,
  bowlingAverage: 30.5,
  economy: 8.85,
  bowlingStrikeRate: 20.7,
  bestBowling: '3/20',
  catches: 2,
  stumpings: 0,
  overallRating: 56,
  battingRating: 5,
  bowlingRating: 58,
  fieldingRating: 45,
  fitnessRating: 72,
  formRating: 55,
  marketDemand: 42,
  basePrice: 40,
  isMarquee: false,
  isCapped: false
},
// 14. Yash Dayal
{
  name: 'Yash Dayal',
  fullName: 'Yash Dayal',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 26,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
  matches: 18,
  runs: 8,
  battingAverage: 2.7,
  strikeRate: 42.0,
  hundreds: 0,
  fifties: 0,
  wickets: 15,
  bowlingAverage: 29.8,
  economy: 8.65,
  bowlingStrikeRate: 20.7,
  bestBowling: '3/18',
  catches: 4,
  stumpings: 0,
  overallRating: 60,
  battingRating: 5,
  bowlingRating: 62,
  fieldingRating: 48,
  fitnessRating: 75,
  formRating: 62,
  marketDemand: 48,
  basePrice: 50,
  isMarquee: false,
  isCapped: false
},
// 15. Vijaykumar Vyshak
{
  name: 'Vijaykumar Vyshak',
  fullName: 'Vijaykumar Vyshak',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 27,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 10,
  runs: 2,
  battingAverage: 1.0,
  strikeRate: 28.5,
  hundreds: 0,
  fifties: 0,
  wickets: 8,
  bowlingAverage: 32.0,
  economy: 9.25,
  bowlingStrikeRate: 20.8,
  bestBowling: '2/25',
  catches: 2,
  stumpings: 0,
  overallRating: 52,
  battingRating: 5,
  bowlingRating: 55,
  fieldingRating: 42,
  fitnessRating: 68,
  formRating: 48,
  marketDemand: 32,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 16. Anuj Rawat
{
  name: 'Anuj Rawat',
  fullName: 'Anuj Rawat',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 24,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 15,
  runs: 200,
  battingAverage: 16.7,
  strikeRate: 125.0,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 8,
  stumpings: 3,
  overallRating: 52,
  battingRating: 52,
  bowlingRating: 5,
  fieldingRating: 58,
  fitnessRating: 70,
  formRating: 48,
  marketDemand: 35,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 17. KS Bharat
{
  name: 'KS Bharat',
  fullName: 'Kona Srikar Bharat',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 30,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 20,
  runs: 300,
  battingAverage: 18.8,
  strikeRate: 118.5,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 12,
  stumpings: 8,
  overallRating: 55,
  battingRating: 55,
  bowlingRating: 5,
  fieldingRating: 68,
  fitnessRating: 65,
  formRating: 50,
  marketDemand: 35,
  basePrice: 30,
  isMarquee: false,
  isCapped: true
},
// 18. N Jagadeesan
{
  name: 'N Jagadeesan',
  fullName: 'Narayan Jagadeesan',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'OPENER',
  age: 28,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 12,
  runs: 180,
  battingAverage: 18.0,
  strikeRate: 122.5,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 6,
  stumpings: 5,
  overallRating: 52,
  battingRating: 52,
  bowlingRating: 5,
  fieldingRating: 58,
  fitnessRating: 68,
  formRating: 48,
  marketDemand: 32,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 19. Sheldon Jackson
{
  name: 'Sheldon Jackson',
  fullName: 'Sheldon Jackson',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 37,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 8,
  runs: 95,
  battingAverage: 13.6,
  strikeRate: 112.5,
  hundreds: 0,
  fifties: 0,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 5,
  stumpings: 3,
  overallRating: 48,
  battingRating: 48,
  bowlingRating: 5,
  fieldingRating: 55,
  fitnessRating: 55,
  formRating: 42,
  marketDemand: 25,
  basePrice: 20,
  isMarquee: false,
  isCapped: false
},
// 20. Abishek Porel
{
  name: 'Abishek Porel',
  fullName: 'Abishek Porel',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 22,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 10,
  runs: 150,
  battingAverage: 16.7,
  strikeRate: 132.5,
  hundreds: 0,
  fifties: 0,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 6,
  stumpings: 4,
  overallRating: 52,
  battingRating: 52,
  bowlingRating: 5,
  fieldingRating: 58,
  fitnessRating: 72,
  formRating: 52,
  marketDemand: 38,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},

// ===== BATSMEN (21-35) =====

// 21. Vivrant Sharma
{
  name: 'Vivrant Sharma',
  fullName: 'Vivrant Sharma',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 22,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 12,
  runs: 210,
  battingAverage: 19.1,
  strikeRate: 128.5,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 5,
  stumpings: 0,
  overallRating: 55,
  battingRating: 58,
  bowlingRating: 10,
  fieldingRating: 52,
  fitnessRating: 72,
  formRating: 55,
  marketDemand: 40,
  basePrice: 40,
  isMarquee: false,
  isCapped: false
},
// 22. Sachin Baby
{
  name: 'Sachin Baby',
  fullName: 'Sachin Baby',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 36,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 22,
  runs: 350,
  battingAverage: 18.4,
  strikeRate: 118.2,
  hundreds: 0,
  fifties: 2,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 8,
  stumpings: 0,
  overallRating: 50,
  battingRating: 52,
  bowlingRating: 8,
  fieldingRating: 48,
  fitnessRating: 55,
  formRating: 42,
  marketDemand: 28,
  basePrice: 20,
  isMarquee: false,
  isCapped: false
},
// 23. Manan Vohra
{
  name: 'Manan Vohra',
  fullName: 'Manan Vohra',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'OPENER',
  age: 31,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 28,
  runs: 420,
  battingAverage: 17.5,
  strikeRate: 132.8,
  hundreds: 0,
  fifties: 2,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 10,
  stumpings: 0,
  overallRating: 52,
  battingRating: 55,
  bowlingRating: 5,
  fieldingRating: 50,
  fitnessRating: 62,
  formRating: 45,
  marketDemand: 30,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 24. Mandeep Singh
{
  name: 'Mandeep Singh',
  fullName: 'Mandeep Singh',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'OPENER',
  age: 32,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_MEDIUM',
  matches: 30,
  runs: 480,
  battingAverage: 19.2,
  strikeRate: 122.5,
  hundreds: 0,
  fifties: 2,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 12,
  stumpings: 0,
  overallRating: 55,
  battingRating: 58,
  bowlingRating: 5,
  fieldingRating: 55,
  fitnessRating: 62,
  formRating: 48,
  marketDemand: 32,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 25. Gurkeerat Mann
{
  name: 'Gurkeerat Mann',
  fullName: 'Gurkeerat Singh Mann',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 31,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 25,
  runs: 380,
  battingAverage: 17.3,
  strikeRate: 115.8,
  hundreds: 0,
  fifties: 1,
  wickets: 2,
  bowlingAverage: 42.0,
  economy: 8.5,
  bowlingStrikeRate: 29.6,
  bestBowling: '1/12',
  catches: 9,
  stumpings: 0,
  overallRating: 52,
  battingRating: 55,
  bowlingRating: 15,
  fieldingRating: 52,
  fitnessRating: 60,
  formRating: 45,
  marketDemand: 28,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 26. Anmolpreet Singh
{
  name: 'Anmolpreet Singh',
  fullName: 'Anmolpreet Singh',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'OPENER',
  age: 26,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_MEDIUM',
  matches: 8,
  runs: 95,
  battingAverage: 13.6,
  strikeRate: 118.8,
  hundreds: 0,
  fifties: 0,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 3,
  stumpings: 0,
  overallRating: 48,
  battingRating: 50,
  bowlingRating: 5,
  fieldingRating: 48,
  fitnessRating: 68,
  formRating: 45,
  marketDemand: 28,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 27. Vishnu Vinod
{
  name: 'Vishnu Vinod',
  fullName: 'Vishnu Vinod',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 30,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 15,
  runs: 220,
  battingAverage: 16.9,
  strikeRate: 142.5,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 5,
  stumpings: 0,
  overallRating: 52,
  battingRating: 55,
  bowlingRating: 5,
  fieldingRating: 48,
  fitnessRating: 62,
  formRating: 50,
  marketDemand: 32,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 28. Akshath Reddy
{
  name: 'Akshath Reddy',
  fullName: 'Akshath Reddy',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 28,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_MEDIUM',
  matches: 5,
  runs: 55,
  battingAverage: 11.0,
  strikeRate: 105.8,
  hundreds: 0,
  fifties: 0,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 2,
  stumpings: 0,
  overallRating: 45,
  battingRating: 45,
  bowlingRating: 5,
  fieldingRating: 42,
  fitnessRating: 62,
  formRating: 40,
  marketDemand: 25,
  basePrice: 20,
  isMarquee: false,
  isCapped: false
},
// 29. Manoj Tiwary
{
  name: 'Manoj Tiwary',
  fullName: 'Manoj Kumar Tiwary',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 39,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 25,
  runs: 380,
  battingAverage: 19.0,
  strikeRate: 112.5,
  hundreds: 0,
  fifties: 2,
  wickets: 1,
  bowlingAverage: 55.0,
  economy: 9.2,
  bowlingStrikeRate: 35.8,
  bestBowling: '1/22',
  catches: 8,
  stumpings: 0,
  overallRating: 50,
  battingRating: 52,
  bowlingRating: 8,
  fieldingRating: 48,
  fitnessRating: 50,
  formRating: 40,
  marketDemand: 25,
  basePrice: 20,
  isMarquee: false,
  isCapped: false
},
// 30. Ajinkya Rahane
{
  name: 'Ajinkya Rahane',
  fullName: 'Ajinkya Madhukar Rahane',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 36,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_MEDIUM',
  matches: 30,
  runs: 500,
  battingAverage: 20.8,
  strikeRate: 118.5,
  hundreds: 0,
  fifties: 3,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 15,
  stumpings: 0,
  overallRating: 62,
  battingRating: 65,
  bowlingRating: 5,
  fieldingRating: 65,
  fitnessRating: 60,
  formRating: 48,
  marketDemand: 42,
  basePrice: 50,
  isMarquee: false,
  isCapped: true
},
// 31. Cheteshwar Pujara
{
  name: 'Cheteshwar Pujara',
  fullName: 'Cheteshwar Arvind Pujara',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 36,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 20,
  runs: 280,
  battingAverage: 17.5,
  strikeRate: 98.5,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 8,
  stumpings: 0,
  overallRating: 58,
  battingRating: 62,
  bowlingRating: 5,
  fieldingRating: 58,
  fitnessRating: 58,
  formRating: 42,
  marketDemand: 35,
  basePrice: 40,
  isMarquee: false,
  isCapped: true
},
// 32. Suresh Raina
{
  name: 'Suresh Raina',
  fullName: 'Suresh Kumar Raina',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 38,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 30,
  runs: 600,
  battingAverage: 22.2,
  strikeRate: 135.5,
  hundreds: 0,
  fifties: 3,
  wickets: 3,
  bowlingAverage: 45.0,
  economy: 8.8,
  bowlingStrikeRate: 30.7,
  bestBowling: '1/8',
  catches: 18,
  stumpings: 0,
  overallRating: 65,
  battingRating: 68,
  bowlingRating: 15,
  fieldingRating: 68,
  fitnessRating: 52,
  formRating: 42,
  marketDemand: 45,
  basePrice: 50,
  isMarquee: false,
  isCapped: true
},
// 33. Hanuma Vihari
{
  name: 'Hanuma Vihari',
  fullName: 'Hanuma Vihari',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 30,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 10,
  runs: 120,
  battingAverage: 15.0,
  strikeRate: 105.3,
  hundreds: 0,
  fifties: 0,
  wickets: 1,
  bowlingAverage: 38.0,
  economy: 8.2,
  bowlingStrikeRate: 27.8,
  bestBowling: '1/15',
  catches: 4,
  stumpings: 0,
  overallRating: 52,
  battingRating: 55,
  bowlingRating: 12,
  fieldingRating: 55,
  fitnessRating: 65,
  formRating: 45,
  marketDemand: 30,
  basePrice: 30,
  isMarquee: false,
  isCapped: true
},
// 34. Karun Nair
{
  name: 'Karun Nair',
  fullName: 'Karun Nair',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 32,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 22,
  runs: 340,
  battingAverage: 18.9,
  strikeRate: 125.5,
  hundreds: 0,
  fifties: 2,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 7,
  stumpings: 0,
  overallRating: 55,
  battingRating: 58,
  bowlingRating: 8,
  fieldingRating: 55,
  fitnessRating: 62,
  formRating: 50,
  marketDemand: 35,
  basePrice: 35,
  isMarquee: false,
  isCapped: false
},
// 35. Shivam Dube
{
  name: 'Shivam Dube',
  fullName: 'Shivam Dube',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BATSMAN',
  subRole: 'FINISHER',
  age: 31,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_MEDIUM',
  matches: 30,
  runs: 580,
  battingAverage: 24.2,
  strikeRate: 148.5,
  hundreds: 0,
  fifties: 3,
  wickets: 5,
  bowlingAverage: 42.0,
  economy: 9.5,
  bowlingStrikeRate: 26.5,
  bestBowling: '2/18',
  catches: 10,
  stumpings: 0,
  overallRating: 65,
  battingRating: 68,
  bowlingRating: 20,
  fieldingRating: 55,
  fitnessRating: 72,
  formRating: 65,
  marketDemand: 55,
  basePrice: 75,
  isMarquee: false,
  isCapped: true
},

// ===== BOWLERS (36-50) =====

// 36. Shivam Mavi
{
  name: 'Shivam Mavi',
  fullName: 'Shivam Mavi',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 25,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST',
  matches: 22,
  runs: 28,
  battingAverage: 4.7,
  strikeRate: 65.5,
  hundreds: 0,
  fifties: 0,
  wickets: 18,
  bowlingAverage: 30.5,
  economy: 8.95,
  bowlingStrikeRate: 20.5,
  bestBowling: '3/28',
  catches: 5,
  stumpings: 0,
  overallRating: 58,
  battingRating: 8,
  bowlingRating: 62,
  fieldingRating: 50,
  fitnessRating: 72,
  formRating: 55,
  marketDemand: 42,
  basePrice: 40,
  isMarquee: false,
  isCapped: false
},
// 37. Suyash Sharma
{
  name: 'Suyash Sharma',
  fullName: 'Suyash Sharma',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'SPINNER',
  age: 21,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 5,
  runs: 2,
  battingAverage: 1.0,
  strikeRate: 22.5,
  hundreds: 0,
  fifties: 0,
  wickets: 4,
  bowlingAverage: 28.5,
  economy: 7.55,
  bowlingStrikeRate: 22.6,
  bestBowling: '2/18',
  catches: 1,
  stumpings: 0,
  overallRating: 50,
  battingRating: 5,
  bowlingRating: 52,
  fieldingRating: 42,
  fitnessRating: 70,
  formRating: 50,
  marketDemand: 35,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 38. R Sai Kishore
{
  name: 'R Sai Kishore',
  fullName: 'Ravisrinivasan Sai Kishore',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'SPINNER',
  age: 28,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_ORTHODOX',
  matches: 18,
  runs: 22,
  battingAverage: 3.7,
  strikeRate: 72.5,
  hundreds: 0,
  fifties: 0,
  wickets: 15,
  bowlingAverage: 27.5,
  economy: 7.45,
  bowlingStrikeRate: 22.1,
  bestBowling: '3/15',
  catches: 5,
  stumpings: 0,
  overallRating: 58,
  battingRating: 8,
  bowlingRating: 62,
  fieldingRating: 52,
  fitnessRating: 70,
  formRating: 58,
  marketDemand: 42,
  basePrice: 40,
  isMarquee: false,
  isCapped: false
},
// 39. Piyush Chawla
{
  name: 'Piyush Chawla',
  fullName: 'Piyush Chawla',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'SPINNER',
  age: 36,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 30,
  runs: 85,
  battingAverage: 5.7,
  strikeRate: 95.5,
  hundreds: 0,
  fifties: 0,
  wickets: 28,
  bowlingAverage: 30.2,
  economy: 8.15,
  bowlingStrikeRate: 22.2,
  bestBowling: '4/17',
  catches: 8,
  stumpings: 0,
  overallRating: 60,
  battingRating: 12,
  bowlingRating: 65,
  fieldingRating: 48,
  fitnessRating: 55,
  formRating: 48,
  marketDemand: 35,
  basePrice: 40,
  isMarquee: false,
  isCapped: true
},
// 40. Rahul Sharma
{
  name: 'Rahul Sharma',
  fullName: 'Rahul Sharma',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'SPINNER',
  age: 28,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 10,
  runs: 8,
  battingAverage: 2.7,
  strikeRate: 52.5,
  hundreds: 0,
  fifties: 0,
  wickets: 8,
  bowlingAverage: 32.5,
  economy: 8.35,
  bowlingStrikeRate: 23.4,
  bestBowling: '2/22',
  catches: 2,
  stumpings: 0,
  overallRating: 50,
  battingRating: 5,
  bowlingRating: 52,
  fieldingRating: 42,
  fitnessRating: 65,
  formRating: 48,
  marketDemand: 30,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 41. Ishan Porel
{
  name: 'Ishan Porel',
  fullName: 'Ishan Porel',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 25,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 8,
  runs: 5,
  battingAverage: 2.5,
  strikeRate: 38.5,
  hundreds: 0,
  fifties: 0,
  wickets: 6,
  bowlingAverage: 34.5,
  economy: 9.15,
  bowlingStrikeRate: 22.6,
  bestBowling: '2/28',
  catches: 1,
  stumpings: 0,
  overallRating: 48,
  battingRating: 5,
  bowlingRating: 50,
  fieldingRating: 42,
  fitnessRating: 68,
  formRating: 45,
  marketDemand: 28,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 42. Kuldip Yadav
{
  name: 'Kuldip Yadav',
  fullName: 'Kuldip Yadav',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'SPINNER',
  age: 26,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 5,
  runs: 3,
  battingAverage: 1.5,
  strikeRate: 30.0,
  hundreds: 0,
  fifties: 0,
  wickets: 3,
  bowlingAverage: 38.0,
  economy: 8.85,
  bowlingStrikeRate: 25.8,
  bestBowling: '1/15',
  catches: 1,
  stumpings: 0,
  overallRating: 46,
  battingRating: 5,
  bowlingRating: 48,
  fieldingRating: 40,
  fitnessRating: 65,
  formRating: 42,
  marketDemand: 25,
  basePrice: 20,
  isMarquee: false,
  isCapped: false
},
// 43. Shams Mulani
{
  name: 'Shams Mulani',
  fullName: 'Shams Mulani',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'SPINNER',
  age: 27,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_ORTHODOX',
  matches: 8,
  runs: 35,
  battingAverage: 7.0,
  strikeRate: 85.5,
  hundreds: 0,
  fifties: 0,
  wickets: 7,
  bowlingAverage: 30.5,
  economy: 7.65,
  bowlingStrikeRate: 23.9,
  bestBowling: '2/18',
  catches: 3,
  stumpings: 0,
  overallRating: 50,
  battingRating: 12,
  bowlingRating: 52,
  fieldingRating: 45,
  fitnessRating: 68,
  formRating: 50,
  marketDemand: 32,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 44. Tanush Kotian
{
  name: 'Tanush Kotian',
  fullName: 'Tanush Kotian',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'SPINNER',
  age: 25,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 6,
  runs: 18,
  battingAverage: 4.5,
  strikeRate: 72.0,
  hundreds: 0,
  fifties: 0,
  wickets: 5,
  bowlingAverage: 32.0,
  economy: 7.85,
  bowlingStrikeRate: 24.5,
  bestBowling: '2/20',
  catches: 2,
  stumpings: 0,
  overallRating: 48,
  battingRating: 8,
  bowlingRating: 50,
  fieldingRating: 42,
  fitnessRating: 70,
  formRating: 48,
  marketDemand: 30,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 45. Atit Sheth
{
  name: 'Atit Sheth',
  fullName: 'Atit Sheth',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 27,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 5,
  runs: 2,
  battingAverage: 1.0,
  strikeRate: 28.5,
  hundreds: 0,
  fifties: 0,
  wickets: 4,
  bowlingAverage: 30.0,
  economy: 8.75,
  bowlingStrikeRate: 20.6,
  bestBowling: '2/22',
  catches: 1,
  stumpings: 0,
  overallRating: 48,
  battingRating: 5,
  bowlingRating: 50,
  fieldingRating: 42,
  fitnessRating: 65,
  formRating: 45,
  marketDemand: 28,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 46. Mayank Yadav
{
  name: 'Mayank Yadav',
  fullName: 'Mayank Yadav',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 22,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST',
  matches: 6,
  runs: 5,
  battingAverage: 2.5,
  strikeRate: 45.5,
  hundreds: 0,
  fifties: 0,
  wickets: 8,
  bowlingAverage: 18.5,
  economy: 7.25,
  bowlingStrikeRate: 15.3,
  bestBowling: '3/14',
  catches: 2,
  stumpings: 0,
  overallRating: 62,
  battingRating: 5,
  bowlingRating: 68,
  fieldingRating: 48,
  fitnessRating: 65,
  formRating: 65,
  marketDemand: 55,
  basePrice: 75,
  isMarquee: false,
  isCapped: false
},
// 47. Vaibhav Arora
{
  name: 'Vaibhav Arora',
  fullName: 'Vaibhav Arora',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 26,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 12,
  runs: 5,
  battingAverage: 1.7,
  strikeRate: 32.5,
  hundreds: 0,
  fifties: 0,
  wickets: 10,
  bowlingAverage: 28.5,
  economy: 8.25,
  bowlingStrikeRate: 20.7,
  bestBowling: '3/22',
  catches: 3,
  stumpings: 0,
  overallRating: 55,
  battingRating: 5,
  bowlingRating: 58,
  fieldingRating: 45,
  fitnessRating: 72,
  formRating: 55,
  marketDemand: 40,
  basePrice: 40,
  isMarquee: false,
  isCapped: false
},
// 48. Arjun Tendulkar
{
  name: 'Arjun Tendulkar',
  fullName: 'Arjun Sachin Tendulkar',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 26,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
  matches: 5,
  runs: 12,
  battingAverage: 4.0,
  strikeRate: 72.5,
  hundreds: 0,
  fifties: 0,
  wickets: 3,
  bowlingAverage: 42.0,
  economy: 10.25,
  bowlingStrikeRate: 24.6,
  bestBowling: '1/18',
  catches: 1,
  stumpings: 0,
  overallRating: 45,
  battingRating: 10,
  bowlingRating: 45,
  fieldingRating: 42,
  fitnessRating: 68,
  formRating: 42,
  marketDemand: 35,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 49. Sakariya Chetan
{
  name: 'Chetan Sakariya',
  fullName: 'Chetan Sakariya',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 27,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
  matches: 18,
  runs: 12,
  battingAverage: 2.4,
  strikeRate: 52.5,
  hundreds: 0,
  fifties: 0,
  wickets: 14,
  bowlingAverage: 30.5,
  economy: 8.95,
  bowlingStrikeRate: 20.4,
  bestBowling: '3/36',
  catches: 4,
  stumpings: 0,
  overallRating: 55,
  battingRating: 5,
  bowlingRating: 58,
  fieldingRating: 48,
  fitnessRating: 70,
  formRating: 52,
  marketDemand: 38,
  basePrice: 35,
  isMarquee: false,
  isCapped: false
},
// 50. Navdeep Saini
{
  name: 'Navdeep Saini',
  fullName: 'Navdeep Saini',
  country: 'India',
  nationality: 'INDIAN',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 32,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST',
  matches: 28,
  runs: 18,
  battingAverage: 3.0,
  strikeRate: 55.5,
  hundreds: 0,
  fifties: 0,
  wickets: 22,
  bowlingAverage: 30.8,
  economy: 9.15,
  bowlingStrikeRate: 20.2,
  bestBowling: '3/28',
  catches: 5,
  stumpings: 0,
  overallRating: 60,
  battingRating: 5,
  bowlingRating: 65,
  fieldingRating: 48,
  fitnessRating: 68,
  formRating: 52,
  marketDemand: 40,
  basePrice: 40,
  isMarquee: false,
  isCapped: true
},

// ===== ALL-ROUNDERS (51-60) =====

// 51. Nitish Kumar Reddy
{
  name: 'Nitish Kumar Reddy',
  fullName: 'Nitish Kumar Reddy',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SEAM_ALL_ROUNDER',
  age: 22,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_MEDIUM',
  matches: 18,
  runs: 350,
  battingAverage: 23.3,
  strikeRate: 142.5,
  hundreds: 0,
  fifties: 2,
  wickets: 8,
  bowlingAverage: 35.5,
  economy: 9.25,
  bowlingStrikeRate: 23.0,
  bestBowling: '2/15',
  catches: 7,
  stumpings: 0,
  overallRating: 62,
  battingRating: 62,
  bowlingRating: 38,
  fieldingRating: 55,
  fitnessRating: 75,
  formRating: 65,
  marketDemand: 55,
  basePrice: 75,
  isMarquee: false,
  isCapped: false
},
// 52. Abdul Samad
{
  name: 'Abdul Samad',
  fullName: 'Abdul Samad',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SEAM_ALL_ROUNDER',
  age: 22,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 20,
  runs: 320,
  battingAverage: 18.8,
  strikeRate: 145.5,
  hundreds: 0,
  fifties: 1,
  wickets: 3,
  bowlingAverage: 42.0,
  economy: 9.5,
  bowlingStrikeRate: 26.5,
  bestBowling: '1/12',
  catches: 6,
  stumpings: 0,
  overallRating: 55,
  battingRating: 58,
  bowlingRating: 18,
  fieldingRating: 52,
  fitnessRating: 72,
  formRating: 55,
  marketDemand: 42,
  basePrice: 40,
  isMarquee: false,
  isCapped: false
},
// 53. Vijay Shankar
{
  name: 'Vijay Shankar',
  fullName: 'Vijay Shankar',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SEAM_ALL_ROUNDER',
  age: 33,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_MEDIUM',
  matches: 28,
  runs: 420,
  battingAverage: 18.3,
  strikeRate: 125.5,
  hundreds: 0,
  fifties: 2,
  wickets: 12,
  bowlingAverage: 32.5,
  economy: 8.85,
  bowlingStrikeRate: 22.0,
  bestBowling: '2/15',
  catches: 10,
  stumpings: 0,
  overallRating: 60,
  battingRating: 58,
  bowlingRating: 40,
  fieldingRating: 58,
  fitnessRating: 60,
  formRating: 50,
  marketDemand: 38,
  basePrice: 40,
  isMarquee: false,
  isCapped: true
},
// 54. Aman Hakim Khan
{
  name: 'Aman Hakim Khan',
  fullName: 'Aman Hakim Khan',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SEAM_ALL_ROUNDER',
  age: 22,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_MEDIUM',
  matches: 5,
  runs: 65,
  battingAverage: 13.0,
  strikeRate: 128.5,
  hundreds: 0,
  fifties: 0,
  wickets: 2,
  bowlingAverage: 38.0,
  economy: 9.5,
  bowlingStrikeRate: 24.0,
  bestBowling: '1/18',
  catches: 2,
  stumpings: 0,
  overallRating: 48,
  battingRating: 48,
  bowlingRating: 25,
  fieldingRating: 45,
  fitnessRating: 72,
  formRating: 48,
  marketDemand: 32,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 55. Baba Indrajith
{
  name: 'Baba Indrajith',
  fullName: 'Baba Indrajith',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SPIN_ALL_ROUNDER',
  age: 28,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 10,
  runs: 145,
  battingAverage: 16.1,
  strikeRate: 112.5,
  hundreds: 0,
  fifties: 1,
  wickets: 5,
  bowlingAverage: 35.0,
  economy: 8.25,
  bowlingStrikeRate: 25.5,
  bestBowling: '2/22',
  catches: 4,
  stumpings: 0,
  overallRating: 50,
  battingRating: 50,
  bowlingRating: 32,
  fieldingRating: 48,
  fitnessRating: 65,
  formRating: 48,
  marketDemand: 28,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 56. Prerak Mankad
{
  name: 'Prerak Mankad',
  fullName: 'Prerak Mankad',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SPIN_ALL_ROUNDER',
  age: 26,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_ORTHODOX',
  matches: 8,
  runs: 85,
  battingAverage: 12.1,
  strikeRate: 105.5,
  hundreds: 0,
  fifties: 0,
  wickets: 6,
  bowlingAverage: 30.5,
  economy: 7.55,
  bowlingStrikeRate: 24.2,
  bestBowling: '2/15',
  catches: 3,
  stumpings: 0,
  overallRating: 48,
  battingRating: 38,
  bowlingRating: 42,
  fieldingRating: 45,
  fitnessRating: 68,
  formRating: 48,
  marketDemand: 30,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 57. Lalit Yadav
{
  name: 'Lalit Yadav',
  fullName: 'Lalit Yadav',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SPIN_ALL_ROUNDER',
  age: 28,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 15,
  runs: 180,
  battingAverage: 15.0,
  strikeRate: 118.5,
  hundreds: 0,
  fifties: 0,
  wickets: 10,
  bowlingAverage: 32.0,
  economy: 8.15,
  bowlingStrikeRate: 23.6,
  bestBowling: '2/18',
  catches: 5,
  stumpings: 0,
  overallRating: 52,
  battingRating: 42,
  bowlingRating: 45,
  fieldingRating: 48,
  fitnessRating: 68,
  formRating: 50,
  marketDemand: 32,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},
// 58. Ripal Patel
{
  name: 'Ripal Patel',
  fullName: 'Ripal Patel',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SEAM_ALL_ROUNDER',
  age: 26,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_MEDIUM',
  matches: 8,
  runs: 110,
  battingAverage: 15.7,
  strikeRate: 132.5,
  hundreds: 0,
  fifties: 0,
  wickets: 4,
  bowlingAverage: 38.5,
  economy: 9.55,
  bowlingStrikeRate: 24.2,
  bestBowling: '1/15',
  catches: 3,
  stumpings: 0,
  overallRating: 48,
  battingRating: 45,
  bowlingRating: 28,
  fieldingRating: 48,
  fitnessRating: 68,
  formRating: 48,
  marketDemand: 28,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 59. Anirudh Singh
{
  name: 'Anirudh Singh',
  fullName: 'Anirudh Singh',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SEAM_ALL_ROUNDER',
  age: 23,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 3,
  runs: 35,
  battingAverage: 11.7,
  strikeRate: 115.5,
  hundreds: 0,
  fifties: 0,
  wickets: 2,
  bowlingAverage: 40.0,
  economy: 9.85,
  bowlingStrikeRate: 24.4,
  bestBowling: '1/18',
  catches: 1,
  stumpings: 0,
  overallRating: 45,
  battingRating: 42,
  bowlingRating: 28,
  fieldingRating: 42,
  fitnessRating: 72,
  formRating: 45,
  marketDemand: 25,
  basePrice: 20,
  isMarquee: false,
  isCapped: false
},
// 60. Swapnil Singh
{
  name: 'Swapnil Singh',
  fullName: 'Swapnil Singh',
  country: 'India',
  nationality: 'INDIAN',
  role: 'ALL_ROUNDER',
  subRole: 'SPIN_ALL_ROUNDER',
  age: 30,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_ORTHODOX',
  matches: 12,
  runs: 125,
  battingAverage: 12.5,
  strikeRate: 108.5,
  hundreds: 0,
  fifties: 0,
  wickets: 10,
  bowlingAverage: 28.5,
  economy: 7.55,
  bowlingStrikeRate: 22.6,
  bestBowling: '3/22',
  catches: 4,
  stumpings: 0,
  overallRating: 52,
  battingRating: 38,
  bowlingRating: 48,
  fieldingRating: 48,
  fitnessRating: 62,
  formRating: 50,
  marketDemand: 30,
  basePrice: 30,
  isMarquee: false,
  isCapped: false
},

// ===== WICKET-KEEPERS (61-65) =====

// 61. Upendra Yadav
{
  name: 'Upendra Yadav',
  fullName: 'Upendra Yadav',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 25,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 5,
  runs: 65,
  battingAverage: 13.0,
  strikeRate: 118.2,
  hundreds: 0,
  fifties: 0,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 4,
  stumpings: 2,
  overallRating: 46,
  battingRating: 45,
  bowlingRating: 5,
  fieldingRating: 55,
  fitnessRating: 68,
  formRating: 45,
  marketDemand: 28,
  basePrice: 20,
  isMarquee: false,
  isCapped: false
},
// 62. Smit Patel
{
  name: 'Smit Patel',
  fullName: 'Smit Patel',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 27,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 3,
  runs: 42,
  battingAverage: 14.0,
  strikeRate: 122.5,
  hundreds: 0,
  fifties: 0,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 3,
  stumpings: 1,
  overallRating: 45,
  battingRating: 42,
  bowlingRating: 5,
  fieldingRating: 55,
  fitnessRating: 65,
  formRating: 42,
  marketDemand: 25,
  basePrice: 20,
  isMarquee: false,
  isCapped: false
},
// 63. Srikar Bharat
{
  name: 'Srikar Bharat',
  fullName: 'Kona Srikar Bharat',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 31,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 12,
  runs: 165,
  battingAverage: 16.5,
  strikeRate: 115.5,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 8,
  stumpings: 5,
  overallRating: 52,
  battingRating: 50,
  bowlingRating: 5,
  fieldingRating: 62,
  fitnessRating: 62,
  formRating: 48,
  marketDemand: 30,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
},
// 64. Aditya Tare
{
  name: 'Aditya Tare',
  fullName: 'Aditya Tare',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 37,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 18,
  runs: 220,
  battingAverage: 14.7,
  strikeRate: 108.5,
  hundreds: 0,
  fifties: 1,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 10,
  stumpings: 6,
  overallRating: 50,
  battingRating: 48,
  bowlingRating: 5,
  fieldingRating: 60,
  fitnessRating: 52,
  formRating: 40,
  marketDemand: 25,
  basePrice: 20,
  isMarquee: false,
  isCapped: false
},
// 65. Kumar Kushagra
{
  name: 'Kumar Kushagra',
  fullName: 'Kumar Kushagra',
  country: 'India',
  nationality: 'INDIAN',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 23,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 4,
  runs: 55,
  battingAverage: 13.8,
  strikeRate: 125.0,
  hundreds: 0,
  fifties: 0,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 3,
  stumpings: 2,
  overallRating: 46,
  battingRating: 45,
  bowlingRating: 5,
  fieldingRating: 55,
  fitnessRating: 72,
  formRating: 48,
  marketDemand: 30,
  basePrice: 25,
  isMarquee: false,
  isCapped: false
}
];
