export const part4b = [
  // 1. Sai Sudharsan
  {
    name: 'Sai Sudharsan',
    fullName: 'Bhardwaj Sai Sudharsan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 22,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 25,
    runs: 750,
    battingAverage: 37.5,
    strikeRate: 139.2,
    hundreds: 0,
    fifties: 6,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 0,
    overallRating: 68,
    battingRating: 72,
    bowlingRating: 10,
    fieldingRating: 62,
    fitnessRating: 80,
    formRating: 68,
    marketDemand: 60,
    basePrice: 50,
    isMarquee: false,
    isCapped: false
  },
  // 2. Nehal Wadhera
  {
    name: 'Nehal Wadhera',
    fullName: 'Nehal Wadhera',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 20,
    runs: 350,
    battingAverage: 25.0,
    strikeRate: 135.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 0,
    overallRating: 62,
    battingRating: 65,
    bowlingRating: 8,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 50,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 3. Shahrukh Khan
  {
    name: 'Shahrukh Khan',
    fullName: 'Masood Shahrukh Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'FINISHER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 35,
    runs: 480,
    battingAverage: 20.0,
    strikeRate: 140.2,
    hundreds: 0,
    fifties: 1,
    wickets: 8,
    bowlingAverage: 35.5,
    economy: 8.8,
    bowlingStrikeRate: 24.2,
    bestBowling: '2/18',
    catches: 12,
    stumpings: 0,
    overallRating: 64,
    battingRating: 62,
    bowlingRating: 45,
    fieldingRating: 60,
    fitnessRating: 78,
    formRating: 62,
    marketDemand: 52,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 4. Jitesh Sharma
  {
    name: 'Jitesh Sharma',
    fullName: 'Jitesh Mohan Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 28,
    runs: 420,
    battingAverage: 22.1,
    strikeRate: 145.6,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 15,
    stumpings: 3,
    overallRating: 65,
    battingRating: 64,
    bowlingRating: 5,
    fieldingRating: 68,
    fitnessRating: 80,
    formRating: 63,
    marketDemand: 55,
    basePrice: 50,
    isMarquee: false,
    isCapped: false
  },
  // 5. Dhruv Jurel
  {
    name: 'Dhruv Jurel',
    fullName: 'Dhruv Chand Jurel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 22,
    runs: 300,
    battingAverage: 25.0,
    strikeRate: 136.4,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 12,
    stumpings: 2,
    overallRating: 66,
    battingRating: 66,
    bowlingRating: 5,
    fieldingRating: 70,
    fitnessRating: 82,
    formRating: 65,
    marketDemand: 58,
    basePrice: 50,
    isMarquee: false,
    isCapped: false
  },
  // 6. Ramandeep Singh
  {
    name: 'Ramandeep Singh',
    fullName: 'Ramandeep Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 15,
    runs: 180,
    battingAverage: 18.0,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 28.5,
    economy: 8.5,
    bowlingStrikeRate: 20.1,
    bestBowling: '3/20',
    catches: 8,
    stumpings: 0,
    overallRating: 60,
    battingRating: 55,
    bowlingRating: 48,
    fieldingRating: 62,
    fitnessRating: 78,
    formRating: 58,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 7. Harshit Rana
  {
    name: 'Harshit Rana',
    fullName: 'Harshit Rana',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 18,
    runs: 45,
    battingAverage: 9.0,
    strikeRate: 110.5,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 24.5,
    economy: 8.4,
    bowlingStrikeRate: 17.5,
    bestBowling: '3/24',
    catches: 5,
    stumpings: 0,
    overallRating: 64,
    battingRating: 25,
    bowlingRating: 68,
    fieldingRating: 55,
    fitnessRating: 82,
    formRating: 66,
    marketDemand: 52,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 8. Vaibhav Arora
  {
    name: 'Vaibhav Arora',
    fullName: 'Vaibhav Arora',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 8,
    battingAverage: 2.0,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 26.2,
    economy: 8.6,
    bowlingStrikeRate: 18.2,
    bestBowling: '3/28',
    catches: 3,
    stumpings: 0,
    overallRating: 60,
    battingRating: 10,
    bowlingRating: 62,
    fieldingRating: 48,
    fitnessRating: 74,
    formRating: 58,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 9. Angkrish Raghuvanshi
  {
    name: 'Angkrish Raghuvanshi',
    fullName: 'Angkrish Raghuvanshi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 19,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 10,
    runs: 180,
    battingAverage: 22.5,
    strikeRate: 138.2,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 58,
    battingRating: 62,
    bowlingRating: 5,
    fieldingRating: 56,
    fitnessRating: 78,
    formRating: 58,
    marketDemand: 48,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 10. Sameer Rizvi
  {
    name: 'Sameer Rizvi',
    fullName: 'Sameer Rizvi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 20,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 8,
    runs: 95,
    battingAverage: 15.8,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 56,
    battingRating: 59,
    bowlingRating: 5,
    fieldingRating: 55,
    fitnessRating: 76,
    formRating: 54,
    marketDemand: 42,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 11. Ashutosh Sharma
  {
    name: 'Ashutosh Sharma',
    fullName: 'Ashutosh Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 12,
    runs: 220,
    battingAverage: 24.4,
    strikeRate: 168.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 62,
    battingRating: 66,
    bowlingRating: 5,
    fieldingRating: 54,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 54,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 12. Shashank Singh
  {
    name: 'Shashank Singh',
    fullName: 'Shashank Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 25,
    runs: 450,
    battingAverage: 28.1,
    strikeRate: 152.4,
    hundreds: 0,
    fifties: 2,
    wickets: 3,
    bowlingAverage: 30.5,
    economy: 8.9,
    bowlingStrikeRate: 20.5,
    bestBowling: '1/12',
    catches: 10,
    stumpings: 0,
    overallRating: 64,
    battingRating: 66,
    bowlingRating: 25,
    fieldingRating: 58,
    fitnessRating: 74,
    formRating: 65,
    marketDemand: 52,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 13. Kumar Kartikeya
  {
    name: 'Kumar Kartikeya',
    fullName: 'Kumar Kartikeya Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_WRIST_SPIN',
    matches: 15,
    runs: 12,
    battingAverage: 3.0,
    strikeRate: 50.0,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 27.5,
    economy: 7.9,
    bowlingStrikeRate: 20.8,
    bestBowling: '2/18',
    catches: 4,
    stumpings: 0,
    overallRating: 58,
    battingRating: 12,
    bowlingRating: 60,
    fieldingRating: 50,
    fitnessRating: 72,
    formRating: 56,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 14. Akash Madhwal
  {
    name: 'Akash Madhwal',
    fullName: 'Akash Madhwal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM_FAST',
    matches: 16,
    runs: 5,
    battingAverage: 1.5,
    strikeRate: 40.0,
    hundreds: 0,
    fifties: 0,
    wickets: 20,
    bowlingAverage: 23.4,
    economy: 8.5,
    bowlingStrikeRate: 16.5,
    bestBowling: '5/5',
    catches: 4,
    stumpings: 0,
    overallRating: 62,
    battingRating: 8,
    bowlingRating: 65,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 50,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 15. Mayank Yadav
  {
    name: 'Mayank Yadav',
    fullName: 'Mayank Yadav',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 6,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 10,
    bowlingAverage: 18.2,
    economy: 7.2,
    bowlingStrikeRate: 15.1,
    bestBowling: '3/14',
    catches: 1,
    stumpings: 0,
    overallRating: 65,
    battingRating: 5,
    bowlingRating: 70,
    fieldingRating: 54,
    fitnessRating: 80,
    formRating: 68,
    marketDemand: 60,
    basePrice: 50,
    isMarquee: false,
    isCapped: false
  },
  // 16. Rasikh Salam
  {
    name: 'Rasikh Salam',
    fullName: 'Rasikh Salam Dar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 12,
    runs: 14,
    battingAverage: 4.5,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 28.2,
    economy: 8.9,
    bowlingStrikeRate: 19.0,
    bestBowling: '3/34',
    catches: 3,
    stumpings: 0,
    overallRating: 58,
    battingRating: 15,
    bowlingRating: 60,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 57,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 17. Nitish Kumar Reddy
  {
    name: 'Nitish Kumar Reddy',
    fullName: 'Nitish Kumar Reddy',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 18,
    runs: 360,
    battingAverage: 32.7,
    strikeRate: 142.8,
    hundreds: 0,
    fifties: 2,
    wickets: 8,
    bowlingAverage: 28.8,
    economy: 8.5,
    bowlingStrikeRate: 20.3,
    bestBowling: '3/19',
    catches: 8,
    stumpings: 0,
    overallRating: 66,
    battingRating: 68,
    bowlingRating: 55,
    fieldingRating: 62,
    fitnessRating: 82,
    formRating: 66,
    marketDemand: 58,
    basePrice: 50,
    isMarquee: false,
    isCapped: false
  },
  // 18. Abdul Samad
  {
    name: 'Abdul Samad',
    fullName: 'Abdul Samad',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 38,
    runs: 450,
    battingAverage: 19.5,
    strikeRate: 142.3,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 45.0,
    economy: 9.8,
    bowlingStrikeRate: 27.5,
    bestBowling: '1/9',
    catches: 15,
    stumpings: 0,
    overallRating: 60,
    battingRating: 62,
    bowlingRating: 25,
    fieldingRating: 54,
    fitnessRating: 78,
    formRating: 58,
    marketDemand: 48,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 19. Umran Malik
  {
    name: 'Umran Malik',
    fullName: 'Umran Malik',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 26,
    runs: 10,
    battingAverage: 2.0,
    strikeRate: 55.0,
    hundreds: 0,
    fifties: 0,
    wickets: 29,
    bowlingAverage: 27.2,
    economy: 9.2,
    bowlingStrikeRate: 17.7,
    bestBowling: '5/25',
    catches: 5,
    stumpings: 0,
    overallRating: 63,
    battingRating: 8,
    bowlingRating: 65,
    fieldingRating: 50,
    fitnessRating: 82,
    formRating: 60,
    marketDemand: 52,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 20. Rahul Tewatia
  {
    name: 'Rahul Tewatia',
    fullName: 'Rahul Tewatia',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 31,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 78,
    runs: 950,
    battingAverage: 25.6,
    strikeRate: 135.2,
    hundreds: 0,
    fifties: 1,
    wickets: 32,
    bowlingAverage: 32.4,
    economy: 8.35,
    bowlingStrikeRate: 23.2,
    bestBowling: '3/25',
    catches: 22,
    stumpings: 0,
    overallRating: 65,
    battingRating: 62,
    bowlingRating: 58,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 63,
    marketDemand: 55,
    basePrice: 50,
    isMarquee: false,
    isCapped: false
  },
  // 21. Riyan Parag
  {
    name: 'Riyan Parag',
    fullName: 'Riyan Parag',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 54,
    runs: 980,
    battingAverage: 24.5,
    strikeRate: 138.8,
    hundreds: 0,
    fifties: 6,
    wickets: 4,
    bowlingAverage: 48.0,
    economy: 8.6,
    bowlingStrikeRate: 33.5,
    bestBowling: '1/12',
    catches: 32,
    stumpings: 0,
    overallRating: 67,
    battingRating: 70,
    bowlingRating: 35,
    fieldingRating: 68,
    fitnessRating: 82,
    formRating: 68,
    marketDemand: 58,
    basePrice: 50,
    isMarquee: false,
    isCapped: false
  },
  // 22. Mahipal Lomror
  {
    name: 'Mahipal Lomror',
    fullName: 'Mahipal Krishan Lomror',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 32,
    runs: 450,
    battingAverage: 18.5,
    strikeRate: 138.4,
    hundreds: 0,
    fifties: 1,
    wickets: 1,
    bowlingAverage: 55.0,
    economy: 9.0,
    bowlingStrikeRate: 36.0,
    bestBowling: '1/21',
    catches: 10,
    stumpings: 0,
    overallRating: 61,
    battingRating: 64,
    bowlingRating: 28,
    fieldingRating: 54,
    fitnessRating: 75,
    formRating: 59,
    marketDemand: 46,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 23. Suyash Sharma
  {
    name: 'Suyash Sharma',
    fullName: 'Suyash Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 12,
    runs: 4,
    battingAverage: 2.0,
    strikeRate: 60.0,
    hundreds: 0,
    fifties: 0,
    wickets: 10,
    bowlingAverage: 32.1,
    economy: 8.2,
    bowlingStrikeRate: 23.5,
    bestBowling: '3/30',
    catches: 2,
    stumpings: 0,
    overallRating: 60,
    battingRating: 8,
    bowlingRating: 63,
    fieldingRating: 50,
    fitnessRating: 78,
    formRating: 58,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 24. Anukul Roy
  {
    name: 'Anukul Roy',
    fullName: 'Anukul Sudhakar Roy',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 10,
    runs: 85,
    battingAverage: 14.1,
    strikeRate: 121.4,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 29.5,
    economy: 7.8,
    bowlingStrikeRate: 22.6,
    bestBowling: '2/15',
    catches: 5,
    stumpings: 0,
    overallRating: 57,
    battingRating: 48,
    bowlingRating: 58,
    fieldingRating: 60,
    fitnessRating: 76,
    formRating: 55,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 25. Rajvardhan Hangargekar
  {
    name: 'Rajvardhan Hangargekar',
    fullName: 'Rajvardhan Hangargekar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 15,
    battingAverage: 7.5,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 28.5,
    economy: 9.5,
    bowlingStrikeRate: 18.0,
    bestBowling: '3/36',
    catches: 2,
    stumpings: 0,
    overallRating: 56,
    battingRating: 30,
    bowlingRating: 58,
    fieldingRating: 50,
    fitnessRating: 80,
    formRating: 54,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 26. Nishant Sindhu
  {
    name: 'Nishant Sindhu',
    fullName: 'Nishant Sindhu',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 20,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 3,
    runs: 25,
    battingAverage: 12.5,
    strikeRate: 110.0,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 32.0,
    economy: 8.0,
    bowlingStrikeRate: 24.0,
    bestBowling: '1/18',
    catches: 1,
    stumpings: 0,
    overallRating: 54,
    battingRating: 48,
    bowlingRating: 52,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 27. Shaik Rasheed
  {
    name: 'Shaik Rasheed',
    fullName: 'Shaik Rasheed',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 2,
    runs: 12,
    battingAverage: 6.0,
    strikeRate: 92.3,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 1,
    stumpings: 0,
    overallRating: 52,
    battingRating: 55,
    bowlingRating: 10,
    fieldingRating: 54,
    fitnessRating: 74,
    formRating: 50,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 28. Sanvir Singh
  {
    name: 'Sanvir Singh',
    fullName: 'Sanvir Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 5,
    runs: 48,
    battingAverage: 16.0,
    strikeRate: 133.3,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 45.0,
    economy: 9.0,
    bowlingStrikeRate: 30.0,
    bestBowling: '1/25',
    catches: 2,
    stumpings: 0,
    overallRating: 55,
    battingRating: 52,
    bowlingRating: 48,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 29. Upendra Yadav
  {
    name: 'Upendra Yadav',
    fullName: 'Upendra Dewan Singh Yadav',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 4,
    runs: 32,
    battingAverage: 10.7,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 1,
    overallRating: 53,
    battingRating: 50,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 70,
    formRating: 51,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 30. Kumar Kushagra
  {
    name: 'Kumar Kushagra',
    fullName: 'Kumar Kushagra',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 19,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 6,
    runs: 62,
    battingAverage: 15.5,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 56,
    battingRating: 55,
    bowlingRating: 5,
    fieldingRating: 60,
    fitnessRating: 76,
    formRating: 54,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 31. Robin Minz
  {
    name: 'Robin Minz',
    fullName: 'Robin Minz',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 21,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 0,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 0,
    stumpings: 0,
    overallRating: 54,
    battingRating: 52,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 78,
    formRating: 52,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 32. Sumit Kumar
  {
    name: 'Sumit Kumar',
    fullName: 'Sumit Kumar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 6,
    runs: 35,
    battingAverage: 8.8,
    strikeRate: 110.5,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 38.5,
    economy: 9.2,
    bowlingStrikeRate: 25.0,
    bestBowling: '1/20',
    catches: 2,
    stumpings: 0,
    overallRating: 53,
    battingRating: 45,
    bowlingRating: 52,
    fieldingRating: 50,
    fitnessRating: 72,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 33. Swastik Chikara
  {
    name: 'Swastik Chikara',
    fullName: 'Swastik Chikara',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 0,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 0,
    stumpings: 0,
    overallRating: 51,
    battingRating: 54,
    bowlingRating: 5,
    fieldingRating: 48,
    fitnessRating: 75,
    formRating: 50,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 34. Saurav Chauhan
  {
    name: 'Saurav Chauhan',
    fullName: 'Saurav Chauhan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 3,
    runs: 28,
    battingAverage: 9.3,
    strikeRate: 140.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 1,
    stumpings: 0,
    overallRating: 52,
    battingRating: 55,
    bowlingRating: 5,
    fieldingRating: 50,
    fitnessRating: 73,
    formRating: 50,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 35. Tanay Thyagarajan
  {
    name: 'Tanay Thyagarajan',
    fullName: 'Tanay Thyagarajan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 28,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 4,
    runs: 10,
    battingAverage: 5.0,
    strikeRate: 90.0,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 30.0,
    economy: 7.5,
    bowlingStrikeRate: 24.0,
    bestBowling: '1/20',
    catches: 2,
    stumpings: 0,
    overallRating: 56,
    battingRating: 15,
    bowlingRating: 58,
    fieldingRating: 52,
    fitnessRating: 70,
    formRating: 54,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 36. Manav Suthar
  {
    name: 'Manav Suthar',
    fullName: 'Manav Suthar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 21,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 2,
    runs: 5,
    battingAverage: 5.0,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 28.0,
    economy: 7.0,
    bowlingStrikeRate: 24.0,
    bestBowling: '1/15',
    catches: 1,
    stumpings: 0,
    overallRating: 58,
    battingRating: 20,
    bowlingRating: 60,
    fieldingRating: 54,
    fitnessRating: 78,
    formRating: 56,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 37. Shams Mulani
  {
    name: 'Shams Mulani',
    fullName: 'Shams Zakir Mulani',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 8,
    runs: 75,
    battingAverage: 12.5,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 32.5,
    economy: 8.1,
    bowlingStrikeRate: 24.0,
    bestBowling: '2/25',
    catches: 4,
    stumpings: 0,
    overallRating: 60,
    battingRating: 48,
    bowlingRating: 58,
    fieldingRating: 54,
    fitnessRating: 75,
    formRating: 58,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 38. Himanshu Sharma
  {
    name: 'Himanshu Sharma',
    fullName: 'Himanshu Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 2,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 48.0,
    economy: 9.6,
    bowlingStrikeRate: 30.0,
    bestBowling: '1/28',
    catches: 0,
    stumpings: 0,
    overallRating: 50,
    battingRating: 5,
    bowlingRating: 52,
    fieldingRating: 45,
    fitnessRating: 70,
    formRating: 48,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 39. Rajan Kumar
  {
    name: 'Rajan Kumar',
    fullName: 'Rajan Kumar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 0,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 0,
    stumpings: 0,
    overallRating: 55,
    battingRating: 8,
    bowlingRating: 58,
    fieldingRating: 48,
    fitnessRating: 76,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 40. Vyshak Vijaykumar
  {
    name: 'Vijaykumar Vyshak',
    fullName: 'Vijaykumar Vyshak',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 12,
    runs: 10,
    battingAverage: 3.3,
    strikeRate: 65.0,
    hundreds: 0,
    fifties: 0,
    wickets: 13,
    bowlingAverage: 28.5,
    economy: 9.1,
    bowlingStrikeRate: 18.8,
    bestBowling: '3/20',
    catches: 3,
    stumpings: 0,
    overallRating: 61,
    battingRating: 12,
    bowlingRating: 63,
    fieldingRating: 52,
    fitnessRating: 76,
    formRating: 60,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 41. Manoj Bhandage
  {
    name: 'Manoj Bhandage',
    fullName: 'Manoj Bhandage',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM_FAST',
    matches: 0,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 0,
    stumpings: 0,
    overallRating: 54,
    battingRating: 48,
    bowlingRating: 48,
    fieldingRating: 52,
    fitnessRating: 76,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 42. Akash Singh
  {
    name: 'Akash Singh',
    fullName: 'Akash Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 6,
    runs: 2,
    battingAverage: 1.0,
    strikeRate: 22.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 34.2,
    economy: 9.8,
    bowlingStrikeRate: 20.8,
    bestBowling: '2/27',
    catches: 1,
    stumpings: 0,
    overallRating: 56,
    battingRating: 5,
    bowlingRating: 58,
    fieldingRating: 45,
    fitnessRating: 75,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 43. Darshan Nalkande
  {
    name: 'Darshan Nalkande',
    fullName: 'Darshan Nalkande',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 25,
    battingAverage: 8.3,
    strikeRate: 122.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 30.5,
    economy: 9.2,
    bowlingStrikeRate: 19.8,
    bestBowling: '2/25',
    catches: 2,
    stumpings: 0,
    overallRating: 57,
    battingRating: 25,
    bowlingRating: 58,
    fieldingRating: 50,
    fitnessRating: 74,
    formRating: 55,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 44. Sai Kishore
  {
    name: 'Sai Kishore',
    fullName: 'Ravisrinivasan Sai Kishore',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 12,
    runs: 22,
    battingAverage: 7.3,
    strikeRate: 88.0,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 24.5,
    economy: 7.6,
    bowlingStrikeRate: 19.3,
    bestBowling: '4/21',
    catches: 4,
    stumpings: 0,
    overallRating: 64,
    battingRating: 22,
    bowlingRating: 66,
    fieldingRating: 58,
    fitnessRating: 78,
    formRating: 62,
    marketDemand: 50,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 45. Sandeep Warrier
  {
    name: 'Sandeep Warrier',
    fullName: 'Sandeep Warrier',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 8,
    runs: 4,
    battingAverage: 2.0,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 38.5,
    economy: 8.9,
    bowlingStrikeRate: 25.8,
    bestBowling: '2/22',
    catches: 2,
    stumpings: 0,
    overallRating: 60,
    battingRating: 5,
    bowlingRating: 61,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 58,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 46. Mukesh Choudhary
  {
    name: 'Mukesh Choudhary',
    fullName: 'Mukesh Choudhary',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 13,
    runs: 6,
    battingAverage: 3.0,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 16,
    bowlingAverage: 26.5,
    economy: 8.8,
    bowlingStrikeRate: 18.0,
    bestBowling: '4/46',
    catches: 3,
    stumpings: 0,
    overallRating: 61,
    battingRating: 8,
    bowlingRating: 63,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 47. Simarjeet Singh
  {
    name: 'Simarjeet Singh',
    fullName: 'Simarjeet Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 10,
    runs: 12,
    battingAverage: 6.0,
    strikeRate: 75.0,
    hundreds: 0,
    fifties: 0,
    wickets: 9,
    bowlingAverage: 31.2,
    economy: 8.65,
    bowlingStrikeRate: 21.5,
    bestBowling: '2/21',
    catches: 3,
    stumpings: 0,
    overallRating: 59,
    battingRating: 12,
    bowlingRating: 60,
    fieldingRating: 50,
    fitnessRating: 76,
    formRating: 58,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 48. Prashant Solanki
  {
    name: 'Prashant Solanki',
    fullName: 'Prashant Solanki',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 2,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 19.0,
    economy: 6.3,
    bowlingStrikeRate: 18.0,
    bestBowling: '2/20',
    catches: 1,
    stumpings: 0,
    overallRating: 53,
    battingRating: 5,
    bowlingRating: 55,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 51,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 49. Ajay Mandal
  {
    name: 'Ajay Mandal',
    fullName: 'Ajay Jadav Mandal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 28,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 0,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 0,
    stumpings: 0,
    overallRating: 54,
    battingRating: 48,
    bowlingRating: 48,
    fieldingRating: 52,
    fitnessRating: 73,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 50. Kunal Singh Rathore
  {
    name: 'Kunal Singh Rathore',
    fullName: 'Kunal Singh Rathore',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 21,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 0,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 0,
    stumpings: 0,
    overallRating: 50,
    battingRating: 48,
    bowlingRating: 5,
    fieldingRating: 55,
    fitnessRating: 74,
    formRating: 48,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 51. Yudhvir Singh
  {
    name: 'Yudhvir Singh',
    fullName: 'Yudhvir Singh Charak',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 18,
    battingAverage: 9.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 35.3,
    economy: 8.8,
    bowlingStrikeRate: 24.0,
    bestBowling: '2/27',
    catches: 2,
    stumpings: 0,
    overallRating: 56,
    battingRating: 45,
    bowlingRating: 54,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 52. Atharva Taide
  {
    name: 'Atharva Taide',
    fullName: 'Atharva Taide',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 10,
    runs: 186,
    battingAverage: 20.7,
    strikeRate: 128.3,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 57,
    battingRating: 60,
    bowlingRating: 5,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 55,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 53. Vidwath Kaverappa
  {
    name: 'Vidwath Kaverappa',
    fullName: 'Vidwath Kaverappa',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 2,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 35.0,
    economy: 8.75,
    bowlingStrikeRate: 24.0,
    bestBowling: '2/35',
    catches: 1,
    stumpings: 0,
    overallRating: 59,
    battingRating: 8,
    bowlingRating: 61,
    fieldingRating: 50,
    fitnessRating: 78,
    formRating: 57,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 54. Mayank Dagar
  {
    name: 'Mayank Dagar',
    fullName: 'Mayank Dagar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 5,
    runs: 15,
    battingAverage: 7.5,
    strikeRate: 95.0,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 42.0,
    economy: 8.4,
    bowlingStrikeRate: 30.0,
    bestBowling: '1/24',
    catches: 3,
    stumpings: 0,
    overallRating: 58,
    battingRating: 18,
    bowlingRating: 59,
    fieldingRating: 62,
    fitnessRating: 78,
    formRating: 56,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 55. Prithvi Shaw
  {
    name: 'Prithvi Shaw',
    fullName: 'Prithvi Pankaj Shaw',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 75,
    runs: 1690,
    battingAverage: 23.5,
    strikeRate: 145.8,
    hundreds: 1,
    fifties: 12,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 25,
    stumpings: 0,
    overallRating: 68,
    battingRating: 73,
    bowlingRating: 5,
    fieldingRating: 54,
    fitnessRating: 65,
    formRating: 62,
    marketDemand: 58,
    basePrice: 50,
    isMarquee: false,
    isCapped: false
  },
  // 56. Sarfaraz Khan
  {
    name: 'Sarfaraz Khan',
    fullName: 'Sarfaraz Naushad Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 50,
    runs: 580,
    battingAverage: 22.3,
    strikeRate: 130.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 18,
    stumpings: 0,
    overallRating: 65,
    battingRating: 68,
    bowlingRating: 10,
    fieldingRating: 52,
    fitnessRating: 68,
    formRating: 64,
    marketDemand: 54,
    basePrice: 50,
    isMarquee: false,
    isCapped: false
  },
  // 57. Chetan Sakariya
  {
    name: 'Chetan Sakariya',
    fullName: 'Chetan Sakariya',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 19,
    runs: 16,
    battingAverage: 4.0,
    strikeRate: 65.0,
    hundreds: 0,
    fifties: 0,
    wickets: 20,
    bowlingAverage: 28.5,
    economy: 8.4,
    bowlingStrikeRate: 20.3,
    bestBowling: '3/31',
    catches: 5,
    stumpings: 0,
    overallRating: 61,
    battingRating: 10,
    bowlingRating: 63,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 58,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 58. Kamlesh Nagarkoti
  {
    name: 'Kamlesh Nagarkoti',
    fullName: 'Kamlesh Nagarkoti',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 12,
    runs: 22,
    battingAverage: 5.5,
    strikeRate: 90.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 45.2,
    economy: 9.5,
    bowlingStrikeRate: 28.5,
    bestBowling: '2/13',
    catches: 4,
    stumpings: 0,
    overallRating: 55,
    battingRating: 15,
    bowlingRating: 56,
    fieldingRating: 62,
    fitnessRating: 72,
    formRating: 52,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 59. Shivam Mavi
  {
    name: 'Shivam Mavi',
    fullName: 'Shivam Mavi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 32,
    runs: 55,
    battingAverage: 6.8,
    strikeRate: 105.0,
    hundreds: 0,
    fifties: 0,
    wickets: 30,
    bowlingAverage: 31.4,
    economy: 8.7,
    bowlingStrikeRate: 21.6,
    bestBowling: '4/21',
    catches: 8,
    stumpings: 0,
    overallRating: 62,
    battingRating: 20,
    bowlingRating: 64,
    fieldingRating: 58,
    fitnessRating: 78,
    formRating: 60,
    marketDemand: 50,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 60. Ishan Porel
  {
    name: 'Ishan Porel',
    fullName: 'Ishan Porel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 38.5,
    economy: 9.8,
    bowlingStrikeRate: 23.5,
    bestBowling: '1/25',
    catches: 1,
    stumpings: 0,
    overallRating: 56,
    battingRating: 5,
    bowlingRating: 58,
    fieldingRating: 46,
    fitnessRating: 74,
    formRating: 53,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 61. Hrithik Shokeen
  {
    name: 'Hrithik Shokeen',
    fullName: 'Hrithik Shokeen',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 13,
    runs: 66,
    battingAverage: 11.0,
    strikeRate: 115.8,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 38.4,
    economy: 8.2,
    bowlingStrikeRate: 28.0,
    bestBowling: '2/13',
    catches: 6,
    stumpings: 0,
    overallRating: 57,
    battingRating: 46,
    bowlingRating: 56,
    fieldingRating: 56,
    fitnessRating: 76,
    formRating: 54,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 62. Lalit Yadav
  {
    name: 'Lalit Yadav',
    fullName: 'Lalit Yadav',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 25,
    runs: 280,
    battingAverage: 17.5,
    strikeRate: 115.0,
    hundreds: 0,
    fifties: 0,
    wickets: 10,
    bowlingAverage: 30.5,
    economy: 8.1,
    bowlingStrikeRate: 22.5,
    bestBowling: '2/11',
    catches: 10,
    stumpings: 0,
    overallRating: 59,
    battingRating: 52,
    bowlingRating: 56,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 57,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 63. Aman Khan
  {
    name: 'Aman Khan',
    fullName: 'Aman Hakim Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 14,
    runs: 110,
    battingAverage: 10.0,
    strikeRate: 122.2,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 55.0,
    economy: 9.6,
    bowlingStrikeRate: 34.0,
    bestBowling: '1/15',
    catches: 6,
    stumpings: 0,
    overallRating: 55,
    battingRating: 50,
    bowlingRating: 46,
    fieldingRating: 54,
    fitnessRating: 76,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 64. Ripal Patel
  {
    name: 'Ripal Patel',
    fullName: 'Ripal Patel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 10,
    runs: 85,
    battingAverage: 12.1,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 53,
    battingRating: 52,
    bowlingRating: 10,
    fieldingRating: 50,
    fitnessRating: 74,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 65. Baba Indrajith
  {
    name: 'Baba Indrajith',
    fullName: 'Baba Indrajith',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 3,
    runs: 21,
    battingAverage: 7.0,
    strikeRate: 95.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 2,
    stumpings: 0,
    overallRating: 55,
    battingRating: 58,
    bowlingRating: 10,
    fieldingRating: 52,
    fitnessRating: 70,
    formRating: 52,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 66. Prerak Mankad
  {
    name: 'Prerak Mankad',
    fullName: 'Prerak Mankad',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 6,
    runs: 98,
    battingAverage: 24.5,
    strikeRate: 120.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 8.5,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 56,
    battingRating: 54,
    bowlingRating: 44,
    fieldingRating: 54,
    fitnessRating: 72,
    formRating: 53,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 67. Mohsin Khan
  {
    name: 'Mohsin Khan',
    fullName: 'Mohsin Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 22,
    runs: 25,
    battingAverage: 5.0,
    strikeRate: 90.0,
    hundreds: 0,
    fifties: 0,
    wickets: 27,
    bowlingAverage: 22.5,
    economy: 8.1,
    bowlingStrikeRate: 16.6,
    bestBowling: '4/16',
    catches: 6,
    stumpings: 0,
    overallRating: 64,
    battingRating: 15,
    bowlingRating: 66,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 62,
    marketDemand: 52,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 68. Yash Thakur
  {
    name: 'Yash Thakur',
    fullName: 'Yash Thakur',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 19,
    runs: 8,
    battingAverage: 2.0,
    strikeRate: 50.0,
    hundreds: 0,
    fifties: 0,
    wickets: 24,
    bowlingAverage: 25.5,
    economy: 9.0,
    bowlingStrikeRate: 17.0,
    bestBowling: '5/30',
    catches: 4,
    stumpings: 0,
    overallRating: 61,
    battingRating: 8,
    bowlingRating: 63,
    fieldingRating: 50,
    fitnessRating: 76,
    formRating: 60,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 69. Mayank Markande
  {
    name: 'Mayank Markande',
    fullName: 'Mayank Markande',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 35,
    runs: 35,
    battingAverage: 5.0,
    strikeRate: 72.0,
    hundreds: 0,
    fifties: 0,
    wickets: 32,
    bowlingAverage: 29.2,
    economy: 8.3,
    bowlingStrikeRate: 21.1,
    bestBowling: '4/23',
    catches: 8,
    stumpings: 0,
    overallRating: 62,
    battingRating: 12,
    bowlingRating: 64,
    fieldingRating: 54,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 70. Murugan Ashwin
  {
    name: 'Murugan Ashwin',
    fullName: 'Murugan Ashwin',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 35,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 44,
    runs: 32,
    battingAverage: 4.0,
    strikeRate: 75.0,
    hundreds: 0,
    fifties: 0,
    wickets: 35,
    bowlingAverage: 33.5,
    economy: 7.9,
    bowlingStrikeRate: 25.4,
    bestBowling: '3/21',
    catches: 12,
    stumpings: 0,
    overallRating: 58,
    battingRating: 8,
    bowlingRating: 60,
    fieldingRating: 55,
    fitnessRating: 70,
    formRating: 54,
    marketDemand: 40,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 71. Shreyas Gopal
  {
    name: 'Shreyas Gopal',
    fullName: 'Shreyas Gopal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 49,
    runs: 180,
    battingAverage: 12.0,
    strikeRate: 110.5,
    hundreds: 0,
    fifties: 0,
    wickets: 49,
    bowlingAverage: 26.2,
    economy: 8.1,
    bowlingStrikeRate: 19.4,
    bestBowling: '4/16',
    catches: 14,
    stumpings: 0,
    overallRating: 62,
    battingRating: 42,
    bowlingRating: 64,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 58,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 72. KC Cariappa
  {
    name: 'KC Cariappa',
    fullName: 'Konganda Charamanna Cariappa',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 11,
    runs: 15,
    battingAverage: 5.0,
    strikeRate: 80.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 35.8,
    economy: 8.4,
    bowlingStrikeRate: 25.5,
    bestBowling: '2/18',
    catches: 2,
    stumpings: 0,
    overallRating: 55,
    battingRating: 10,
    bowlingRating: 56,
    fieldingRating: 50,
    fitnessRating: 70,
    formRating: 51,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 73. Jagadeesha Suchith
  {
    name: 'Jagadeesha Suchith',
    fullName: 'Jagadeesha Suchith',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 22,
    runs: 75,
    battingAverage: 10.7,
    strikeRate: 120.0,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 38.0,
    economy: 8.5,
    bowlingStrikeRate: 26.8,
    bestBowling: '2/14',
    catches: 10,
    stumpings: 0,
    overallRating: 58,
    battingRating: 40,
    bowlingRating: 58,
    fieldingRating: 60,
    fitnessRating: 74,
    formRating: 55,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 74. Pawan Negi
  {
    name: 'Pawan Negi',
    fullName: 'Pawan Negi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 33,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 50,
    runs: 365,
    battingAverage: 14.0,
    strikeRate: 126.2,
    hundreds: 0,
    fifties: 0,
    wickets: 34,
    bowlingAverage: 29.8,
    economy: 7.9,
    bowlingStrikeRate: 22.6,
    bestBowling: '4/18',
    catches: 18,
    stumpings: 0,
    overallRating: 56,
    battingRating: 48,
    bowlingRating: 55,
    fieldingRating: 60,
    fitnessRating: 70,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 75. Shahbaz Ahmed
  {
    name: 'Shahbaz Ahmed',
    fullName: 'Shahbaz Ahmed',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 29,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 39,
    runs: 380,
    battingAverage: 19.0,
    strikeRate: 121.8,
    hundreds: 0,
    fifties: 0,
    wickets: 14,
    bowlingAverage: 35.8,
    economy: 8.5,
    bowlingStrikeRate: 25.2,
    bestBowling: '3/7',
    catches: 14,
    stumpings: 0,
    overallRating: 63,
    battingRating: 60,
    bowlingRating: 60,
    fieldingRating: 60,
    fitnessRating: 78,
    formRating: 62,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  }
];
