export const part1 = [
  {
    name: 'Virat Kohli',
    fullName: 'Virat Kohli',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 36,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 237,
    runs: 7579,
    battingAverage: 37.25,
    strikeRate: 131.61,
    hundreds: 7,
    fifties: 50,
    wickets: 4,
    bowlingAverage: 45.0,
    economy: 8.5,
    bowlingStrikeRate: 32.0,
    bestBowling: '1/10',
    catches: 130,
    stumpings: 0,
    overallRating: 95,
    battingRating: 97,
    bowlingRating: 15,
    fieldingRating: 90,
    fitnessRating: 92,
    formRating: 90,
    marketDemand: 98,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'Rohit Sharma',
    fullName: 'Rohit Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 37,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 243,
    runs: 6628,
    battingAverage: 30.21,
    strikeRate: 130.61,
    hundreds: 2,
    fifties: 42,
    wickets: 15,
    bowlingAverage: 38.0,
    economy: 8.2,
    bowlingStrikeRate: 28.0,
    bestBowling: '1/8',
    catches: 95,
    stumpings: 0,
    overallRating: 93,
    battingRating: 95,
    bowlingRating: 12,
    fieldingRating: 78,
    fitnessRating: 80,
    formRating: 82,
    marketDemand: 95,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'Jasprit Bumrah',
    fullName: 'Jasprit Bumrah',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 133,
    runs: 56,
    battingAverage: 4.31,
    strikeRate: 75.0,
    hundreds: 0,
    fifties: 0,
    wickets: 165,
    bowlingAverage: 23.5,
    economy: 7.39,
    bowlingStrikeRate: 19.1,
    bestBowling: '5/10',
    catches: 22,
    stumpings: 0,
    overallRating: 95,
    battingRating: 8,
    bowlingRating: 98,
    fieldingRating: 72,
    fitnessRating: 88,
    formRating: 94,
    marketDemand: 97,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'Rishabh Pant',
    fullName: 'Rishabh Pant',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 110,
    runs: 3500,
    battingAverage: 35.2,
    strikeRate: 148.7,
    hundreds: 1,
    fifties: 18,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 68,
    stumpings: 23,
    overallRating: 90,
    battingRating: 90,
    bowlingRating: 5,
    fieldingRating: 82,
    fitnessRating: 85,
    formRating: 88,
    marketDemand: 95,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'Hardik Pandya',
    fullName: 'Hardik Pandya',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 120,
    runs: 2200,
    battingAverage: 28.5,
    strikeRate: 153.9,
    hundreds: 0,
    fifties: 9,
    wickets: 85,
    bowlingAverage: 30.2,
    economy: 9.05,
    bowlingStrikeRate: 20.1,
    bestBowling: '3/17',
    catches: 45,
    stumpings: 0,
    overallRating: 90,
    battingRating: 82,
    bowlingRating: 78,
    fieldingRating: 80,
    fitnessRating: 72,
    formRating: 78,
    marketDemand: 92,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'Ravindra Jadeja',
    fullName: 'Ravindra Jadeja',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 35,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 230,
    runs: 2700,
    battingAverage: 26.4,
    strikeRate: 130.2,
    hundreds: 0,
    fifties: 6,
    wickets: 150,
    bowlingAverage: 29.5,
    economy: 7.6,
    bowlingStrikeRate: 23.3,
    bestBowling: '5/16',
    catches: 82,
    stumpings: 0,
    overallRating: 92,
    battingRating: 78,
    bowlingRating: 85,
    fieldingRating: 95,
    fitnessRating: 88,
    formRating: 85,
    marketDemand: 90,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'KL Rahul',
    fullName: 'KL Rahul',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 120,
    runs: 4600,
    battingAverage: 45.5,
    strikeRate: 134.2,
    hundreds: 4,
    fifties: 37,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 48,
    stumpings: 0,
    overallRating: 90,
    battingRating: 93,
    bowlingRating: 5,
    fieldingRating: 75,
    fitnessRating: 82,
    formRating: 80,
    marketDemand: 90,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'Suryakumar Yadav',
    fullName: 'Suryakumar Yadav',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 150,
    runs: 3800,
    battingAverage: 30.8,
    strikeRate: 148.5,
    hundreds: 1,
    fifties: 24,
    wickets: 2,
    bowlingAverage: 42.0,
    economy: 9.5,
    bowlingStrikeRate: 26.5,
    bestBowling: '1/12',
    catches: 55,
    stumpings: 0,
    overallRating: 90,
    battingRating: 92,
    bowlingRating: 10,
    fieldingRating: 80,
    fitnessRating: 85,
    formRating: 88,
    marketDemand: 92,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'Shreyas Iyer',
    fullName: 'Shreyas Iyer',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 115,
    runs: 3200,
    battingAverage: 33.5,
    strikeRate: 127.5,
    hundreds: 1,
    fifties: 22,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 40,
    stumpings: 0,
    overallRating: 88,
    battingRating: 88,
    bowlingRating: 8,
    fieldingRating: 78,
    fitnessRating: 78,
    formRating: 82,
    marketDemand: 85,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'Mohammed Shami',
    fullName: 'Mohammed Shami',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 34,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 110,
    runs: 65,
    battingAverage: 4.6,
    strikeRate: 78.2,
    hundreds: 0,
    fifties: 0,
    wickets: 120,
    bowlingAverage: 25.8,
    economy: 8.55,
    bowlingStrikeRate: 18.1,
    bestBowling: '4/16',
    catches: 18,
    stumpings: 0,
    overallRating: 88,
    battingRating: 10,
    bowlingRating: 92,
    fieldingRating: 60,
    fitnessRating: 72,
    formRating: 78,
    marketDemand: 88,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'R Ashwin',
    fullName: 'Ravichandran Ashwin',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 37,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 190,
    runs: 700,
    battingAverage: 15.5,
    strikeRate: 116.8,
    hundreds: 0,
    fifties: 0,
    wickets: 180,
    bowlingAverage: 26.3,
    economy: 6.98,
    bowlingStrikeRate: 22.6,
    bestBowling: '4/34',
    catches: 40,
    stumpings: 0,
    overallRating: 88,
    battingRating: 35,
    bowlingRating: 90,
    fieldingRating: 65,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 82,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  },
  {
    name: 'Shubman Gill',
    fullName: 'Shubman Gill',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 95,
    runs: 3200,
    battingAverage: 36.8,
    strikeRate: 133.2,
    hundreds: 2,
    fifties: 22,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 38,
    stumpings: 0,
    overallRating: 89,
    battingRating: 91,
    bowlingRating: 8,
    fieldingRating: 78,
    fitnessRating: 88,
    formRating: 90,
    marketDemand: 92,
    basePrice: 200,
    isMarquee: true,
    isCapped: true,
  }
];
