// --- Overseas Squad Players (40) ---
export const part7a = [
  {
    name: 'L Ferguson',
    fullName: 'Lockie Ferguson',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 30,
    runs: 5,
    battingAverage: 1.7,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 35,
    bowlingAverage: 22.5,
    economy: 8.55,
    bowlingStrikeRate: 15.8,
    bestBowling: '4/18',
    catches: 8,
    stumpings: 0,
    overallRating: 78,
    battingRating: 5,
    bowlingRating: 82,
    fieldingRating: 58,
    fitnessRating: 78,
    formRating: 78,
    marketDemand: 75,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'K Jamieson',
    fullName: 'Kyle Jamieson',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 120,
    battingAverage: 12.0,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 30.5,
    economy: 9.25,
    bowlingStrikeRate: 19.8,
    bestBowling: '3/22',
    catches: 5,
    stumpings: 0,
    overallRating: 72,
    battingRating: 30,
    bowlingRating: 72,
    fieldingRating: 55,
    fitnessRating: 72,
    formRating: 65,
    marketDemand: 60,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'D Conway',
    fullName: 'Devon Conway',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 33,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 32,
    runs: 850,
    battingAverage: 30.3,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 6,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 15,
    stumpings: 0,
    overallRating: 76,
    battingRating: 80,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 70,
    basePrice: 125,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'R Ravindra',
    fullName: 'Rachin Ravindra',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 15,
    runs: 350,
    battingAverage: 25.0,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 2,
    wickets: 5,
    bowlingAverage: 38.0,
    economy: 8.2,
    bowlingStrikeRate: 27.8,
    bestBowling: '1/18',
    catches: 8,
    stumpings: 0,
    overallRating: 74,
    battingRating: 72,
    bowlingRating: 45,
    fieldingRating: 68,
    fitnessRating: 80,
    formRating: 75,
    marketDemand: 72,
    basePrice: 125,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'D Mitchell',
    fullName: 'Daryl Mitchell',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 12,
    runs: 250,
    battingAverage: 22.7,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 1,
    wickets: 5,
    bowlingAverage: 38.5,
    economy: 9.0,
    bowlingStrikeRate: 25.7,
    bestBowling: '2/20',
    catches: 5,
    stumpings: 0,
    overallRating: 72,
    battingRating: 68,
    bowlingRating: 42,
    fieldingRating: 65,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 58,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'J Neesham',
    fullName: 'Jimmy Neesham',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 34,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 30,
    runs: 350,
    battingAverage: 15.2,
    strikeRate: 148.5,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 32.5,
    economy: 8.95,
    bowlingStrikeRate: 21.8,
    bestBowling: '3/22',
    catches: 12,
    stumpings: 0,
    overallRating: 72,
    battingRating: 48,
    bowlingRating: 62,
    fieldingRating: 65,
    fitnessRating: 72,
    formRating: 62,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'M Rahman',
    fullName: 'Mustafizur Rahman',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 29,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 55,
    runs: 15,
    battingAverage: 3.0,
    strikeRate: 48.0,
    hundreds: 0,
    fifties: 0,
    wickets: 52,
    bowlingAverage: 26.5,
    economy: 7.85,
    bowlingStrikeRate: 20.2,
    bestBowling: '3/16',
    catches: 10,
    stumpings: 0,
    overallRating: 76,
    battingRating: 5,
    bowlingRating: 80,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 72,
    basePrice: 125,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'S Al Hasan',
    fullName: 'Shakib Al Hasan',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 37,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 75,
    runs: 800,
    battingAverage: 16.5,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 1,
    wickets: 62,
    bowlingAverage: 28.5,
    economy: 7.35,
    bowlingStrikeRate: 23.2,
    bestBowling: '3/18',
    catches: 25,
    stumpings: 0,
    overallRating: 75,
    battingRating: 45,
    bowlingRating: 78,
    fieldingRating: 65,
    fitnessRating: 65,
    formRating: 62,
    marketDemand: 60,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'M Pathirana',
    fullName: 'Matheesha Pathirana',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 22,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 38.5,
    hundreds: 0,
    fifties: 0,
    wickets: 28,
    bowlingAverage: 22.5,
    economy: 7.55,
    bowlingStrikeRate: 17.9,
    bestBowling: '4/28',
    catches: 5,
    stumpings: 0,
    overallRating: 78,
    battingRating: 5,
    bowlingRating: 82,
    fieldingRating: 52,
    fitnessRating: 82,
    formRating: 82,
    marketDemand: 80,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'M Theekshana',
    fullName: 'Maheesh Theekshana',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 25,
    runs: 8,
    battingAverage: 2.7,
    strikeRate: 42.0,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 25.8,
    economy: 7.25,
    bowlingStrikeRate: 21.3,
    bestBowling: '3/18',
    catches: 8,
    stumpings: 0,
    overallRating: 76,
    battingRating: 5,
    bowlingRating: 80,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 72,
    basePrice: 125,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'D Chameera',
    fullName: 'Dushmantha Chameera',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 18,
    runs: 3,
    battingAverage: 1.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 28.5,
    economy: 8.75,
    bowlingStrikeRate: 19.5,
    bestBowling: '3/24',
    catches: 3,
    stumpings: 0,
    overallRating: 70,
    battingRating: 5,
    bowlingRating: 72,
    fieldingRating: 48,
    fitnessRating: 68,
    formRating: 62,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'J Holder',
    fullName: 'Jason Holder',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 28,
    runs: 320,
    battingAverage: 18.8,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 0,
    wickets: 25,
    bowlingAverage: 30.5,
    economy: 8.55,
    bowlingStrikeRate: 21.4,
    bestBowling: '3/18',
    catches: 10,
    stumpings: 0,
    overallRating: 74,
    battingRating: 42,
    bowlingRating: 72,
    fieldingRating: 68,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 62,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'S Hetmyer',
    fullName: 'Shimron Hetmyer',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 28,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 48,
    runs: 950,
    battingAverage: 25.0,
    strikeRate: 158.5,
    hundreds: 0,
    fifties: 3,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 18,
    stumpings: 0,
    overallRating: 75,
    battingRating: 78,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 68,
    formRating: 68,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'N Pooran',
    fullName: 'Nicholas Pooran',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 29,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 65,
    runs: 1200,
    battingAverage: 22.5,
    strikeRate: 152.5,
    hundreds: 0,
    fifties: 5,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 28,
    stumpings: 15,
    overallRating: 76,
    battingRating: 78,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 72,
    basePrice: 125,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'R Powell',
    fullName: 'Rovman Powell',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 28,
    runs: 500,
    battingAverage: 20.8,
    strikeRate: 158.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 12,
    stumpings: 0,
    overallRating: 72,
    battingRating: 75,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 62,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'A Russell',
    fullName: 'Andre Russell',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 36,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 110,
    runs: 2200,
    battingAverage: 28.2,
    strikeRate: 177.8,
    hundreds: 0,
    fifties: 9,
    wickets: 82,
    bowlingAverage: 28.5,
    economy: 9.15,
    bowlingStrikeRate: 18.7,
    bestBowling: '3/19',
    catches: 42,
    stumpings: 0,
    overallRating: 85,
    battingRating: 85,
    bowlingRating: 78,
    fieldingRating: 75,
    fitnessRating: 62,
    formRating: 68,
    marketDemand: 85,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'S Narine',
    fullName: 'Sunil Narine',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 36,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 175,
    runs: 1600,
    battingAverage: 15.5,
    strikeRate: 162.5,
    hundreds: 0,
    fifties: 2,
    wickets: 175,
    bowlingAverage: 24.5,
    economy: 6.55,
    bowlingStrikeRate: 22.5,
    bestBowling: '5/19',
    catches: 48,
    stumpings: 0,
    overallRating: 85,
    battingRating: 55,
    bowlingRating: 92,
    fieldingRating: 72,
    fitnessRating: 72,
    formRating: 78,
    marketDemand: 85,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'C Jordan',
    fullName: 'Chris Jordan',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 35,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 22,
    runs: 45,
    battingAverage: 5.0,
    strikeRate: 95.0,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 32.5,
    economy: 9.15,
    bowlingStrikeRate: 21.3,
    bestBowling: '2/18',
    catches: 8,
    stumpings: 0,
    overallRating: 68,
    battingRating: 12,
    bowlingRating: 70,
    fieldingRating: 58,
    fitnessRating: 68,
    formRating: 58,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'R Topley',
    fullName: 'Reece Topley',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 12,
    runs: 3,
    battingAverage: 1.5,
    strikeRate: 32.0,
    hundreds: 0,
    fifties: 0,
    wickets: 10,
    bowlingAverage: 28.5,
    economy: 8.25,
    bowlingStrikeRate: 20.7,
    bestBowling: '2/15',
    catches: 3,
    stumpings: 0,
    overallRating: 70,
    battingRating: 5,
    bowlingRating: 72,
    fieldingRating: 50,
    fitnessRating: 65,
    formRating: 62,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'J Archer',
    fullName: 'Jofra Archer',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 35,
    runs: 35,
    battingAverage: 5.0,
    strikeRate: 92.0,
    hundreds: 0,
    fifties: 0,
    wickets: 46,
    bowlingAverage: 21.0,
    economy: 7.15,
    bowlingStrikeRate: 17.6,
    bestBowling: '3/15',
    catches: 12,
    stumpings: 0,
    overallRating: 78,
    battingRating: 12,
    bowlingRating: 85,
    fieldingRating: 62,
    fitnessRating: 58,
    formRating: 65,
    marketDemand: 78,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'M Short',
    fullName: 'Matt Short',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 180,
    battingAverage: 22.5,
    strikeRate: 148.5,
    hundreds: 0,
    fifties: 1,
    wickets: 3,
    bowlingAverage: 38.5,
    economy: 8.5,
    bowlingStrikeRate: 27.2,
    bestBowling: '1/15',
    catches: 4,
    stumpings: 0,
    overallRating: 70,
    battingRating: 68,
    bowlingRating: 35,
    fieldingRating: 60,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'J Fraser-McGurk',
    fullName: 'Jake Fraser-McGurk',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 10,
    runs: 280,
    battingAverage: 28.0,
    strikeRate: 225.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 72,
    battingRating: 75,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 78,
    formRating: 80,
    marketDemand: 75,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'W Jacks',
    fullName: 'Will Jacks',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 12,
    runs: 280,
    battingAverage: 23.3,
    strikeRate: 155.5,
    hundreds: 0,
    fifties: 2,
    wickets: 5,
    bowlingAverage: 35.5,
    economy: 8.5,
    bowlingStrikeRate: 25.1,
    bestBowling: '2/18',
    catches: 5,
    stumpings: 0,
    overallRating: 74,
    battingRating: 72,
    bowlingRating: 45,
    fieldingRating: 62,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 72,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'A Markram',
    fullName: 'Aiden Markram',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 22,
    runs: 380,
    battingAverage: 21.1,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 2,
    wickets: 5,
    bowlingAverage: 38.0,
    economy: 8.2,
    bowlingStrikeRate: 27.8,
    bestBowling: '1/12',
    catches: 8,
    stumpings: 0,
    overallRating: 72,
    battingRating: 72,
    bowlingRating: 22,
    fieldingRating: 65,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 62,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'M Jansen',
    fullName: 'Marco Jansen',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 18,
    runs: 120,
    battingAverage: 12.0,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 28.5,
    economy: 8.65,
    bowlingStrikeRate: 19.8,
    bestBowling: '3/20',
    catches: 5,
    stumpings: 0,
    overallRating: 76,
    battingRating: 28,
    bowlingRating: 78,
    fieldingRating: 58,
    fitnessRating: 82,
    formRating: 78,
    marketDemand: 75,
    basePrice: 125,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'G Coetzee',
    fullName: 'Gerald Coetzee',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 10,
    runs: 15,
    battingAverage: 3.8,
    strikeRate: 95.0,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 26.5,
    economy: 9.15,
    bowlingStrikeRate: 17.4,
    bestBowling: '3/25',
    catches: 3,
    stumpings: 0,
    overallRating: 72,
    battingRating: 10,
    bowlingRating: 75,
    fieldingRating: 52,
    fitnessRating: 80,
    formRating: 72,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'L Ngidi',
    fullName: 'Lungi Ngidi',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 20,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 38.5,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 25.8,
    economy: 8.55,
    bowlingStrikeRate: 18.1,
    bestBowling: '3/18',
    catches: 5,
    stumpings: 0,
    overallRating: 74,
    battingRating: 5,
    bowlingRating: 78,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 70,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'D Pretorius',
    fullName: 'Dwaine Pretorius',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 35,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 20,
    runs: 180,
    battingAverage: 15.0,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 28.5,
    economy: 8.35,
    bowlingStrikeRate: 20.4,
    bestBowling: '3/20',
    catches: 8,
    stumpings: 0,
    overallRating: 72,
    battingRating: 38,
    bowlingRating: 68,
    fieldingRating: 60,
    fitnessRating: 68,
    formRating: 62,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'T Stubbs',
    fullName: 'Tristan Stubbs',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 12,
    runs: 220,
    battingAverage: 22.0,
    strikeRate: 162.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 70,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 60,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 65,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'S Raza',
    fullName: 'Sikandar Raza',
    country: 'Zimbabwe',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 38,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 10,
    runs: 120,
    battingAverage: 15.0,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 32.5,
    economy: 7.85,
    bowlingStrikeRate: 24.8,
    bestBowling: '2/18',
    catches: 5,
    stumpings: 0,
    overallRating: 68,
    battingRating: 42,
    bowlingRating: 62,
    fieldingRating: 58,
    fitnessRating: 58,
    formRating: 55,
    marketDemand: 42,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'R Rickelton',
    fullName: 'Ryan Rickelton',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 28,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 5,
    runs: 80,
    battingAverage: 16.0,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 66,
    battingRating: 65,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'O Baartman',
    fullName: 'Ottneil Baartman',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 8,
    runs: 2,
    battingAverage: 1.0,
    strikeRate: 28.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 28.5,
    economy: 8.25,
    bowlingStrikeRate: 20.7,
    bestBowling: '2/22',
    catches: 2,
    stumpings: 0,
    overallRating: 66,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 62,
    marketDemand: 45,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'N Coulter-Nile',
    fullName: 'Nathan Coulter-Nile',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 37,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 42,
    runs: 95,
    battingAverage: 7.3,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 0,
    wickets: 42,
    bowlingAverage: 28.5,
    economy: 8.55,
    bowlingStrikeRate: 20.0,
    bestBowling: '3/20',
    catches: 8,
    stumpings: 0,
    overallRating: 70,
    battingRating: 18,
    bowlingRating: 72,
    fieldingRating: 55,
    fitnessRating: 58,
    formRating: 55,
    marketDemand: 45,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'D Sams',
    fullName: 'Daniel Sams',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 32,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 28,
    runs: 180,
    battingAverage: 12.0,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 0,
    wickets: 25,
    bowlingAverage: 30.5,
    economy: 9.25,
    bowlingStrikeRate: 19.8,
    bestBowling: '3/16',
    catches: 8,
    stumpings: 0,
    overallRating: 70,
    battingRating: 28,
    bowlingRating: 68,
    fieldingRating: 55,
    fitnessRating: 72,
    formRating: 62,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'S Johnson',
    fullName: 'Spencer Johnson',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST',
    matches: 8,
    runs: 3,
    battingAverage: 1.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 10,
    bowlingAverage: 24.5,
    economy: 8.45,
    bowlingStrikeRate: 17.4,
    bestBowling: '3/15',
    catches: 2,
    stumpings: 0,
    overallRating: 72,
    battingRating: 5,
    bowlingRating: 75,
    fieldingRating: 50,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'J Inglis',
    fullName: 'Josh Inglis',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 8,
    runs: 120,
    battingAverage: 15.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 3,
    overallRating: 68,
    battingRating: 65,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'D Shanaka',
    fullName: 'Dasun Shanaka',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 10,
    runs: 120,
    battingAverage: 15.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 35.0,
    economy: 9.2,
    bowlingStrikeRate: 22.8,
    bestBowling: '2/22',
    catches: 5,
    stumpings: 0,
    overallRating: 68,
    battingRating: 42,
    bowlingRating: 52,
    fieldingRating: 60,
    fitnessRating: 72,
    formRating: 58,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'C Asalanka',
    fullName: 'Charith Asalanka',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 15,
    runs: 280,
    battingAverage: 21.5,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 2,
    wickets: 3,
    bowlingAverage: 42.0,
    economy: 8.5,
    bowlingStrikeRate: 29.6,
    bestBowling: '1/12',
    catches: 8,
    stumpings: 0,
    overallRating: 72,
    battingRating: 72,
    bowlingRating: 18,
    fieldingRating: 62,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'A Hosein',
    fullName: 'Akeal Hosein',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 31,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 15,
    runs: 25,
    battingAverage: 5.0,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 25.5,
    economy: 6.85,
    bowlingStrikeRate: 22.4,
    bestBowling: '3/14',
    catches: 5,
    stumpings: 0,
    overallRating: 72,
    battingRating: 10,
    bowlingRating: 75,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 60,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'R Shepherd',
    fullName: 'Romario Shepherd',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 150,
    battingAverage: 15.0,
    strikeRate: 145.0,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 30.5,
    economy: 8.85,
    bowlingStrikeRate: 20.7,
    bestBowling: '3/20',
    catches: 5,
    stumpings: 0,
    overallRating: 70,
    battingRating: 35,
    bowlingRating: 68,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 65,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  }
];
