// Overseas Marquee Players (12)
export const part5 = [
{
  name: 'Pat Cummins',
  fullName: 'Patrick James Cummins',
  country: 'Australia',
  nationality: 'OVERSEAS',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 31,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST',
  matches: 42,
  runs: 220,
  battingAverage: 12.2,
  strikeRate: 145.8,
  hundreds: 0,
  fifties: 0,
  wickets: 45,
  bowlingAverage: 28.2,
  economy: 8.85,
  bowlingStrikeRate: 19.1,
  bestBowling: '4/24',
  catches: 12,
  stumpings: 0,
  overallRating: 88,
  battingRating: 28,
  bowlingRating: 90,
  fieldingRating: 65,
  fitnessRating: 85,
  formRating: 82,
  marketDemand: 88,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Mitchell Starc',
  fullName: 'Mitchell Aaron Starc',
  country: 'Australia',
  nationality: 'OVERSEAS',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 34,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_FAST',
  matches: 25,
  runs: 35,
  battingAverage: 5.0,
  strikeRate: 85.0,
  hundreds: 0,
  fifties: 0,
  wickets: 30,
  bowlingAverage: 25.5,
  economy: 8.95,
  bowlingStrikeRate: 17.1,
  bestBowling: '3/16',
  catches: 5,
  stumpings: 0,
  overallRating: 88,
  battingRating: 10,
  bowlingRating: 92,
  fieldingRating: 58,
  fitnessRating: 78,
  formRating: 80,
  marketDemand: 88,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Rashid Khan',
  fullName: 'Rashid Khan Arman',
  country: 'Afghanistan',
  nationality: 'OVERSEAS',
  role: 'BOWLER',
  subRole: 'SPINNER',
  age: 26,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 110,
  runs: 400,
  battingAverage: 13.8,
  strikeRate: 148.5,
  hundreds: 0,
  fifties: 0,
  wickets: 125,
  bowlingAverage: 20.5,
  economy: 6.55,
  bowlingStrikeRate: 18.8,
  bestBowling: '4/24',
  catches: 35,
  stumpings: 0,
  overallRating: 93,
  battingRating: 35,
  bowlingRating: 96,
  fieldingRating: 75,
  fitnessRating: 90,
  formRating: 92,
  marketDemand: 95,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'David Warner',
  fullName: 'David Andrew Warner',
  country: 'Australia',
  nationality: 'OVERSEAS',
  role: 'BATSMAN',
  subRole: 'OPENER',
  age: 40,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 176,
  runs: 6500,
  battingAverage: 41.2,
  strikeRate: 139.8,
  hundreds: 4,
  fifties: 58,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 82,
  stumpings: 0,
  overallRating: 90,
  battingRating: 95,
  bowlingRating: 5,
  fieldingRating: 78,
  fitnessRating: 72,
  formRating: 72,
  marketDemand: 85,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Jos Buttler',
  fullName: 'Joseph Charles Buttler',
  country: 'England',
  nationality: 'OVERSEAS',
  role: 'WICKET_KEEPER',
  subRole: 'MIDDLE_ORDER',
  age: 33,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 82,
  runs: 3000,
  battingAverage: 38.5,
  strikeRate: 150.2,
  hundreds: 3,
  fifties: 18,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 42,
  stumpings: 15,
  overallRating: 90,
  battingRating: 93,
  bowlingRating: 5,
  fieldingRating: 82,
  fitnessRating: 82,
  formRating: 85,
  marketDemand: 90,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Ben Stokes',
  fullName: 'Benjamin Andrew Stokes',
  country: 'England',
  nationality: 'OVERSEAS',
  role: 'ALL_ROUNDER',
  subRole: 'SEAM_ALL_ROUNDER',
  age: 33,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
  matches: 55,
  runs: 1300,
  battingAverage: 28.5,
  strikeRate: 138.5,
  hundreds: 0,
  fifties: 6,
  wickets: 32,
  bowlingAverage: 32.5,
  economy: 8.85,
  bowlingStrikeRate: 22.0,
  bestBowling: '3/15',
  catches: 22,
  stumpings: 0,
  overallRating: 88,
  battingRating: 80,
  bowlingRating: 75,
  fieldingRating: 78,
  fitnessRating: 72,
  formRating: 75,
  marketDemand: 88,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Kagiso Rabada',
  fullName: 'Kagiso Rabada',
  country: 'South Africa',
  nationality: 'OVERSEAS',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 29,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_FAST',
  matches: 65,
  runs: 32,
  battingAverage: 4.0,
  strikeRate: 62.5,
  hundreds: 0,
  fifties: 0,
  wickets: 82,
  bowlingAverage: 22.5,
  economy: 8.15,
  bowlingStrikeRate: 16.6,
  bestBowling: '4/21',
  catches: 15,
  stumpings: 0,
  overallRating: 90,
  battingRating: 8,
  bowlingRating: 94,
  fieldingRating: 62,
  fitnessRating: 85,
  formRating: 88,
  marketDemand: 92,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Trent Boult',
  fullName: 'Trent Alexander Boult',
  country: 'New Zealand',
  nationality: 'OVERSEAS',
  role: 'BOWLER',
  subRole: 'PACE_BOWLER',
  age: 35,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'LEFT_ARM_FAST',
  matches: 72,
  runs: 18,
  battingAverage: 3.0,
  strikeRate: 55.0,
  hundreds: 0,
  fifties: 0,
  wickets: 78,
  bowlingAverage: 25.8,
  economy: 8.12,
  bowlingStrikeRate: 19.1,
  bestBowling: '4/18',
  catches: 18,
  stumpings: 0,
  overallRating: 87,
  battingRating: 5,
  bowlingRating: 90,
  fieldingRating: 60,
  fitnessRating: 78,
  formRating: 78,
  marketDemand: 85,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Glenn Maxwell',
  fullName: 'Glenn James Maxwell',
  country: 'Australia',
  nationality: 'OVERSEAS',
  role: 'ALL_ROUNDER',
  subRole: 'SEAM_ALL_ROUNDER',
  age: 33,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 120,
  runs: 2600,
  battingAverage: 24.5,
  strikeRate: 155.5,
  hundreds: 0,
  fifties: 13,
  wickets: 25,
  bowlingAverage: 35.2,
  economy: 7.85,
  bowlingStrikeRate: 26.9,
  bestBowling: '3/20',
  catches: 52,
  stumpings: 0,
  overallRating: 87,
  battingRating: 82,
  bowlingRating: 55,
  fieldingRating: 85,
  fitnessRating: 78,
  formRating: 78,
  marketDemand: 85,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Faf du Plessis',
  fullName: 'Francois du Plessis',
  country: 'South Africa',
  nationality: 'OVERSEAS',
  role: 'BATSMAN',
  subRole: 'OPENER',
  age: 40,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_LEGBREAK',
  matches: 120,
  runs: 3800,
  battingAverage: 34.5,
  strikeRate: 132.8,
  hundreds: 0,
  fifties: 28,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 55,
  stumpings: 0,
  overallRating: 85,
  battingRating: 88,
  bowlingRating: 5,
  fieldingRating: 80,
  fitnessRating: 68,
  formRating: 72,
  marketDemand: 78,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Quinton de Kock',
  fullName: 'Quinton de Kock',
  country: 'South Africa',
  nationality: 'OVERSEAS',
  role: 'WICKET_KEEPER',
  subRole: 'OPENER',
  age: 34,
  battingStyle: 'LEFT_HAND_BAT',
  bowlingStyle: 'NONE',
  matches: 90,
  runs: 2800,
  battingAverage: 32.5,
  strikeRate: 138.2,
  hundreds: 2,
  fifties: 18,
  wickets: 0,
  bowlingAverage: 0,
  economy: 0,
  bowlingStrikeRate: 0,
  bestBowling: '0/0',
  catches: 48,
  stumpings: 18,
  overallRating: 87,
  battingRating: 88,
  bowlingRating: 5,
  fieldingRating: 82,
  fitnessRating: 80,
  formRating: 78,
  marketDemand: 85,
  basePrice: 200,
  isMarquee: true,
  isCapped: true,
},
{
  name: 'Kane Williamson',
  fullName: 'Kane Stuart Williamson',
  country: 'New Zealand',
  nationality: 'OVERSEAS',
  role: 'BATSMAN',
  subRole: 'MIDDLE_ORDER',
  age: 34,
  battingStyle: 'RIGHT_HAND_BAT',
  bowlingStyle: 'RIGHT_ARM_OFFBREAK',
  matches: 72,
  runs: 2200,
  battingAverage: 38.5,
  strikeRate: 125.8,
  hundreds: 0,
  fifties: 16,
  wickets: 5,
  bowlingAverage: 42.0,
  economy: 8.5,
  bowlingStrikeRate: 29.6,
  bestBowling: '1/12',
  catches: 32,
  stumpings: 0,
  overallRating: 85,
  battingRating: 88,
  bowlingRating: 15,
  fieldingRating: 72,
  fitnessRating: 72,
  formRating: 70,
  marketDemand: 75,
  basePrice: 200,
  isMarquee: true,
  isCapped: true
}
];
