export const part7c = [
  {
    name: 'Finn Allen',
    fullName: 'Finn Allen',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 43,
    runs: 1100,
    battingAverage: 25.58,
    strikeRate: 158.5,
    hundreds: 1,
    fifties: 5,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 15,
    stumpings: 0,
    overallRating: 75,
    battingRating: 78,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 74,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Chapman',
    fullName: 'Mark Chapman',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 32,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 35,
    runs: 650,
    battingAverage: 22.4,
    strikeRate: 135.2,
    hundreds: 0,
    fifties: 3,
    wickets: 5,
    bowlingAverage: 32.4,
    economy: 8.2,
    bowlingStrikeRate: 24.0,
    bestBowling: '2/15',
    catches: 12,
    stumpings: 0,
    overallRating: 70,
    battingRating: 68,
    bowlingRating: 42,
    fieldingRating: 65,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Seifert',
    fullName: 'Tim Seifert',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 40,
    runs: 900,
    battingAverage: 24.3,
    strikeRate: 138.4,
    hundreds: 0,
    fifties: 5,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 18,
    stumpings: 5,
    overallRating: 72,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 70,
    fitnessRating: 78,
    formRating: 70,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Bracewell',
    fullName: 'Michael Bracewell',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 35,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 16,
    runs: 250,
    battingAverage: 19.2,
    strikeRate: 135.8,
    hundreds: 0,
    fifties: 1,
    wickets: 12,
    bowlingAverage: 28.4,
    economy: 7.85,
    bowlingStrikeRate: 21.6,
    bestBowling: '3/15',
    catches: 8,
    stumpings: 0,
    overallRating: 71,
    battingRating: 55,
    bowlingRating: 65,
    fieldingRating: 62,
    fitnessRating: 72,
    formRating: 68,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Henry',
    fullName: 'Matt Henry',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 34,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 17,
    runs: 35,
    battingAverage: 5.0,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 26.4,
    economy: 8.25,
    bowlingStrikeRate: 19.2,
    bestBowling: '4/24',
    catches: 6,
    stumpings: 0,
    overallRating: 76,
    battingRating: 15,
    bowlingRating: 80,
    fieldingRating: 58,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 72,
    basePrice: 125,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Southee',
    fullName: 'Tim Southee',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 37,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 52,
    runs: 120,
    battingAverage: 8.0,
    strikeRate: 110.5,
    hundreds: 0,
    fifties: 0,
    wickets: 48,
    bowlingAverage: 28.5,
    economy: 8.45,
    bowlingStrikeRate: 20.2,
    bestBowling: '3/16',
    catches: 15,
    stumpings: 0,
    overallRating: 75,
    battingRating: 25,
    bowlingRating: 78,
    fieldingRating: 60,
    fitnessRating: 65,
    formRating: 68,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'H Nicholls',
    fullName: 'Henry Nicholls',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 34,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 10,
    runs: 220,
    battingAverage: 24.4,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 67,
    battingRating: 68,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 42,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Latham',
    fullName: 'Tom Latham',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 34,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 18,
    runs: 350,
    battingAverage: 26.9,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 2,
    overallRating: 71,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 68,
    fitnessRating: 72,
    formRating: 65,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'W Young',
    fullName: 'Will Young',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 12,
    runs: 280,
    battingAverage: 25.45,
    strikeRate: 128.4,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 0,
    overallRating: 69,
    battingRating: 70,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'C Munro',
    fullName: 'Colin Munro',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 39,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 55,
    runs: 1400,
    battingAverage: 28.0,
    strikeRate: 142.5,
    hundreds: 1,
    fifties: 8,
    wickets: 2,
    bowlingAverage: 38.0,
    economy: 9.15,
    bowlingStrikeRate: 25.0,
    bestBowling: '1/12',
    catches: 18,
    stumpings: 0,
    overallRating: 73,
    battingRating: 75,
    bowlingRating: 25,
    fieldingRating: 60,
    fitnessRating: 62,
    formRating: 65,
    marketDemand: 62,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'B Dwarshuis',
    fullName: 'Ben Dwarshuis',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 32,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 3,
    runs: 10,
    battingAverage: 5.0,
    strikeRate: 95.0,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 35.0,
    economy: 9.5,
    bowlingStrikeRate: 22.0,
    bestBowling: '1/18',
    catches: 1,
    stumpings: 0,
    overallRating: 65,
    battingRating: 15,
    bowlingRating: 65,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 58,
    marketDemand: 38,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'R Meredith',
    fullName: 'Riley Meredith',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 13,
    runs: 5,
    battingAverage: 1.67,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 30.5,
    economy: 8.95,
    bowlingStrikeRate: 20.4,
    bestBowling: '2/24',
    catches: 3,
    stumpings: 0,
    overallRating: 68,
    battingRating: 5,
    bowlingRating: 70,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'N Ellis',
    fullName: 'Nathan Ellis',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 15,
    battingAverage: 3.75,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 17,
    bowlingAverage: 24.8,
    economy: 8.12,
    bowlingStrikeRate: 18.3,
    bestBowling: '3/24',
    catches: 5,
    stumpings: 0,
    overallRating: 74,
    battingRating: 8,
    bowlingRating: 78,
    fieldingRating: 62,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'A Agar',
    fullName: 'Ashton Agar',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 32,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 18,
    runs: 150,
    battingAverage: 15.0,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 14,
    bowlingAverage: 28.5,
    economy: 7.45,
    bowlingStrikeRate: 22.9,
    bestBowling: '3/22',
    catches: 8,
    stumpings: 0,
    overallRating: 72,
    battingRating: 45,
    bowlingRating: 72,
    fieldingRating: 70,
    fitnessRating: 75,
    formRating: 65,
    marketDemand: 58,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Sangha',
    fullName: 'Tanveer Sangha',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 5,
    runs: 2,
    battingAverage: 1.0,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 22.5,
    economy: 7.85,
    bowlingStrikeRate: 17.2,
    bestBowling: '2/18',
    catches: 1,
    stumpings: 0,
    overallRating: 68,
    battingRating: 5,
    bowlingRating: 72,
    fieldingRating: 52,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'L Morris',
    fullName: 'Lance Morris',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 4,
    runs: 1,
    battingAverage: 0.5,
    strikeRate: 25.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 28.5,
    economy: 8.65,
    bowlingStrikeRate: 19.8,
    bestBowling: '2/20',
    catches: 1,
    stumpings: 0,
    overallRating: 67,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 48,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 45,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'X Bartlett',
    fullName: 'Xavier Bartlett',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 6,
    runs: 10,
    battingAverage: 5.0,
    strikeRate: 75.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 21.4,
    economy: 7.95,
    bowlingStrikeRate: 16.1,
    bestBowling: '3/19',
    catches: 3,
    stumpings: 0,
    overallRating: 70,
    battingRating: 15,
    bowlingRating: 72,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 62,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'J Philippe',
    fullName: 'Josh Philippe',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 10,
    runs: 180,
    battingAverage: 20.0,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 1,
    overallRating: 68,
    battingRating: 68,
    bowlingRating: 5,
    fieldingRating: 65,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'C Green (AUS)',
    fullName: 'Chris Green',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 5,
    runs: 35,
    battingAverage: 11.67,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 35.0,
    economy: 7.25,
    bowlingStrikeRate: 28.9,
    bestBowling: '1/15',
    catches: 4,
    stumpings: 0,
    overallRating: 67,
    battingRating: 38,
    bowlingRating: 65,
    fieldingRating: 68,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 45,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Henriques',
    fullName: 'Moises Henriques',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 39,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 28,
    runs: 450,
    battingAverage: 22.5,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 2,
    wickets: 10,
    bowlingAverage: 35.5,
    economy: 8.55,
    bowlingStrikeRate: 24.9,
    bestBowling: '2/18',
    catches: 10,
    stumpings: 0,
    overallRating: 70,
    battingRating: 62,
    bowlingRating: 55,
    fieldingRating: 62,
    fitnessRating: 65,
    formRating: 60,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'N Burger',
    fullName: 'Nandre Burger',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST',
    matches: 6,
    runs: 2,
    battingAverage: 1.0,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 7,
    bowlingAverage: 24.5,
    economy: 8.35,
    bowlingStrikeRate: 17.6,
    bestBowling: '3/30',
    catches: 2,
    stumpings: 0,
    overallRating: 72,
    battingRating: 5,
    bowlingRating: 75,
    fieldingRating: 50,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'W Mulder',
    fullName: 'Wiaan Mulder',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 12,
    runs: 160,
    battingAverage: 17.8,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 30.5,
    economy: 8.65,
    bowlingStrikeRate: 21.1,
    bestBowling: '2/24',
    catches: 5,
    stumpings: 0,
    overallRating: 69,
    battingRating: 58,
    bowlingRating: 58,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Breetzke',
    fullName: 'Matthew Breetzke',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 4,
    runs: 85,
    battingAverage: 21.25,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 67,
    battingRating: 68,
    bowlingRating: 5,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 45,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'L Williams',
    fullName: 'Lizaad Williams',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 1,
    battingAverage: 0.5,
    strikeRate: 25.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 32.5,
    economy: 9.15,
    bowlingStrikeRate: 21.3,
    bestBowling: '2/26',
    catches: 2,
    stumpings: 0,
    overallRating: 66,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 42,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'B Fortuin',
    fullName: 'Bjorn Fortuin',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 10,
    runs: 25,
    battingAverage: 6.25,
    strikeRate: 95.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 28.5,
    economy: 7.35,
    bowlingStrikeRate: 23.3,
    bestBowling: '2/18',
    catches: 4,
    stumpings: 0,
    overallRating: 69,
    battingRating: 15,
    bowlingRating: 70,
    fieldingRating: 58,
    fitnessRating: 72,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Shamsi',
    fullName: 'Tabraiz Shamsi',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 36,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_CHINAMAN',
    matches: 25,
    runs: 5,
    battingAverage: 1.0,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 28,
    bowlingAverage: 22.4,
    economy: 7.65,
    bowlingStrikeRate: 17.6,
    bestBowling: '3/20',
    catches: 5,
    stumpings: 0,
    overallRating: 75,
    battingRating: 5,
    bowlingRating: 78,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 68,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'G Linde',
    fullName: 'George Linde',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 34,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 8,
    runs: 110,
    battingAverage: 22.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 24.5,
    economy: 7.45,
    bowlingStrikeRate: 19.7,
    bestBowling: '2/16',
    catches: 4,
    stumpings: 0,
    overallRating: 70,
    battingRating: 55,
    bowlingRating: 65,
    fieldingRating: 60,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'B Hendricks',
    fullName: 'Beuran Hendricks',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 35,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 10,
    runs: 5,
    battingAverage: 1.25,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 32.5,
    economy: 8.95,
    bowlingStrikeRate: 21.8,
    bestBowling: '2/22',
    catches: 3,
    stumpings: 0,
    overallRating: 67,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 48,
    fitnessRating: 68,
    formRating: 60,
    marketDemand: 45,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'R Hendricks',
    fullName: 'Reeza Hendricks',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 36,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 22,
    runs: 550,
    battingAverage: 26.19,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 4,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 0,
    overallRating: 73,
    battingRating: 75,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 72,
    formRating: 70,
    marketDemand: 62,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'K Verreynne',
    fullName: 'Kyle Verreynne',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 5,
    runs: 80,
    battingAverage: 20.0,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 1,
    overallRating: 66,
    battingRating: 62,
    bowlingRating: 5,
    fieldingRating: 65,
    fitnessRating: 75,
    formRating: 58,
    marketDemand: 42,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'S Hope',
    fullName: 'Shai Hope',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 28,
    runs: 650,
    battingAverage: 28.26,
    strikeRate: 125.8,
    hundreds: 0,
    fifties: 4,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 18,
    stumpings: 2,
    overallRating: 74,
    battingRating: 74,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 75,
    formRating: 72,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Forde',
    fullName: 'Matthew Forde',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 45,
    battingAverage: 15.0,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 30.5,
    economy: 8.45,
    bowlingStrikeRate: 21.6,
    bestBowling: '2/24',
    catches: 2,
    stumpings: 0,
    overallRating: 68,
    battingRating: 42,
    bowlingRating: 68,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 65,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'S Joseph',
    fullName: 'Shamar Joseph',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 4,
    runs: 1,
    battingAverage: 0.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 28.5,
    economy: 8.85,
    bowlingStrikeRate: 19.3,
    bestBowling: '2/18',
    catches: 1,
    stumpings: 0,
    overallRating: 68,
    battingRating: 5,
    bowlingRating: 72,
    fieldingRating: 50,
    fitnessRating: 80,
    formRating: 65,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'Y Cariah',
    fullName: 'Yannic Cariah',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 33,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 3,
    runs: 15,
    battingAverage: 7.5,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 30.0,
    economy: 7.85,
    bowlingStrikeRate: 22.9,
    bestBowling: '1/18',
    catches: 1,
    stumpings: 0,
    overallRating: 65,
    battingRating: 25,
    bowlingRating: 65,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 58,
    marketDemand: 38,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'R Chase',
    fullName: 'Roston Chase',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 34,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 15,
    runs: 220,
    battingAverage: 18.33,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 1,
    wickets: 10,
    bowlingAverage: 24.5,
    economy: 7.25,
    bowlingStrikeRate: 20.3,
    bestBowling: '3/12',
    catches: 8,
    stumpings: 0,
    overallRating: 71,
    battingRating: 55,
    bowlingRating: 68,
    fieldingRating: 62,
    fitnessRating: 72,
    formRating: 65,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'G Motie',
    fullName: 'Gudakesh Motie',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 31,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 12,
    runs: 35,
    battingAverage: 8.75,
    strikeRate: 95.0,
    hundreds: 0,
    fifties: 0,
    wickets: 14,
    bowlingAverage: 22.5,
    economy: 6.95,
    bowlingStrikeRate: 19.4,
    bestBowling: '3/15',
    catches: 5,
    stumpings: 0,
    overallRating: 73,
    battingRating: 18,
    bowlingRating: 76,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 70,
    marketDemand: 62,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'K Paul',
    fullName: 'Keemo Paul',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 140,
    battingAverage: 14.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 30.5,
    economy: 9.15,
    bowlingStrikeRate: 20.0,
    bestBowling: '3/24',
    catches: 6,
    stumpings: 0,
    overallRating: 68,
    battingRating: 48,
    bowlingRating: 68,
    fieldingRating: 55,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'O Thomas',
    fullName: 'Oshane Thomas',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 29,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 10,
    runs: 2,
    battingAverage: 0.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 35.0,
    economy: 9.55,
    bowlingStrikeRate: 22.0,
    bestBowling: '2/24',
    catches: 2,
    stumpings: 0,
    overallRating: 66,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 58,
    marketDemand: 42,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'S Cottrell',
    fullName: 'Sheldon Cottrell',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 36,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 18,
    runs: 15,
    battingAverage: 3.75,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 28.5,
    economy: 8.65,
    bowlingStrikeRate: 19.7,
    bestBowling: '3/28',
    catches: 6,
    stumpings: 0,
    overallRating: 70,
    battingRating: 12,
    bowlingRating: 72,
    fieldingRating: 60,
    fitnessRating: 68,
    formRating: 62,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'E Lewis',
    fullName: 'Evin Lewis',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 34,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 35,
    runs: 950,
    battingAverage: 29.69,
    strikeRate: 145.8,
    hundreds: 0,
    fifties: 5,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 12,
    stumpings: 0,
    overallRating: 74,
    battingRating: 76,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 72,
    formRating: 70,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'B Carse',
    fullName: 'Brydon Carse',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 5,
    runs: 12,
    battingAverage: 6.0,
    strikeRate: 95.0,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 26.5,
    economy: 8.55,
    bowlingStrikeRate: 18.6,
    bestBowling: '2/20',
    catches: 2,
    stumpings: 0,
    overallRating: 70,
    battingRating: 18,
    bowlingRating: 72,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 68,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'G Atkinson',
    fullName: 'Gus Atkinson',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 6,
    runs: 5,
    battingAverage: 1.25,
    strikeRate: 55.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 22.5,
    economy: 8.25,
    bowlingStrikeRate: 16.4,
    bestBowling: '3/24',
    catches: 3,
    stumpings: 0,
    overallRating: 73,
    battingRating: 8,
    bowlingRating: 76,
    fieldingRating: 58,
    fitnessRating: 80,
    formRating: 72,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'L Wood',
    fullName: 'Luke Wood',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 8,
    battingAverage: 4.0,
    strikeRate: 75.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 32.5,
    economy: 9.12,
    bowlingStrikeRate: 21.4,
    bestBowling: '1/20',
    catches: 2,
    stumpings: 0,
    overallRating: 67,
    battingRating: 12,
    bowlingRating: 68,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 45,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'D Lawrence',
    fullName: 'Dan Lawrence',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 120,
    battingAverage: 17.14,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 35.0,
    economy: 8.15,
    bowlingStrikeRate: 25.8,
    bestBowling: '1/18',
    catches: 4,
    stumpings: 0,
    overallRating: 69,
    battingRating: 68,
    bowlingRating: 45,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'J Smith (ENG)',
    fullName: 'Jamie Smith',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 4,
    runs: 90,
    battingAverage: 30.0,
    strikeRate: 145.0,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 0,
    overallRating: 71,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 65,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 62,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'R Ahmed (ENG)',
    fullName: 'Rehan Ahmed',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 7,
    runs: 25,
    battingAverage: 6.25,
    strikeRate: 110.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 24.5,
    economy: 7.65,
    bowlingStrikeRate: 19.2,
    bestBowling: '3/22',
    catches: 3,
    stumpings: 0,
    overallRating: 70,
    battingRating: 30,
    bowlingRating: 70,
    fieldingRating: 58,
    fitnessRating: 78,
    formRating: 70,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'O Stone',
    fullName: 'Ollie Stone',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 4,
    runs: 1,
    battingAverage: 0.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 28.5,
    economy: 8.85,
    bowlingStrikeRate: 19.3,
    bestBowling: '2/24',
    catches: 1,
    stumpings: 0,
    overallRating: 68,
    battingRating: 5,
    bowlingRating: 70,
    fieldingRating: 50,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 45,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'J Bethell',
    fullName: 'Jacob Bethell',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 22,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 3,
    runs: 45,
    battingAverage: 22.5,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 30.0,
    economy: 7.95,
    bowlingStrikeRate: 22.6,
    bestBowling: '1/15',
    catches: 2,
    stumpings: 0,
    overallRating: 67,
    battingRating: 65,
    bowlingRating: 58,
    fieldingRating: 65,
    fitnessRating: 80,
    formRating: 72,
    marketDemand: 52,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'J Cox',
    fullName: 'Jordan Cox',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 3,
    runs: 35,
    battingAverage: 17.5,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 66,
    battingRating: 62,
    bowlingRating: 5,
    fieldingRating: 60,
    fitnessRating: 75,
    formRating: 58,
    marketDemand: 42,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'D Mousley',
    fullName: 'Dan Mousley',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 4,
    runs: 55,
    battingAverage: 18.33,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 28.5,
    economy: 8.05,
    bowlingStrikeRate: 21.2,
    bestBowling: '2/18',
    catches: 2,
    stumpings: 0,
    overallRating: 67,
    battingRating: 60,
    bowlingRating: 58,
    fieldingRating: 62,
    fitnessRating: 78,
    formRating: 65,
    marketDemand: 48,
    basePrice: 50,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'K Mendis',
    fullName: 'Kusal Mendis',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'OPENER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 35,
    runs: 850,
    battingAverage: 25.8,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 6,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 15,
    stumpings: 3,
    overallRating: 75,
    battingRating: 76,
    bowlingRating: 5,
    fieldingRating: 68,
    fitnessRating: 75,
    formRating: 72,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'S Samarawickrama',
    fullName: 'Sadeera Samarawickrama',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 15,
    runs: 320,
    battingAverage: 24.6,
    strikeRate: 125.4,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 2,
    overallRating: 71,
    battingRating: 70,
    bowlingRating: 5,
    fieldingRating: 65,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'A Fernando',
    fullName: 'Avishka Fernando',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 18,
    runs: 380,
    battingAverage: 22.35,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 0,
    overallRating: 70,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'L Kumara',
    fullName: 'Lahiru Kumara',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 29,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 20,
    runs: 5,
    battingAverage: 1.0,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 26.8,
    economy: 8.75,
    bowlingStrikeRate: 18.4,
    bestBowling: '3/25',
    catches: 3,
    stumpings: 0,
    overallRating: 72,
    battingRating: 5,
    bowlingRating: 76,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 60,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'K Rajitha',
    fullName: 'Kasun Rajitha',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 10,
    battingAverage: 2.0,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 14,
    bowlingAverage: 29.5,
    economy: 8.45,
    bowlingStrikeRate: 20.9,
    bestBowling: '3/22',
    catches: 4,
    stumpings: 0,
    overallRating: 69,
    battingRating: 8,
    bowlingRating: 70,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'P Madushan',
    fullName: 'Pramod Madushan',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 10,
    runs: 3,
    battingAverage: 0.75,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 11,
    bowlingAverage: 25.8,
    economy: 8.35,
    bowlingStrikeRate: 18.5,
    bestBowling: '2/18',
    catches: 2,
    stumpings: 0,
    overallRating: 69,
    battingRating: 5,
    bowlingRating: 70,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'Ka Mendis',
    fullName: 'Kamindu Mendis',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 12,
    runs: 250,
    battingAverage: 27.78,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 2,
    wickets: 5,
    bowlingAverage: 28.5,
    economy: 7.65,
    bowlingStrikeRate: 22.4,
    bestBowling: '2/15',
    catches: 6,
    stumpings: 0,
    overallRating: 73,
    battingRating: 72,
    bowlingRating: 55,
    fieldingRating: 60,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'C Karunaratne',
    fullName: 'Chamika Karunaratne',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 18,
    runs: 120,
    battingAverage: 12.0,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 0,
    wickets: 11,
    bowlingAverage: 32.5,
    economy: 8.65,
    bowlingStrikeRate: 22.5,
    bestBowling: '2/20',
    catches: 8,
    stumpings: 0,
    overallRating: 68,
    battingRating: 42,
    bowlingRating: 65,
    fieldingRating: 62,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'S Islam',
    fullName: 'Shoriful Islam',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 5,
    battingAverage: 1.25,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 16,
    bowlingAverage: 25.5,
    economy: 8.12,
    bowlingStrikeRate: 18.8,
    bestBowling: '3/28',
    catches: 4,
    stumpings: 0,
    overallRating: 73,
    battingRating: 5,
    bowlingRating: 76,
    fieldingRating: 52,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 62,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'S Sarkar',
    fullName: 'Soumya Sarkar',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 33,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 22,
    runs: 320,
    battingAverage: 16.84,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 1,
    wickets: 8,
    bowlingAverage: 30.5,
    economy: 8.95,
    bowlingStrikeRate: 20.4,
    bestBowling: '2/18',
    catches: 10,
    stumpings: 0,
    overallRating: 68,
    battingRating: 58,
    bowlingRating: 52,
    fieldingRating: 58,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Hridoy',
    fullName: 'Towhid Hridoy',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 12,
    runs: 250,
    battingAverage: 25.0,
    strikeRate: 135.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 71,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 60,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'N Hossain Shanto',
    fullName: 'Najmul Hossain Shanto',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 18,
    runs: 380,
    battingAverage: 23.75,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 0,
    overallRating: 70,
    battingRating: 70,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 75,
    formRating: 65,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'H Mahmud',
    fullName: 'Hasan Mahmud',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 8,
    runs: 2,
    battingAverage: 0.67,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 9,
    bowlingAverage: 26.5,
    economy: 8.45,
    bowlingStrikeRate: 18.8,
    bestBowling: '3/22',
    catches: 2,
    stumpings: 0,
    overallRating: 69,
    battingRating: 5,
    bowlingRating: 70,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Hasan Sakib',
    fullName: 'Tanzim Hasan Sakib',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 6,
    runs: 12,
    battingAverage: 6.0,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 7,
    bowlingAverage: 24.5,
    economy: 8.25,
    bowlingStrikeRate: 17.8,
    bestBowling: '2/18',
    catches: 2,
    stumpings: 0,
    overallRating: 69,
    battingRating: 15,
    bowlingRating: 70,
    fieldingRating: 52,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'A Omarzai',
    fullName: 'Azmatullah Omarzai',
    country: 'Afghanistan',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 280,
    battingAverage: 25.45,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 1,
    wickets: 10,
    bowlingAverage: 30.5,
    economy: 8.45,
    bowlingStrikeRate: 21.6,
    bestBowling: '2/20',
    catches: 5,
    stumpings: 0,
    overallRating: 74,
    battingRating: 70,
    bowlingRating: 68,
    fieldingRating: 58,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 70,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'G Naib',
    fullName: 'Gulbadin Naib',
    country: 'Afghanistan',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 35,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 25,
    runs: 350,
    battingAverage: 20.58,
    strikeRate: 132.8,
    hundreds: 0,
    fifties: 2,
    wickets: 15,
    bowlingAverage: 32.5,
    economy: 8.85,
    bowlingStrikeRate: 22.0,
    bestBowling: '3/24',
    catches: 8,
    stumpings: 0,
    overallRating: 71,
    battingRating: 62,
    bowlingRating: 62,
    fieldingRating: 58,
    fitnessRating: 72,
    formRating: 68,
    marketDemand: 62,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'I Zadran',
    fullName: 'Ibrahim Zadran',
    country: 'Afghanistan',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 18,
    runs: 450,
    battingAverage: 28.12,
    strikeRate: 120.5,
    hundreds: 0,
    fifties: 3,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 0,
    overallRating: 72,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 60,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'R Ngarava',
    fullName: 'Richard Ngarava',
    country: 'Zimbabwe',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 10,
    battingAverage: 2.0,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 22.4,
    economy: 7.85,
    bowlingStrikeRate: 17.1,
    bestBowling: '3/18',
    catches: 4,
    stumpings: 0,
    overallRating: 73,
    battingRating: 8,
    bowlingRating: 75,
    fieldingRating: 52,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 62,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'S Williams (ZIM)',
    fullName: 'Sean Williams',
    country: 'Zimbabwe',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 39,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 18,
    runs: 320,
    battingAverage: 20.0,
    strikeRate: 125.8,
    hundreds: 0,
    fifties: 1,
    wickets: 10,
    bowlingAverage: 28.5,
    economy: 7.45,
    bowlingStrikeRate: 22.9,
    bestBowling: '2/15',
    catches: 8,
    stumpings: 0,
    overallRating: 70,
    battingRating: 65,
    bowlingRating: 62,
    fieldingRating: 60,
    fitnessRating: 60,
    formRating: 58,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'R Burl',
    fullName: 'Ryan Burl',
    country: 'Zimbabwe',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 32,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 15,
    runs: 180,
    battingAverage: 18.0,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 30.5,
    economy: 7.95,
    bowlingStrikeRate: 23.0,
    bestBowling: '2/14',
    catches: 6,
    stumpings: 0,
    overallRating: 68,
    battingRating: 55,
    bowlingRating: 62,
    fieldingRating: 62,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  }
];
