// ── Indian Squad Players (30) ──
export const part3 = [
  {
    name: 'Washington Sundar',
    fullName: 'Washington Sundar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 26,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 55,
    runs: 650,
    battingAverage: 18.5,
    strikeRate: 125.8,
    hundreds: 0,
    fifties: 2,
    wickets: 42,
    bowlingAverage: 28.2,
    economy: 7.45,
    bowlingStrikeRate: 22.8,
    bestBowling: '3/16',
    catches: 18,
    stumpings: 0,
    overallRating: 76,
    battingRating: 55,
    bowlingRating: 75,
    fieldingRating: 68,
    fitnessRating: 82,
    formRating: 75,
    marketDemand: 72,
    basePrice: 125,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Rahul Tripathi',
    fullName: 'Rahul Tripathi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 80,
    runs: 1800,
    battingAverage: 25.2,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 10,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 35,
    stumpings: 0,
    overallRating: 75,
    battingRating: 78,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 72,
    formRating: 70,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Venkatesh Iyer',
    fullName: 'Venkatesh Iyer',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 29,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 45,
    runs: 900,
    battingAverage: 24.5,
    strikeRate: 132.8,
    hundreds: 0,
    fifties: 4,
    wickets: 12,
    bowlingAverage: 35.5,
    economy: 9.2,
    bowlingStrikeRate: 23.2,
    bestBowling: '2/20',
    catches: 15,
    stumpings: 0,
    overallRating: 74,
    battingRating: 68,
    bowlingRating: 55,
    fieldingRating: 65,
    fitnessRating: 78,
    formRating: 68,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Nitish Rana',
    fullName: 'Nitish Rana',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 90,
    runs: 2200,
    battingAverage: 27.5,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 12,
    wickets: 5,
    bowlingAverage: 42.0,
    economy: 8.8,
    bowlingStrikeRate: 28.6,
    bestBowling: '1/12',
    catches: 42,
    stumpings: 0,
    overallRating: 75,
    battingRating: 78,
    bowlingRating: 18,
    fieldingRating: 70,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Abhishek Sharma',
    fullName: 'Abhishek Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 40,
    runs: 900,
    battingAverage: 25.0,
    strikeRate: 158.5,
    hundreds: 1,
    fifties: 4,
    wickets: 15,
    bowlingAverage: 32.5,
    economy: 8.2,
    bowlingStrikeRate: 23.8,
    bestBowling: '2/18',
    catches: 12,
    stumpings: 0,
    overallRating: 76,
    battingRating: 72,
    bowlingRating: 58,
    fieldingRating: 68,
    fitnessRating: 82,
    formRating: 80,
    marketDemand: 75,
    basePrice: 125,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Shahbaz Ahmed',
    fullName: 'Shahbaz Ahmed',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 29,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 35,
    runs: 450,
    battingAverage: 18.0,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 1,
    wickets: 22,
    bowlingAverage: 30.5,
    economy: 8.15,
    bowlingStrikeRate: 22.5,
    bestBowling: '2/14',
    catches: 10,
    stumpings: 0,
    overallRating: 70,
    battingRating: 52,
    bowlingRating: 65,
    fieldingRating: 62,
    fitnessRating: 75,
    formRating: 65,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Avesh Khan',
    fullName: 'Avesh Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 55,
    runs: 28,
    battingAverage: 4.0,
    strikeRate: 62.5,
    hundreds: 0,
    fifties: 0,
    wickets: 62,
    bowlingAverage: 26.8,
    economy: 8.52,
    bowlingStrikeRate: 18.9,
    bestBowling: '4/18',
    catches: 8,
    stumpings: 0,
    overallRating: 74,
    battingRating: 8,
    bowlingRating: 78,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 70,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Mukesh Choudhary',
    fullName: 'Mukesh Choudhary',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 20,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 32.5,
    economy: 9.12,
    bowlingStrikeRate: 21.4,
    bestBowling: '3/22',
    catches: 4,
    stumpings: 0,
    overallRating: 68,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Umran Malik',
    fullName: 'Umran Malik',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 28,
    runs: 8,
    battingAverage: 2.0,
    strikeRate: 50.0,
    hundreds: 0,
    fifties: 0,
    wickets: 25,
    bowlingAverage: 30.2,
    economy: 9.38,
    bowlingStrikeRate: 19.3,
    bestBowling: '5/25',
    catches: 5,
    stumpings: 0,
    overallRating: 72,
    battingRating: 5,
    bowlingRating: 75,
    fieldingRating: 50,
    fitnessRating: 82,
    formRating: 68,
    marketDemand: 70,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Prasidh Krishna',
    fullName: 'Prasidh Krishna',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 35,
    runs: 12,
    battingAverage: 3.0,
    strikeRate: 55.0,
    hundreds: 0,
    fifties: 0,
    wickets: 32,
    bowlingAverage: 28.5,
    economy: 8.85,
    bowlingStrikeRate: 19.3,
    bestBowling: '4/30',
    catches: 6,
    stumpings: 0,
    overallRating: 74,
    battingRating: 6,
    bowlingRating: 78,
    fieldingRating: 55,
    fitnessRating: 80,
    formRating: 72,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Tushar Deshpande',
    fullName: 'Tushar Deshpande',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 40,
    runs: 15,
    battingAverage: 3.0,
    strikeRate: 58.0,
    hundreds: 0,
    fifties: 0,
    wickets: 42,
    bowlingAverage: 28.2,
    economy: 9.15,
    bowlingStrikeRate: 18.5,
    bestBowling: '3/20',
    catches: 8,
    stumpings: 0,
    overallRating: 72,
    battingRating: 5,
    bowlingRating: 75,
    fieldingRating: 52,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 62,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Krunal Pandya',
    fullName: 'Krunal Pandya',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 33,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 85,
    runs: 1350,
    battingAverage: 22.5,
    strikeRate: 128.2,
    hundreds: 0,
    fifties: 4,
    wickets: 55,
    bowlingAverage: 30.8,
    economy: 7.52,
    bowlingStrikeRate: 24.6,
    bestBowling: '3/19',
    catches: 28,
    stumpings: 0,
    overallRating: 75,
    battingRating: 65,
    bowlingRating: 72,
    fieldingRating: 68,
    fitnessRating: 72,
    formRating: 68,
    marketDemand: 62,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Ravi Bishnoi',
    fullName: 'Ravi Bishnoi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 45,
    runs: 12,
    battingAverage: 3.0,
    strikeRate: 52.0,
    hundreds: 0,
    fifties: 0,
    wickets: 48,
    bowlingAverage: 24.5,
    economy: 7.45,
    bowlingStrikeRate: 19.7,
    bestBowling: '4/16',
    catches: 15,
    stumpings: 0,
    overallRating: 76,
    battingRating: 5,
    bowlingRating: 82,
    fieldingRating: 65,
    fitnessRating: 82,
    formRating: 78,
    marketDemand: 75,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Manish Pandey',
    fullName: 'Manish Pandey',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 35,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 160,
    runs: 3500,
    battingAverage: 29.2,
    strikeRate: 121.8,
    hundreds: 1,
    fifties: 18,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 62,
    stumpings: 0,
    overallRating: 72,
    battingRating: 75,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 65,
    formRating: 58,
    marketDemand: 50,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Sai Sudharsan',
    fullName: 'Sai Sudharsan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 30,
    runs: 900,
    battingAverage: 32.5,
    strikeRate: 135.8,
    hundreds: 0,
    fifties: 6,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 12,
    stumpings: 0,
    overallRating: 76,
    battingRating: 80,
    bowlingRating: 5,
    fieldingRating: 68,
    fitnessRating: 82,
    formRating: 82,
    marketDemand: 78,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Rajat Patidar',
    fullName: 'Rajat Patidar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 25,
    runs: 650,
    battingAverage: 28.2,
    strikeRate: 148.5,
    hundreds: 1,
    fifties: 3,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 0,
    overallRating: 74,
    battingRating: 78,
    bowlingRating: 8,
    fieldingRating: 65,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 70,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Rahul Tewatia',
    fullName: 'Rahul Tewatia',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 31,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 85,
    runs: 1200,
    battingAverage: 22.8,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 3,
    wickets: 28,
    bowlingAverage: 35.2,
    economy: 8.55,
    bowlingStrikeRate: 24.7,
    bestBowling: '3/25',
    catches: 32,
    stumpings: 0,
    overallRating: 73,
    battingRating: 68,
    bowlingRating: 55,
    fieldingRating: 68,
    fitnessRating: 72,
    formRating: 68,
    marketDemand: 60,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Shahrukh Khan',
    fullName: 'Shahrukh Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 30,
    runs: 550,
    battingAverage: 22.0,
    strikeRate: 148.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 0,
    overallRating: 70,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 60,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 62,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Dhruv Jurel',
    fullName: 'Dhruv Jurel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 20,
    runs: 380,
    battingAverage: 25.3,
    strikeRate: 138.2,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 15,
    stumpings: 5,
    overallRating: 72,
    battingRating: 70,
    bowlingRating: 5,
    fieldingRating: 75,
    fitnessRating: 82,
    formRating: 75,
    marketDemand: 72,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Jitesh Sharma',
    fullName: 'Jitesh Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 25,
    runs: 420,
    battingAverage: 21.0,
    strikeRate: 155.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 18,
    stumpings: 8,
    overallRating: 70,
    battingRating: 68,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 72,
    formRating: 68,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Prithvi Shaw',
    fullName: 'Prithvi Shaw',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 65,
    runs: 1600,
    battingAverage: 25.5,
    strikeRate: 148.2,
    hundreds: 1,
    fifties: 8,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 22,
    stumpings: 0,
    overallRating: 72,
    battingRating: 78,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 62,
    formRating: 55,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Sarfaraz Khan',
    fullName: 'Sarfaraz Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 30,
    runs: 500,
    battingAverage: 22.8,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 12,
    stumpings: 0,
    overallRating: 70,
    battingRating: 72,
    bowlingRating: 8,
    fieldingRating: 62,
    fitnessRating: 72,
    formRating: 72,
    marketDemand: 62,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Mayank Agarwal',
    fullName: 'Mayank Agarwal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 110,
    runs: 2700,
    battingAverage: 25.0,
    strikeRate: 132.8,
    hundreds: 1,
    fifties: 15,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 42,
    stumpings: 0,
    overallRating: 73,
    battingRating: 76,
    bowlingRating: 5,
    fieldingRating: 68,
    fitnessRating: 68,
    formRating: 60,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Wriddhiman Saha',
    fullName: 'Wriddhiman Saha',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 39,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 170,
    runs: 2500,
    battingAverage: 22.5,
    strikeRate: 126.5,
    hundreds: 0,
    fifties: 8,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 85,
    stumpings: 22,
    overallRating: 70,
    battingRating: 65,
    bowlingRating: 5,
    fieldingRating: 82,
    fitnessRating: 60,
    formRating: 55,
    marketDemand: 45,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Dinesh Karthik',
    fullName: 'Dinesh Karthik',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'FINISHER',
    age: 39,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 250,
    runs: 4800,
    battingAverage: 26.5,
    strikeRate: 132.8,
    hundreds: 0,
    fifties: 22,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 120,
    stumpings: 35,
    overallRating: 74,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 85,
    fitnessRating: 62,
    formRating: 58,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Robin Uthappa',
    fullName: 'Robin Uthappa',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 39,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 205,
    runs: 4900,
    battingAverage: 27.2,
    strikeRate: 130.5,
    hundreds: 1,
    fifties: 25,
    wickets: 5,
    bowlingAverage: 45.0,
    economy: 9.5,
    bowlingStrikeRate: 28.4,
    bestBowling: '1/15',
    catches: 72,
    stumpings: 0,
    overallRating: 70,
    battingRating: 72,
    bowlingRating: 10,
    fieldingRating: 68,
    fitnessRating: 55,
    formRating: 50,
    marketDemand: 40,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Ambati Rayudu',
    fullName: 'Ambati Rayudu',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 38,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 188,
    runs: 4200,
    battingAverage: 28.5,
    strikeRate: 127.8,
    hundreds: 1,
    fifties: 22,
    wickets: 8,
    bowlingAverage: 38.5,
    economy: 8.2,
    bowlingStrikeRate: 28.2,
    bestBowling: '1/10',
    catches: 65,
    stumpings: 0,
    overallRating: 72,
    battingRating: 75,
    bowlingRating: 15,
    fieldingRating: 68,
    fitnessRating: 58,
    formRating: 52,
    marketDemand: 42,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Riyan Parag',
    fullName: 'Riyan Parag',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 55,
    runs: 800,
    battingAverage: 20.5,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 2,
    wickets: 8,
    bowlingAverage: 38.5,
    economy: 8.85,
    bowlingStrikeRate: 26.1,
    bestBowling: '2/18',
    catches: 22,
    stumpings: 0,
    overallRating: 74,
    battingRating: 68,
    bowlingRating: 42,
    fieldingRating: 72,
    fitnessRating: 80,
    formRating: 75,
    marketDemand: 72,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Deepak Hooda',
    fullName: 'Deepak Hooda',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 75,
    runs: 1200,
    battingAverage: 22.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 5,
    wickets: 18,
    bowlingAverage: 35.8,
    economy: 8.45,
    bowlingStrikeRate: 25.4,
    bestBowling: '2/15',
    catches: 25,
    stumpings: 0,
    overallRating: 72,
    battingRating: 68,
    bowlingRating: 48,
    fieldingRating: 65,
    fitnessRating: 72,
    formRating: 65,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Khaleel Ahmed',
    fullName: 'Khaleel Ahmed',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 40,
    runs: 8,
    battingAverage: 2.0,
    strikeRate: 40.0,
    hundreds: 0,
    fifties: 0,
    wickets: 38,
    bowlingAverage: 29.5,
    economy: 8.92,
    bowlingStrikeRate: 19.8,
    bestBowling: '3/21',
    catches: 6,
    stumpings: 0,
    overallRating: 74,
    battingRating: 5,
    bowlingRating: 76,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 65,
    basePrice: 100,
    isMarquee: false,
    isCapped: true,
  }
];
