export const part7b = [
  {
    name: 'S Rutherford',
    fullName: 'Sherfane Rutherford',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 26,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 15,
    runs: 250,
    battingAverage: 20.8,
    strikeRate: 162.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 70,
    battingRating: 72,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 68,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'O Smith',
    fullName: 'Odean Smith',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 12,
    runs: 85,
    battingAverage: 10.6,
    strikeRate: 155.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 35.5,
    economy: 10.2,
    bowlingStrikeRate: 20.9,
    bestBowling: '2/22',
    catches: 3,
    stumpings: 0,
    overallRating: 65,
    battingRating: 28,
    bowlingRating: 62,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 55,
    marketDemand: 42,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'O McCoy',
    fullName: 'Obed McCoy',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST',
    matches: 10,
    runs: 3,
    battingAverage: 1.5,
    strikeRate: 32.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 30.5,
    economy: 9.55,
    bowlingStrikeRate: 19.2,
    bestBowling: '3/18',
    catches: 2,
    stumpings: 0,
    overallRating: 66,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 45,
    fitnessRating: 68,
    formRating: 58,
    marketDemand: 45,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Curran',
    fullName: 'Tom Curran',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 25,
    runs: 85,
    battingAverage: 8.5,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 30.5,
    economy: 8.95,
    bowlingStrikeRate: 20.4,
    bestBowling: '3/22',
    catches: 8,
    stumpings: 0,
    overallRating: 68,
    battingRating: 18,
    bowlingRating: 70,
    fieldingRating: 58,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 50,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Ali',
    fullName: 'Moeen Ali',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 37,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 60,
    runs: 900,
    battingAverage: 18.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 2,
    wickets: 32,
    bowlingAverage: 28.5,
    economy: 7.35,
    bowlingStrikeRate: 23.2,
    bestBowling: '3/15',
    catches: 22,
    stumpings: 0,
    overallRating: 75,
    battingRating: 55,
    bowlingRating: 72,
    fieldingRating: 68,
    fitnessRating: 65,
    formRating: 62,
    marketDemand: 60,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'H Brook',
    fullName: 'Harry Brook',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 12,
    runs: 280,
    battingAverage: 25.5,
    strikeRate: 148.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 74,
    battingRating: 78,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 80,
    formRating: 78,
    marketDemand: 72,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'A Rashid',
    fullName: 'Adil Rashid',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 36,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 15,
    runs: 12,
    battingAverage: 3.0,
    strikeRate: 55.0,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 28.5,
    economy: 7.65,
    bowlingStrikeRate: 22.3,
    bestBowling: '2/18',
    catches: 5,
    stumpings: 0,
    overallRating: 72,
    battingRating: 8,
    bowlingRating: 78,
    fieldingRating: 55,
    fitnessRating: 68,
    formRating: 62,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Wade',
    fullName: 'Matthew Wade',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'FINISHER',
    age: 36,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 15,
    runs: 200,
    battingAverage: 16.7,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 5,
    overallRating: 68,
    battingRating: 62,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 62,
    formRating: 55,
    marketDemand: 42,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'G Phillips',
    fullName: 'Glenn Phillips',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 120,
    battingAverage: 15.0,
    strikeRate: 148.5,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 38.5,
    economy: 8.5,
    bowlingStrikeRate: 27.2,
    bestBowling: '1/12',
    catches: 4,
    stumpings: 0,
    overallRating: 70,
    battingRating: 62,
    bowlingRating: 38,
    fieldingRating: 65,
    fitnessRating: 78,
    formRating: 68,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'S Abbott',
    fullName: 'Sean Abbott',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 30,
    battingAverage: 10.0,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 32.0,
    economy: 8.85,
    bowlingStrikeRate: 21.7,
    bestBowling: '2/18',
    catches: 2,
    stumpings: 0,
    overallRating: 66,
    battingRating: 22,
    bowlingRating: 65,
    fieldingRating: 55,
    fitnessRating: 72,
    formRating: 58,
    marketDemand: 42,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'I Sodhi',
    fullName: 'Ish Sodhi',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 22,
    runs: 12,
    battingAverage: 3.0,
    strikeRate: 52.0,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 28.5,
    economy: 8.15,
    bowlingStrikeRate: 21.0,
    bestBowling: '3/18',
    catches: 5,
    stumpings: 0,
    overallRating: 68,
    battingRating: 5,
    bowlingRating: 72,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'F Farooqi',
    fullName: 'Fazalhaq Farooqi',
    country: 'Afghanistan',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 20,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 22.5,
    economy: 7.85,
    bowlingStrikeRate: 17.2,
    bestBowling: '3/14',
    catches: 5,
    stumpings: 0,
    overallRating: 76,
    battingRating: 5,
    bowlingRating: 80,
    fieldingRating: 52,
    fitnessRating: 82,
    formRating: 80,
    marketDemand: 78,
    basePrice: 125,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'N Ahmad',
    fullName: 'Noor Ahmad',
    country: 'Afghanistan',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 19,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_CHINAMAN',
    matches: 12,
    runs: 3,
    battingAverage: 1.5,
    strikeRate: 32.0,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 24.5,
    economy: 7.15,
    bowlingStrikeRate: 20.6,
    bestBowling: '3/16',
    catches: 4,
    stumpings: 0,
    overallRating: 72,
    battingRating: 5,
    bowlingRating: 75,
    fieldingRating: 52,
    fitnessRating: 80,
    formRating: 78,
    marketDemand: 72,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'Naveen-ul-Haq',
    fullName: 'Naveen-ul-Haq',
    country: 'Afghanistan',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 22,
    runs: 8,
    battingAverage: 2.7,
    strikeRate: 42.0,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 25.5,
    economy: 8.25,
    bowlingStrikeRate: 18.5,
    bestBowling: '3/20',
    catches: 5,
    stumpings: 0,
    overallRating: 74,
    battingRating: 5,
    bowlingRating: 78,
    fieldingRating: 55,
    fitnessRating: 80,
    formRating: 72,
    marketDemand: 68,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Nabi',
    fullName: 'Mohammad Nabi',
    country: 'Afghanistan',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 40,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 45,
    runs: 350,
    battingAverage: 12.5,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 0,
    wickets: 25,
    bowlingAverage: 30.5,
    economy: 7.55,
    bowlingStrikeRate: 24.2,
    bestBowling: '3/18',
    catches: 15,
    stumpings: 0,
    overallRating: 70,
    battingRating: 35,
    bowlingRating: 68,
    fieldingRating: 62,
    fitnessRating: 58,
    formRating: 55,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'R Gurbaz',
    fullName: 'Rahmanullah Gurbaz',
    country: 'Afghanistan',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'OPENER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 15,
    runs: 350,
    battingAverage: 25.0,
    strikeRate: 158.5,
    hundreds: 0,
    fifties: 3,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 5,
    overallRating: 74,
    battingRating: 78,
    bowlingRating: 5,
    fieldingRating: 68,
    fitnessRating: 80,
    formRating: 78,
    marketDemand: 72,
    basePrice: 100,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'J Little',
    fullName: 'Josh Little',
    country: 'Ireland',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST',
    matches: 5,
    runs: 2,
    battingAverage: 1.0,
    strikeRate: 28.5,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 28.5,
    economy: 8.55,
    bowlingStrikeRate: 20.0,
    bestBowling: '2/15',
    catches: 1,
    stumpings: 0,
    overallRating: 66,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 48,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 50,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Adair',
    fullName: 'Mark Adair',
    country: 'Ireland',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 3,
    runs: 25,
    battingAverage: 8.3,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 32.0,
    economy: 8.85,
    bowlingStrikeRate: 21.7,
    bestBowling: '2/20',
    catches: 1,
    stumpings: 0,
    overallRating: 62,
    battingRating: 22,
    bowlingRating: 58,
    fieldingRating: 50,
    fitnessRating: 72,
    formRating: 55,
    marketDemand: 38,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'D Wellalage',
    fullName: 'Dunith Wellalage',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 21,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 10,
    runs: 80,
    battingAverage: 10.0,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 28.5,
    economy: 7.55,
    bowlingStrikeRate: 22.6,
    bestBowling: '2/18',
    catches: 4,
    stumpings: 0,
    overallRating: 70,
    battingRating: 28,
    bowlingRating: 68,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 62,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'D Madushanka',
    fullName: 'Dilshan Madushanka',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 8,
    runs: 2,
    battingAverage: 1.0,
    strikeRate: 25.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 28.5,
    economy: 8.55,
    bowlingStrikeRate: 20.0,
    bestBowling: '2/20',
    catches: 2,
    stumpings: 0,
    overallRating: 66,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 45,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'N Thushara',
    fullName: 'Nuwan Thushara',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 1,
    battingAverage: 0.5,
    strikeRate: 20.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 30.5,
    economy: 8.85,
    bowlingStrikeRate: 20.7,
    bestBowling: '2/22',
    catches: 1,
    stumpings: 0,
    overallRating: 64,
    battingRating: 5,
    bowlingRating: 65,
    fieldingRating: 42,
    fitnessRating: 72,
    formRating: 58,
    marketDemand: 42,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Hasan',
    fullName: 'Tanzid Hasan',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 22,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 5,
    runs: 60,
    battingAverage: 12.0,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 2,
    stumpings: 0,
    overallRating: 62,
    battingRating: 60,
    bowlingRating: 5,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 58,
    marketDemand: 38,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Ahmed',
    fullName: 'Taskin Ahmed',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 12,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 38.5,
    hundreds: 0,
    fifties: 0,
    wickets: 10,
    bowlingAverage: 30.5,
    economy: 8.85,
    bowlingStrikeRate: 20.7,
    bestBowling: '2/18',
    catches: 3,
    stumpings: 0,
    overallRating: 68,
    battingRating: 5,
    bowlingRating: 70,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 52,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Hasan Miraz',
    fullName: 'Mehidy Hasan Miraz',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 45,
    battingAverage: 9.0,
    strikeRate: 112.5,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 32.5,
    economy: 7.65,
    bowlingStrikeRate: 25.5,
    bestBowling: '2/18',
    catches: 3,
    stumpings: 0,
    overallRating: 66,
    battingRating: 25,
    bowlingRating: 62,
    fieldingRating: 55,
    fitnessRating: 72,
    formRating: 58,
    marketDemand: 42,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'B Muzarabani',
    fullName: 'Blessing Muzarabani',
    country: 'Zimbabwe',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 5,
    runs: 2,
    battingAverage: 1.0,
    strikeRate: 28.5,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 28.5,
    economy: 8.55,
    bowlingStrikeRate: 20.0,
    bestBowling: '2/18',
    catches: 1,
    stumpings: 0,
    overallRating: 66,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 48,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'B King',
    fullName: 'Brandon King',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 8,
    runs: 120,
    battingAverage: 15.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 66,
    battingRating: 65,
    bowlingRating: 5,
    fieldingRating: 55,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 45,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'K Mayers',
    fullName: 'Kyle Mayers',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 32,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 60,
    battingAverage: 12.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 35.0,
    economy: 9.2,
    bowlingStrikeRate: 22.8,
    bestBowling: '1/15',
    catches: 2,
    stumpings: 0,
    overallRating: 64,
    battingRating: 38,
    bowlingRating: 52,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 55,
    marketDemand: 38,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'F Allen',
    fullName: 'Fabian Allen',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 12,
    runs: 80,
    battingAverage: 10.0,
    strikeRate: 148.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 30.5,
    economy: 7.85,
    bowlingStrikeRate: 23.3,
    bestBowling: '2/14',
    catches: 5,
    stumpings: 0,
    overallRating: 66,
    battingRating: 25,
    bowlingRating: 62,
    fieldingRating: 58,
    fitnessRating: 72,
    formRating: 55,
    marketDemand: 42,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'D Ferreira',
    fullName: 'Donovan Ferreira',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 5,
    runs: 45,
    battingAverage: 9.0,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 42.0,
    economy: 9.5,
    bowlingStrikeRate: 26.5,
    bestBowling: '1/12',
    catches: 2,
    stumpings: 0,
    overallRating: 62,
    battingRating: 35,
    bowlingRating: 35,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 58,
    marketDemand: 38,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'D Wiese',
    fullName: 'David Wiese',
    country: 'Namibia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 39,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 45,
    battingAverage: 11.3,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 32.0,
    economy: 8.85,
    bowlingStrikeRate: 21.7,
    bestBowling: '2/18',
    catches: 2,
    stumpings: 0,
    overallRating: 62,
    battingRating: 30,
    bowlingRating: 58,
    fieldingRating: 52,
    fitnessRating: 58,
    formRating: 48,
    marketDemand: 32,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'B McDermott',
    fullName: 'Ben McDermott',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 5,
    runs: 55,
    battingAverage: 11.0,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 64,
    battingRating: 62,
    bowlingRating: 5,
    fieldingRating: 55,
    fitnessRating: 72,
    formRating: 55,
    marketDemand: 38,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'A Hardie',
    fullName: 'Aaron Hardie',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 55,
    battingAverage: 11.0,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 30.0,
    economy: 8.55,
    bowlingStrikeRate: 21.1,
    bestBowling: '2/18',
    catches: 2,
    stumpings: 0,
    overallRating: 66,
    battingRating: 35,
    bowlingRating: 58,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'L Das',
    fullName: 'Litton Das',
    country: 'Bangladesh',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 8,
    runs: 95,
    battingAverage: 11.9,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 3,
    overallRating: 64,
    battingRating: 55,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 68,
    formRating: 55,
    marketDemand: 38,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Potts',
    fullName: 'Matthew Potts',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 3,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 55.0,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 32.0,
    economy: 8.85,
    bowlingStrikeRate: 21.7,
    bestBowling: '2/22',
    catches: 1,
    stumpings: 0,
    overallRating: 64,
    battingRating: 8,
    bowlingRating: 65,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 58,
    marketDemand: 42,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'T Hartley',
    fullName: 'Tom Hartley',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 5,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 42.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 28.5,
    economy: 7.55,
    bowlingStrikeRate: 22.6,
    bestBowling: '2/15',
    catches: 2,
    stumpings: 0,
    overallRating: 66,
    battingRating: 5,
    bowlingRating: 68,
    fieldingRating: 48,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 48,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'M Santner',
    fullName: 'Mitchell Santner',
    country: 'New Zealand',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 32,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 25,
    runs: 150,
    battingAverage: 10.7,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 30.5,
    economy: 7.55,
    bowlingStrikeRate: 24.2,
    bestBowling: '3/18',
    catches: 10,
    stumpings: 0,
    overallRating: 72,
    battingRating: 28,
    bowlingRating: 72,
    fieldingRating: 62,
    fitnessRating: 72,
    formRating: 65,
    marketDemand: 55,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'Mujeeb Ur Rahman',
    fullName: 'Mujeeb Ur Rahman',
    country: 'Afghanistan',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 18,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 26.5,
    economy: 7.25,
    bowlingStrikeRate: 21.9,
    bestBowling: '3/16',
    catches: 5,
    stumpings: 0,
    overallRating: 70,
    battingRating: 5,
    bowlingRating: 75,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 62,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'R Gleeson',
    fullName: 'Richard Gleeson',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 37,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 3,
    runs: 2,
    battingAverage: 1.0,
    strikeRate: 28.5,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 30.0,
    economy: 8.55,
    bowlingStrikeRate: 21.1,
    bestBowling: '2/22',
    catches: 1,
    stumpings: 0,
    overallRating: 62,
    battingRating: 5,
    bowlingRating: 62,
    fieldingRating: 42,
    fitnessRating: 58,
    formRating: 48,
    marketDemand: 32,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'J Richardson',
    fullName: 'Jhye Richardson',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 10,
    runs: 8,
    battingAverage: 2.7,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 10,
    bowlingAverage: 26.5,
    economy: 8.35,
    bowlingStrikeRate: 19.0,
    bestBowling: '3/18',
    catches: 3,
    stumpings: 0,
    overallRating: 72,
    battingRating: 5,
    bowlingRating: 75,
    fieldingRating: 52,
    fitnessRating: 68,
    formRating: 65,
    marketDemand: 58,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  },
  {
    name: 'S Magala',
    fullName: 'Sisanda Magala',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 3,
    battingAverage: 1.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 32.0,
    economy: 9.25,
    bowlingStrikeRate: 20.8,
    bestBowling: '2/22',
    catches: 2,
    stumpings: 0,
    overallRating: 64,
    battingRating: 5,
    bowlingRating: 65,
    fieldingRating: 45,
    fitnessRating: 68,
    formRating: 55,
    marketDemand: 38,
    basePrice: 75,
    isMarquee: false,
    isCapped: true
  }
];
