export const part6 = [
  {
    name: 'Wanindu Hasaranga',
    fullName: 'Pinnaduwage Wanindu Hasaranga de Silva',
    country: 'Sri Lanka',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 30,
    runs: 200,
    battingAverage: 12.5,
    strikeRate: 132.5,
    hundreds: 0,
    fifties: 0,
    wickets: 35,
    bowlingAverage: 22.8,
    economy: 7.55,
    bowlingStrikeRate: 18.1,
    bestBowling: '4/20',
    catches: 12,
    stumpings: 0,
    overallRating: 84,
    battingRating: 30,
    bowlingRating: 88,
    fieldingRating: 68,
    fitnessRating: 82,
    formRating: 82,
    marketDemand: 82,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Marcus Stoinis',
    fullName: 'Marcus Peter Stoinis',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 35,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 55,
    runs: 1100,
    battingAverage: 25.5,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 5,
    wickets: 22,
    bowlingAverage: 32.5,
    economy: 8.85,
    bowlingStrikeRate: 22.0,
    bestBowling: '2/16',
    catches: 20,
    stumpings: 0,
    overallRating: 80,
    battingRating: 72,
    bowlingRating: 62,
    fieldingRating: 75,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 72,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'David Miller',
    fullName: 'David Andrew Miller',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 35,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 110,
    runs: 2600,
    battingAverage: 32.5,
    strikeRate: 140.2,
    hundreds: 0,
    fifties: 15,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 42,
    stumpings: 0,
    overallRating: 82,
    battingRating: 85,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 72,
    formRating: 78,
    marketDemand: 78,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Liam Livingstone',
    fullName: 'Liam Stephen Livingstone',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 35,
    runs: 700,
    battingAverage: 22.5,
    strikeRate: 155.8,
    hundreds: 0,
    fifties: 3,
    wickets: 10,
    bowlingAverage: 35.5,
    economy: 8.92,
    bowlingStrikeRate: 23.8,
    bestBowling: '2/18',
    catches: 15,
    stumpings: 0,
    overallRating: 80,
    battingRating: 78,
    bowlingRating: 48,
    fieldingRating: 70,
    fitnessRating: 75,
    formRating: 72,
    marketDemand: 75,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Sam Curran',
    fullName: 'Samuel Matthew Curran',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 26,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 48,
    runs: 450,
    battingAverage: 15.0,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 1,
    wickets: 42,
    bowlingAverage: 28.5,
    economy: 8.52,
    bowlingStrikeRate: 20.1,
    bestBowling: '4/11',
    catches: 18,
    stumpings: 0,
    overallRating: 83,
    battingRating: 42,
    bowlingRating: 82,
    fieldingRating: 72,
    fitnessRating: 82,
    formRating: 80,
    marketDemand: 82,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Cameron Green',
    fullName: 'Cameron David Green',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 18,
    runs: 380,
    battingAverage: 25.3,
    strikeRate: 148.5,
    hundreds: 0,
    fifties: 2,
    wickets: 12,
    bowlingAverage: 30.5,
    economy: 8.65,
    bowlingStrikeRate: 21.2,
    bestBowling: '2/20',
    catches: 8,
    stumpings: 0,
    overallRating: 82,
    battingRating: 75,
    bowlingRating: 72,
    fieldingRating: 70,
    fitnessRating: 82,
    formRating: 78,
    marketDemand: 82,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Travis Head',
    fullName: 'Travis Michael Head',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 25,
    runs: 600,
    battingAverage: 28.5,
    strikeRate: 158.5,
    hundreds: 0,
    fifties: 4,
    wickets: 3,
    bowlingAverage: 42.0,
    economy: 9.2,
    bowlingStrikeRate: 27.4,
    bestBowling: '1/15',
    catches: 10,
    stumpings: 0,
    overallRating: 82,
    battingRating: 85,
    bowlingRating: 15,
    fieldingRating: 68,
    fitnessRating: 82,
    formRating: 82,
    marketDemand: 80,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Mitchell Marsh',
    fullName: 'Mitchell Ross Marsh',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 35,
    runs: 650,
    battingAverage: 22.5,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 3,
    wickets: 15,
    bowlingAverage: 35.5,
    economy: 9.15,
    bowlingStrikeRate: 23.3,
    bestBowling: '2/18',
    catches: 12,
    stumpings: 0,
    overallRating: 80,
    battingRating: 72,
    bowlingRating: 58,
    fieldingRating: 68,
    fitnessRating: 72,
    formRating: 72,
    marketDemand: 72,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Heinrich Klaasen',
    fullName: 'Heinrich Ernst Klaasen',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 30,
    runs: 850,
    battingAverage: 32.7,
    strikeRate: 168.5,
    hundreds: 0,
    fifties: 5,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 18,
    stumpings: 8,
    overallRating: 85,
    battingRating: 88,
    bowlingRating: 5,
    fieldingRating: 78,
    fitnessRating: 82,
    formRating: 88,
    marketDemand: 88,
    basePrice: 200,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Tim David',
    fullName: 'Timothy Howard David',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 25,
    runs: 500,
    battingAverage: 28.5,
    strikeRate: 168.2,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 0,
    overallRating: 80,
    battingRating: 82,
    bowlingRating: 5,
    fieldingRating: 65,
    fitnessRating: 78,
    formRating: 78,
    marketDemand: 78,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Phil Salt',
    fullName: 'Philip Dean Salt',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'WICKET_KEEPER',
    subRole: 'OPENER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 20,
    runs: 520,
    battingAverage: 30.5,
    strikeRate: 162.5,
    hundreds: 0,
    fifties: 4,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 12,
    stumpings: 5,
    overallRating: 82,
    battingRating: 85,
    bowlingRating: 5,
    fieldingRating: 75,
    fitnessRating: 82,
    formRating: 85,
    marketDemand: 82,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Mark Wood',
    fullName: 'Mark Andrew Wood',
    country: 'England',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 34,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 18,
    runs: 8,
    battingAverage: 2.7,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 25.5,
    economy: 8.55,
    bowlingStrikeRate: 17.9,
    bestBowling: '3/20',
    catches: 5,
    stumpings: 0,
    overallRating: 80,
    battingRating: 5,
    bowlingRating: 85,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 75,
    marketDemand: 78,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Anrich Nortje',
    fullName: 'Anrich Nortje',
    country: 'South Africa',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 35,
    runs: 8,
    battingAverage: 2.7,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 35,
    bowlingAverage: 24.5,
    economy: 8.22,
    bowlingStrikeRate: 17.9,
    bestBowling: '4/10',
    catches: 8,
    stumpings: 0,
    overallRating: 83,
    battingRating: 5,
    bowlingRating: 88,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 78,
    marketDemand: 80,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Alzarri Joseph',
    fullName: 'Alzarri Shaheim Joseph',
    country: 'West Indies',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 42,
    runs: 28,
    battingAverage: 4.0,
    strikeRate: 55.0,
    hundreds: 0,
    fifties: 0,
    wickets: 48,
    bowlingAverage: 25.8,
    economy: 8.45,
    bowlingStrikeRate: 18.3,
    bestBowling: '6/12',
    catches: 8,
    stumpings: 0,
    overallRating: 82,
    battingRating: 8,
    bowlingRating: 86,
    fieldingRating: 55,
    fitnessRating: 82,
    formRating: 80,
    marketDemand: 78,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Josh Hazlewood',
    fullName: 'Joshua Reginald Hazlewood',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 18,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 26.5,
    economy: 7.85,
    bowlingStrikeRate: 20.3,
    bestBowling: '3/14',
    catches: 5,
    stumpings: 0,
    overallRating: 80,
    battingRating: 5,
    bowlingRating: 85,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 72,
    marketDemand: 75,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Adam Zampa',
    fullName: 'Adam Jeffrey Zampa',
    country: 'Australia',
    nationality: 'OVERSEAS',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 22,
    runs: 12,
    battingAverage: 3.0,
    strikeRate: 48.0,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 24.8,
    economy: 7.35,
    bowlingStrikeRate: 20.2,
    bestBowling: '3/18',
    catches: 8,
    stumpings: 0,
    overallRating: 80,
    battingRating: 5,
    bowlingRating: 85,
    fieldingRating: 58,
    fitnessRating: 78,
    formRating: 75,
    marketDemand: 72,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  }
];
