export const part4c = [
  // 1. Swastik Chikara
  {
    name: 'Swastik Chikara',
    fullName: 'Swastik Chikara',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 8,
    runs: 140,
    battingAverage: 17.5,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 52,
    battingRating: 55,
    bowlingRating: 5,
    fieldingRating: 48,
    fitnessRating: 75,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 2. Sameer Rizvi
  {
    name: 'Sameer Rizvi',
    fullName: 'Sameer Rizvi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 20,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 12,
    runs: 160,
    battingAverage: 20.0,
    strikeRate: 140.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 58,
    battingRating: 62,
    bowlingRating: 5,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 58,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 3. Kumar Kushagra
  {
    name: 'Kumar Kushagra',
    fullName: 'Kumar Kushagra',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 19,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 9,
    runs: 110,
    battingAverage: 15.7,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 1,
    overallRating: 54,
    battingRating: 53,
    bowlingRating: 5,
    fieldingRating: 60,
    fitnessRating: 74,
    formRating: 52,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 4. Abishek Porel
  {
    name: 'Abishek Porel',
    fullName: 'Abishek Porel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 22,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 15,
    runs: 280,
    battingAverage: 23.3,
    strikeRate: 142.8,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 3,
    overallRating: 62,
    battingRating: 64,
    bowlingRating: 5,
    fieldingRating: 65,
    fitnessRating: 80,
    formRating: 62,
    marketDemand: 52,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 5. Ramandeep Singh
  {
    name: 'Ramandeep Singh',
    fullName: 'Ramandeep Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 18,
    runs: 220,
    battingAverage: 20.0,
    strikeRate: 155.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 25.5,
    economy: 8.8,
    bowlingStrikeRate: 17.5,
    bestBowling: '3/20',
    catches: 12,
    stumpings: 0,
    overallRating: 63,
    battingRating: 58,
    bowlingRating: 56,
    fieldingRating: 68,
    fitnessRating: 82,
    formRating: 63,
    marketDemand: 50,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 6. Rasikh Salam
  {
    name: 'Rasikh Salam',
    fullName: 'Rasikh Salam Dar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 10,
    runs: 12,
    battingAverage: 3.0,
    strikeRate: 80.0,
    hundreds: 0,
    fifties: 0,
    wickets: 11,
    bowlingAverage: 26.4,
    economy: 8.95,
    bowlingStrikeRate: 17.7,
    bestBowling: '3/34',
    catches: 3,
    stumpings: 0,
    overallRating: 56,
    battingRating: 10,
    bowlingRating: 59,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 55,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 7. Angkrish Raghuvanshi
  {
    name: 'Angkrish Raghuvanshi',
    fullName: 'Angkrish Raghuvanshi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 19,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 10,
    runs: 163,
    battingAverage: 20.4,
    strikeRate: 135.8,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 55,
    battingRating: 58,
    bowlingRating: 5,
    fieldingRating: 52,
    fitnessRating: 76,
    formRating: 54,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 8. Nehal Wadhera
  {
    name: 'Nehal Wadhera',
    fullName: 'Nehal Wadhera',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 16,
    runs: 280,
    battingAverage: 25.5,
    strikeRate: 138.2,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 0,
    overallRating: 60,
    battingRating: 64,
    bowlingRating: 5,
    fieldingRating: 56,
    fitnessRating: 78,
    formRating: 60,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 9. Naman Dhir
  {
    name: 'Naman Dhir',
    fullName: 'Naman Dhir',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 120,
    battingAverage: 15.0,
    strikeRate: 145.0,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 32.5,
    economy: 8.5,
    bowlingStrikeRate: 23.0,
    bestBowling: '1/15',
    catches: 4,
    stumpings: 0,
    overallRating: 54,
    battingRating: 52,
    bowlingRating: 46,
    fieldingRating: 54,
    fitnessRating: 75,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 10. Ashutosh Sharma
  {
    name: 'Ashutosh Sharma',
    fullName: 'Ashutosh Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 10,
    runs: 190,
    battingAverage: 21.1,
    strikeRate: 165.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 61,
    battingRating: 65,
    bowlingRating: 5,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 61,
    marketDemand: 50,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 11. Shashank Singh
  {
    name: 'Shashank Singh',
    fullName: 'Shashank Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 22,
    runs: 380,
    battingAverage: 25.3,
    strikeRate: 148.5,
    hundreds: 0,
    fifties: 2,
    wickets: 2,
    bowlingAverage: 35.0,
    economy: 8.8,
    bowlingStrikeRate: 24.0,
    bestBowling: '1/12',
    catches: 8,
    stumpings: 0,
    overallRating: 62,
    battingRating: 65,
    bowlingRating: 25,
    fieldingRating: 55,
    fitnessRating: 72,
    formRating: 62,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 12. Tanush Kotian
  {
    name: 'Tanush Kotian',
    fullName: 'Tanush Kotian',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 65,
    battingAverage: 13.0,
    strikeRate: 115.0,
    hundreds: 0,
    fifties: 0,
    wickets: 7,
    bowlingAverage: 28.5,
    economy: 7.65,
    bowlingStrikeRate: 22.4,
    bestBowling: '2/18',
    catches: 3,
    stumpings: 0,
    overallRating: 55,
    battingRating: 45,
    bowlingRating: 54,
    fieldingRating: 52,
    fitnessRating: 74,
    formRating: 54,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 13. Shams Mulani
  {
    name: 'Shams Mulani',
    fullName: 'Shams Zakir Mulani',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 10,
    runs: 90,
    battingAverage: 15.0,
    strikeRate: 118.0,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 30.5,
    economy: 8.05,
    bowlingStrikeRate: 22.8,
    bestBowling: '2/22',
    catches: 4,
    stumpings: 0,
    overallRating: 56,
    battingRating: 48,
    bowlingRating: 55,
    fieldingRating: 54,
    fitnessRating: 75,
    formRating: 55,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 14. Vaibhav Arora
  {
    name: 'Vaibhav Arora',
    fullName: 'Vaibhav Arora',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 8,
    battingAverage: 2.0,
    strikeRate: 40.0,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 26.1,
    economy: 8.55,
    bowlingStrikeRate: 18.3,
    bestBowling: '3/28',
    catches: 3,
    stumpings: 0,
    overallRating: 60,
    battingRating: 10,
    bowlingRating: 62,
    fieldingRating: 48,
    fitnessRating: 74,
    formRating: 58,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 15. Akash Madhwal
  {
    name: 'Akash Madhwal',
    fullName: 'Akash Madhwal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM_FAST',
    matches: 16,
    runs: 5,
    battingAverage: 1.5,
    strikeRate: 40.0,
    hundreds: 0,
    fifties: 0,
    wickets: 20,
    bowlingAverage: 23.4,
    economy: 8.5,
    bowlingStrikeRate: 16.5,
    bestBowling: '5/5',
    catches: 4,
    stumpings: 0,
    overallRating: 62,
    battingRating: 8,
    bowlingRating: 65,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 50,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 16. Suyash Sharma
  {
    name: 'Suyash Sharma',
    fullName: 'Suyash Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 12,
    runs: 4,
    battingAverage: 2.0,
    strikeRate: 60.0,
    hundreds: 0,
    fifties: 0,
    wickets: 10,
    bowlingAverage: 32.1,
    economy: 8.2,
    bowlingStrikeRate: 23.5,
    bestBowling: '3/30',
    catches: 2,
    stumpings: 0,
    overallRating: 60,
    battingRating: 8,
    bowlingRating: 63,
    fieldingRating: 50,
    fitnessRating: 78,
    formRating: 58,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 17. Hrithik Shokeen
  {
    name: 'Hrithik Shokeen',
    fullName: 'Hrithik Shokeen',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 15,
    runs: 90,
    battingAverage: 12.8,
    strikeRate: 116.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 35.5,
    economy: 8.15,
    bowlingStrikeRate: 26.1,
    bestBowling: '2/13',
    catches: 6,
    stumpings: 0,
    overallRating: 56,
    battingRating: 46,
    bowlingRating: 55,
    fieldingRating: 54,
    fitnessRating: 76,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 18. Vidwath Kaverappa
  {
    name: 'Vidwath Kaverappa',
    fullName: 'Vidwath Kaverappa',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 4,
    runs: 5,
    battingAverage: 2.5,
    strikeRate: 50.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 28.4,
    economy: 8.5,
    bowlingStrikeRate: 20.0,
    bestBowling: '2/24',
    catches: 2,
    stumpings: 0,
    overallRating: 58,
    battingRating: 8,
    bowlingRating: 60,
    fieldingRating: 50,
    fitnessRating: 78,
    formRating: 56,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 19. Rajvardhan Hangargekar
  {
    name: 'Rajvardhan Hangargekar',
    fullName: 'Rajvardhan Hangargekar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 6,
    runs: 18,
    battingAverage: 6.0,
    strikeRate: 130.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 30.2,
    economy: 9.3,
    bowlingStrikeRate: 19.5,
    bestBowling: '3/36',
    catches: 2,
    stumpings: 0,
    overallRating: 55,
    battingRating: 25,
    bowlingRating: 57,
    fieldingRating: 50,
    fitnessRating: 80,
    formRating: 52,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 20. Nishant Sindhu
  {
    name: 'Nishant Sindhu',
    fullName: 'Nishant Sindhu',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 20,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 4,
    runs: 35,
    battingAverage: 11.7,
    strikeRate: 112.5,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 30.0,
    economy: 7.85,
    bowlingStrikeRate: 22.9,
    bestBowling: '1/15',
    catches: 1,
    stumpings: 0,
    overallRating: 54,
    battingRating: 46,
    bowlingRating: 51,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 21. Sanvir Singh
  {
    name: 'Sanvir Singh',
    fullName: 'Sanvir Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 6,
    runs: 55,
    battingAverage: 13.8,
    strikeRate: 130.5,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 48.0,
    economy: 9.15,
    bowlingStrikeRate: 31.4,
    bestBowling: '1/25',
    catches: 2,
    stumpings: 0,
    overallRating: 53,
    battingRating: 50,
    bowlingRating: 46,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 50,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 22. Musheer Khan
  {
    name: 'Musheer Khan',
    fullName: 'Musheer Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 19,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 5,
    runs: 95,
    battingAverage: 23.75,
    strikeRate: 120.0,
    hundreds: 0,
    fifties: 1,
    wickets: 4,
    bowlingAverage: 28.5,
    economy: 7.25,
    bowlingStrikeRate: 23.5,
    bestBowling: '2/18',
    catches: 2,
    stumpings: 0,
    overallRating: 56,
    battingRating: 55,
    bowlingRating: 52,
    fieldingRating: 52,
    fitnessRating: 78,
    formRating: 55,
    marketDemand: 42,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 23. Arshin Kulkarni
  {
    name: 'Arshin Kulkarni',
    fullName: 'Arshin Kulkarni',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 19,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM_FAST',
    matches: 4,
    runs: 60,
    battingAverage: 15.0,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 35.0,
    economy: 8.9,
    bowlingStrikeRate: 23.6,
    bestBowling: '1/18',
    catches: 1,
    stumpings: 0,
    overallRating: 54,
    battingRating: 52,
    bowlingRating: 48,
    fieldingRating: 50,
    fitnessRating: 78,
    formRating: 52,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 24. Priyansh Arya
  {
    name: 'Priyansh Arya',
    fullName: 'Priyansh Arya',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 22,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 5,
    runs: 85,
    battingAverage: 17.0,
    strikeRate: 135.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 2,
    stumpings: 0,
    overallRating: 51,
    battingRating: 54,
    bowlingRating: 5,
    fieldingRating: 48,
    fitnessRating: 75,
    formRating: 50,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 25. Saurav Chauhan
  {
    name: 'Saurav Chauhan',
    fullName: 'Saurav Chauhan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 4,
    runs: 35,
    battingAverage: 8.75,
    strikeRate: 138.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 1,
    stumpings: 0,
    overallRating: 50,
    battingRating: 52,
    bowlingRating: 5,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 48,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 26. Sakib Hussain
  {
    name: 'Sakib Hussain',
    fullName: 'Sakib Hussain',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 2,
    runs: 2,
    battingAverage: 2.0,
    strikeRate: 50.0,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 45.0,
    economy: 9.5,
    bowlingStrikeRate: 28.4,
    bestBowling: '1/22',
    catches: 0,
    stumpings: 0,
    overallRating: 48,
    battingRating: 5,
    bowlingRating: 50,
    fieldingRating: 42,
    fitnessRating: 74,
    formRating: 46,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 27. Prince Choudhary
  {
    name: 'Prince Choudhary',
    fullName: 'Prince Choudhary',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 1,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 9.0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 0,
    stumpings: 0,
    overallRating: 46,
    battingRating: 5,
    bowlingRating: 48,
    fieldingRating: 45,
    fitnessRating: 70,
    formRating: 44,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 28. Jhathavedh Subramanyan
  {
    name: 'Jhathavedh Subramanyan',
    fullName: 'Jhathavedh Subramanyan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 2,
    runs: 4,
    battingAverage: 2.0,
    strikeRate: 60.0,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 35.0,
    economy: 7.8,
    bowlingStrikeRate: 27.0,
    bestBowling: '1/18',
    catches: 0,
    stumpings: 0,
    overallRating: 48,
    battingRating: 5,
    bowlingRating: 50,
    fieldingRating: 46,
    fitnessRating: 70,
    formRating: 46,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 29. Gurnoor Brar
  {
    name: 'Gurnoor Brar',
    fullName: 'Gurnoor Singh Brar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 3,
    runs: 8,
    battingAverage: 4.0,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 38.5,
    economy: 9.2,
    bowlingStrikeRate: 25.0,
    bestBowling: '1/28',
    catches: 1,
    stumpings: 0,
    overallRating: 50,
    battingRating: 12,
    bowlingRating: 52,
    fieldingRating: 45,
    fitnessRating: 73,
    formRating: 48,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 30. Vyas Sen
  {
    name: 'Vyas Sen',
    fullName: 'Vyas Sen',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 2,
    runs: 2,
    battingAverage: 1.0,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 42.0,
    economy: 8.85,
    bowlingStrikeRate: 28.5,
    bestBowling: '1/22',
    catches: 1,
    stumpings: 0,
    overallRating: 47,
    battingRating: 5,
    bowlingRating: 49,
    fieldingRating: 42,
    fitnessRating: 72,
    formRating: 45,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 31. Robin Minz
  {
    name: 'Robin Minz',
    fullName: 'Robin Minz',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 21,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 4,
    runs: 38,
    battingAverage: 9.5,
    strikeRate: 118.8,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 2,
    stumpings: 0,
    overallRating: 50,
    battingRating: 48,
    bowlingRating: 5,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 48,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 32. Ricky Bhui
  {
    name: 'Ricky Bhui',
    fullName: 'Ricky Bhui',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 5,
    runs: 72,
    battingAverage: 14.4,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 2,
    stumpings: 0,
    overallRating: 52,
    battingRating: 55,
    bowlingRating: 5,
    fieldingRating: 50,
    fitnessRating: 70,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 33. Shaik Rasheed
  {
    name: 'Shaik Rasheed',
    fullName: 'Shaik Rasheed',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 2,
    runs: 15,
    battingAverage: 7.5,
    strikeRate: 98.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 1,
    stumpings: 0,
    overallRating: 51,
    battingRating: 54,
    bowlingRating: 10,
    fieldingRating: 54,
    fitnessRating: 74,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 34. Dinesh Bana
  {
    name: 'Dinesh Bana',
    fullName: 'Dinesh Bana',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 3,
    runs: 42,
    battingAverage: 14.0,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 2,
    stumpings: 1,
    overallRating: 50,
    battingRating: 48,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 48,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 35. Manav Suthar
  {
    name: 'Manav Suthar',
    fullName: 'Manav Suthar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 21,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 4,
    runs: 15,
    battingAverage: 7.5,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 28.0,
    economy: 7.2,
    bowlingStrikeRate: 23.3,
    bestBowling: '2/18',
    catches: 1,
    stumpings: 0,
    overallRating: 56,
    battingRating: 18,
    bowlingRating: 58,
    fieldingRating: 52,
    fitnessRating: 76,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 36. Shubhang Hegde
  {
    name: 'Shubhang Hegde',
    fullName: 'Shubhang Hegde',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 5,
    runs: 45,
    battingAverage: 9.0,
    strikeRate: 110.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 30.5,
    economy: 7.95,
    bowlingStrikeRate: 23.0,
    bestBowling: '2/20',
    catches: 2,
    stumpings: 0,
    overallRating: 52,
    battingRating: 44,
    bowlingRating: 53,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 37. Yudhvir Singh Charak
  {
    name: 'Yudhvir Singh Charak',
    fullName: 'Yudhvir Singh Charak',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 8,
    runs: 32,
    battingAverage: 8.0,
    strikeRate: 135.0,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 33.2,
    economy: 8.9,
    bowlingStrikeRate: 22.4,
    bestBowling: '2/27',
    catches: 2,
    stumpings: 0,
    overallRating: 55,
    battingRating: 44,
    bowlingRating: 54,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 53,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 38. Mukesh Choudhary
  {
    name: 'Mukesh Choudhary',
    fullName: 'Mukesh Choudhary',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 13,
    runs: 6,
    battingAverage: 3.0,
    strikeRate: 45.0,
    hundreds: 0,
    fifties: 0,
    wickets: 16,
    bowlingAverage: 26.5,
    economy: 8.8,
    bowlingStrikeRate: 18.0,
    bestBowling: '4/46',
    catches: 3,
    stumpings: 0,
    overallRating: 61,
    battingRating: 5,
    bowlingRating: 63,
    fieldingRating: 50,
    fitnessRating: 74,
    formRating: 58,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 39. Simarjeet Singh
  {
    name: 'Simarjeet Singh',
    fullName: 'Simarjeet Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 12,
    runs: 15,
    battingAverage: 5.0,
    strikeRate: 75.0,
    hundreds: 0,
    fifties: 0,
    wickets: 10,
    bowlingAverage: 30.5,
    economy: 8.65,
    bowlingStrikeRate: 21.1,
    bestBowling: '2/21',
    catches: 3,
    stumpings: 0,
    overallRating: 58,
    battingRating: 10,
    bowlingRating: 60,
    fieldingRating: 50,
    fitnessRating: 76,
    formRating: 56,
    marketDemand: 40,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 40. Raj Angad Bawa
  {
    name: 'Raj Angad Bawa',
    fullName: 'Raj Angad Bawa',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 4,
    runs: 45,
    battingAverage: 11.25,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 32.5,
    economy: 8.95,
    bowlingStrikeRate: 21.8,
    bestBowling: '2/25',
    catches: 1,
    stumpings: 0,
    overallRating: 53,
    battingRating: 50,
    bowlingRating: 50,
    fieldingRating: 50,
    fitnessRating: 78,
    formRating: 51,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 41. Aneeshwar Gautam
  {
    name: 'Aneeshwar Gautam',
    fullName: 'Aneeshwar Gautam',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 2,
    runs: 15,
    battingAverage: 7.5,
    strikeRate: 105.0,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 38.0,
    economy: 8.2,
    bowlingStrikeRate: 27.8,
    bestBowling: '1/18',
    catches: 1,
    stumpings: 0,
    overallRating: 48,
    battingRating: 44,
    bowlingRating: 46,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 46,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 42. Kaushal Tambe
  {
    name: 'Kaushal Tambe',
    fullName: 'Kaushal Tambe',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 3,
    runs: 35,
    battingAverage: 11.67,
    strikeRate: 112.5,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 45.0,
    economy: 8.5,
    bowlingStrikeRate: 31.8,
    bestBowling: '1/22',
    catches: 2,
    stumpings: 0,
    overallRating: 48,
    battingRating: 45,
    bowlingRating: 45,
    fieldingRating: 48,
    fitnessRating: 73,
    formRating: 46,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 43. Vicky Ostwal
  {
    name: 'Vicky Ostwal',
    fullName: 'Vicky Ostwal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 4,
    runs: 8,
    battingAverage: 4.0,
    strikeRate: 75.0,
    hundreds: 0,
    fifties: 0,
    wickets: 3,
    bowlingAverage: 32.5,
    economy: 7.6,
    bowlingStrikeRate: 25.6,
    bestBowling: '2/20',
    catches: 1,
    stumpings: 0,
    overallRating: 52,
    battingRating: 10,
    bowlingRating: 54,
    fieldingRating: 48,
    fitnessRating: 74,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 44. Prashant Solanki
  {
    name: 'Prashant Solanki',
    fullName: 'Prashant Solanki',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 3,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 25.0,
    economy: 6.8,
    bowlingStrikeRate: 22.0,
    bestBowling: '2/20',
    catches: 1,
    stumpings: 0,
    overallRating: 52,
    battingRating: 5,
    bowlingRating: 54,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 50,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 45. Raghav Goyal
  {
    name: 'Raghav Goyal',
    fullName: 'Raghav Goyal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_WRIST_SPIN',
    matches: 2,
    runs: 2,
    battingAverage: 2.0,
    strikeRate: 66.7,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 38.0,
    economy: 8.5,
    bowlingStrikeRate: 26.8,
    bestBowling: '1/22',
    catches: 0,
    stumpings: 0,
    overallRating: 48,
    battingRating: 5,
    bowlingRating: 50,
    fieldingRating: 45,
    fitnessRating: 70,
    formRating: 46,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 46. Himanshu Sharma
  {
    name: 'Himanshu Sharma',
    fullName: 'Himanshu Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 2,
    runs: 0,
    battingAverage: 0,
    strikeRate: 0,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 48.0,
    economy: 9.6,
    bowlingStrikeRate: 30.0,
    bestBowling: '1/28',
    catches: 0,
    stumpings: 0,
    overallRating: 48,
    battingRating: 5,
    bowlingRating: 50,
    fieldingRating: 45,
    fitnessRating: 70,
    formRating: 46,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 47. Atharva Taide
  {
    name: 'Atharva Taide',
    fullName: 'Atharva Taide',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 12,
    runs: 230,
    battingAverage: 20.9,
    strikeRate: 127.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 56,
    battingRating: 59,
    bowlingRating: 5,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 54,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 48. Sumit Kumar
  {
    name: 'Sumit Kumar',
    fullName: 'Sumit Kumar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 8,
    runs: 48,
    battingAverage: 9.6,
    strikeRate: 112.5,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 35.5,
    economy: 9.1,
    bowlingStrikeRate: 23.4,
    bestBowling: '1/20',
    catches: 3,
    stumpings: 0,
    overallRating: 52,
    battingRating: 44,
    bowlingRating: 51,
    fieldingRating: 50,
    fitnessRating: 72,
    formRating: 48,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 49. Anukul Roy
  {
    name: 'Anukul Roy',
    fullName: 'Anukul Sudhakar Roy',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 12,
    runs: 95,
    battingAverage: 13.5,
    strikeRate: 120.0,
    hundreds: 0,
    fifties: 0,
    wickets: 7,
    bowlingAverage: 28.5,
    economy: 7.75,
    bowlingStrikeRate: 22.0,
    bestBowling: '2/15',
    catches: 6,
    stumpings: 0,
    overallRating: 56,
    battingRating: 46,
    bowlingRating: 57,
    fieldingRating: 60,
    fitnessRating: 76,
    formRating: 54,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 50. Harvik Desai
  {
    name: 'Harvik Desai',
    fullName: 'Harvik Desai',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 4,
    runs: 55,
    battingAverage: 13.75,
    strikeRate: 122.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 1,
    overallRating: 51,
    battingRating: 50,
    bowlingRating: 5,
    fieldingRating: 56,
    fitnessRating: 72,
    formRating: 48,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 51. Urvil Patel
  {
    name: 'Urvil Patel',
    fullName: 'Urvil Patel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 2,
    runs: 18,
    battingAverage: 9.0,
    strikeRate: 140.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 1,
    stumpings: 0,
    overallRating: 49,
    battingRating: 52,
    bowlingRating: 5,
    fieldingRating: 54,
    fitnessRating: 70,
    formRating: 46,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 52. Aryan Juyal
  {
    name: 'Aryan Juyal',
    fullName: 'Aryan Juyal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 3,
    runs: 45,
    battingAverage: 15.0,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 1,
    overallRating: 50,
    battingRating: 48,
    bowlingRating: 5,
    fieldingRating: 56,
    fitnessRating: 73,
    formRating: 48,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 53. Luvnith Sisodia
  {
    name: 'Luvnith Sisodia',
    fullName: 'Luvnith Sisodia',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 2,
    runs: 15,
    battingAverage: 7.5,
    strikeRate: 115.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 1,
    stumpings: 1,
    overallRating: 47,
    battingRating: 45,
    bowlingRating: 5,
    fieldingRating: 54,
    fitnessRating: 70,
    formRating: 45,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 54. Manoj Bhandage
  {
    name: 'Manoj Bhandage',
    fullName: 'Manoj Bhandage',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM_FAST',
    matches: 4,
    runs: 35,
    battingAverage: 8.75,
    strikeRate: 145.0,
    hundreds: 0,
    fifties: 0,
    wickets: 2,
    bowlingAverage: 32.0,
    economy: 9.1,
    bowlingStrikeRate: 21.0,
    bestBowling: '1/15',
    catches: 2,
    stumpings: 0,
    overallRating: 52,
    battingRating: 46,
    bowlingRating: 48,
    fieldingRating: 52,
    fitnessRating: 76,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 55. Aman Khan
  {
    name: 'Aman Khan',
    fullName: 'Aman Hakim Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 14,
    runs: 110,
    battingAverage: 10.0,
    strikeRate: 122.2,
    hundreds: 0,
    fifties: 0,
    wickets: 1,
    bowlingAverage: 55.0,
    economy: 9.6,
    bowlingStrikeRate: 34.0,
    bestBowling: '1/15',
    catches: 6,
    stumpings: 0,
    overallRating: 54,
    battingRating: 48,
    bowlingRating: 44,
    fieldingRating: 54,
    fitnessRating: 76,
    formRating: 52,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 56. Ripal Patel
  {
    name: 'Ripal Patel',
    fullName: 'Ripal Patel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 10,
    runs: 85,
    battingAverage: 12.1,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 51,
    battingRating: 53,
    bowlingRating: 10,
    fieldingRating: 50,
    fitnessRating: 74,
    formRating: 48,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 57. Prerak Mankad
  {
    name: 'Prerak Mankad',
    fullName: 'Prerak Mankad',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 6,
    runs: 98,
    battingAverage: 24.5,
    strikeRate: 120.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 8.5,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 54,
    battingRating: 52,
    bowlingRating: 42,
    fieldingRating: 54,
    fitnessRating: 72,
    formRating: 52,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 58. Chirag Jani
  {
    name: 'Chirag Jani',
    fullName: 'Chirag Jani',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 36,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 10,
    runs: 120,
    battingAverage: 15.0,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 35.0,
    economy: 8.4,
    bowlingStrikeRate: 25.0,
    bestBowling: '2/20',
    catches: 4,
    stumpings: 0,
    overallRating: 55,
    battingRating: 50,
    bowlingRating: 50,
    fieldingRating: 52,
    fitnessRating: 65,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 59. Baba Indrajith
  {
    name: 'Baba Indrajith',
    fullName: 'Baba Indrajith',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 3,
    runs: 21,
    battingAverage: 7.0,
    strikeRate: 95.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 2,
    stumpings: 0,
    overallRating: 53,
    battingRating: 56,
    bowlingRating: 10,
    fieldingRating: 52,
    fitnessRating: 70,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 60. Baba Aparajith
  {
    name: 'Baba Aparajith',
    fullName: 'Baba Aparajith',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 105,
    battingAverage: 15.0,
    strikeRate: 115.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 32.0,
    economy: 7.9,
    bowlingStrikeRate: 24.3,
    bestBowling: '2/18',
    catches: 5,
    stumpings: 0,
    overallRating: 54,
    battingRating: 52,
    bowlingRating: 48,
    fieldingRating: 52,
    fitnessRating: 70,
    formRating: 51,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 61. Akshay Wadkar
  {
    name: 'Akshay Wadkar',
    fullName: 'Akshay Wadkar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 5,
    runs: 75,
    battingAverage: 18.75,
    strikeRate: 120.0,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 1,
    overallRating: 52,
    battingRating: 50,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 68,
    formRating: 48,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 62. Upendra Yadav
  {
    name: 'Upendra Yadav',
    fullName: 'Upendra Dewan Singh Yadav',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 4,
    runs: 32,
    battingAverage: 10.7,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 1,
    overallRating: 51,
    battingRating: 48,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 70,
    formRating: 48,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 63. Kartik Tyagi
  {
    name: 'Kartik Tyagi',
    fullName: 'Kartik Tyagi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST',
    matches: 19,
    runs: 14,
    battingAverage: 3.5,
    strikeRate: 65.0,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 34.2,
    economy: 9.25,
    bowlingStrikeRate: 22.2,
    bestBowling: '2/29',
    catches: 4,
    stumpings: 0,
    overallRating: 56,
    battingRating: 5,
    bowlingRating: 59,
    fieldingRating: 48,
    fitnessRating: 75,
    formRating: 54,
    marketDemand: 42,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 64. Ravi Kumar
  {
    name: 'Ravi Kumar',
    fullName: 'Ravi Kumar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 24,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 5,
    runs: 3,
    battingAverage: 1.5,
    strikeRate: 35.0,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 32.5,
    economy: 9.25,
    bowlingStrikeRate: 21.1,
    bestBowling: '2/22',
    catches: 1,
    stumpings: 0,
    overallRating: 49,
    battingRating: 5,
    bowlingRating: 51,
    fieldingRating: 42,
    fitnessRating: 68,
    formRating: 46,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 65. Yash Dhull
  {
    name: 'Yash Dhull',
    fullName: 'Yash Dhull',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 180,
    battingAverage: 22.5,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 57,
    battingRating: 60,
    bowlingRating: 10,
    fieldingRating: 55,
    fitnessRating: 72,
    formRating: 56,
    marketDemand: 42,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 66. Vivrant Sharma
  {
    name: 'Vivrant Sharma',
    fullName: 'Vivrant Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 22,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 12,
    runs: 210,
    battingAverage: 19.1,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 8.5,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 54,
    battingRating: 56,
    bowlingRating: 30,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 67. Sachin Baby
  {
    name: 'Sachin Baby',
    fullName: 'Sachin Baby',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 36,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 22,
    runs: 350,
    battingAverage: 18.4,
    strikeRate: 118.2,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 0,
    overallRating: 49,
    battingRating: 51,
    bowlingRating: 8,
    fieldingRating: 48,
    fitnessRating: 55,
    formRating: 42,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 68. Manan Vohra
  {
    name: 'Manan Vohra',
    fullName: 'Manan Vohra',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 28,
    runs: 420,
    battingAverage: 17.5,
    strikeRate: 132.8,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 0,
    overallRating: 53,
    battingRating: 55,
    bowlingRating: 5,
    fieldingRating: 50,
    fitnessRating: 65,
    formRating: 48,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 69. Anmolpreet Singh
  {
    name: 'Anmolpreet Singh',
    fullName: 'Anmolpreet Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 95,
    battingAverage: 13.6,
    strikeRate: 118.8,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 48,
    battingRating: 50,
    bowlingRating: 5,
    fieldingRating: 48,
    fitnessRating: 68,
    formRating: 45,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 70. Vishnu Vinod
  {
    name: 'Vishnu Vinod',
    fullName: 'Vishnu Vinod',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 15,
    runs: 220,
    battingAverage: 16.9,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 52,
    battingRating: 54,
    bowlingRating: 5,
    fieldingRating: 48,
    fitnessRating: 62,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 71. Akshath Reddy
  {
    name: 'Akshath Reddy',
    fullName: 'Akshath Reddy',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 5,
    runs: 55,
    battingAverage: 11.0,
    strikeRate: 105.8,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 2,
    stumpings: 0,
    overallRating: 45,
    battingRating: 45,
    bowlingRating: 5,
    fieldingRating: 42,
    fitnessRating: 62,
    formRating: 40,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 72. Gurkeerat Mann
  {
    name: 'Gurkeerat Mann',
    fullName: 'Gurkeerat Singh Mann',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 34,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 25,
    runs: 380,
    battingAverage: 17.3,
    strikeRate: 115.8,
    hundreds: 0,
    fifties: 1,
    wickets: 2,
    bowlingAverage: 42.0,
    economy: 8.5,
    bowlingStrikeRate: 29.6,
    bestBowling: '1/12',
    catches: 9,
    stumpings: 0,
    overallRating: 50,
    battingRating: 52,
    bowlingRating: 35,
    fieldingRating: 52,
    fitnessRating: 60,
    formRating: 45,
    marketDemand: 25,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 73. Mandeep Singh
  {
    name: 'Mandeep Singh',
    fullName: 'Mandeep Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 30,
    runs: 480,
    battingAverage: 19.2,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 12,
    stumpings: 0,
    overallRating: 54,
    battingRating: 56,
    bowlingRating: 5,
    fieldingRating: 55,
    fitnessRating: 62,
    formRating: 48,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 74. Karun Nair
  {
    name: 'Karun Nair',
    fullName: 'Karun Nair',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 22,
    runs: 340,
    battingAverage: 18.9,
    strikeRate: 125.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 7,
    stumpings: 0,
    overallRating: 55,
    battingRating: 58,
    bowlingRating: 8,
    fieldingRating: 55,
    fitnessRating: 62,
    formRating: 50,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 75. Pradosh Ranjan Paul
  {
    name: 'Pradosh Ranjan Paul',
    fullName: 'Pradosh Ranjan Paul',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 4,
    runs: 85,
    battingAverage: 21.25,
    strikeRate: 125.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 55,
    battingRating: 59,
    bowlingRating: 10,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  }
];
