export const part2 = [
  {
    name: 'Ruturaj Gaikwad',
    fullName: 'Ruturaj Dashrath Gaikwad',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 65,
    runs: 2100,
    battingAverage: 35.5,
    strikeRate: 131.8,
    hundreds: 2,
    fifties: 14,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 32,
    stumpings: 0,
    overallRating: 85,
    battingRating: 88,
    bowlingRating: 10,
    fieldingRating: 75,
    fitnessRating: 85,
    formRating: 88,
    marketDemand: 85,
    basePrice: 200,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Yashasvi Jaiswal',
    fullName: 'Yashasvi Bhupendra Jaiswal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 22,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 50,
    runs: 1800,
    battingAverage: 32.5,
    strikeRate: 158.2,
    hundreds: 1,
    fifties: 11,
    wickets: 2,
    bowlingAverage: 48,
    economy: 9.2,
    bowlingStrikeRate: 31.3,
    bestBowling: '1/12',
    catches: 25,
    stumpings: 0,
    overallRating: 86,
    battingRating: 89,
    bowlingRating: 12,
    fieldingRating: 78,
    fitnessRating: 90,
    formRating: 92,
    marketDemand: 90,
    basePrice: 200,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Sanju Samson',
    fullName: 'Sanju Viswanath Samson',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 165,
    runs: 4200,
    battingAverage: 29.8,
    strikeRate: 136.5,
    hundreds: 3,
    fifties: 18,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 72,
    stumpings: 18,
    overallRating: 84,
    battingRating: 86,
    bowlingRating: 5,
    fieldingRating: 80,
    fitnessRating: 82,
    formRating: 80,
    marketDemand: 82,
    basePrice: 200,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Ishan Kishan',
    fullName: 'Ishan Pranav Kumar Pandey Kishan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'MIDDLE_ORDER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 95,
    runs: 2300,
    battingAverage: 27.8,
    strikeRate: 136.2,
    hundreds: 1,
    fifties: 13,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 48,
    stumpings: 12,
    overallRating: 82,
    battingRating: 84,
    bowlingRating: 5,
    fieldingRating: 78,
    fitnessRating: 80,
    formRating: 78,
    marketDemand: 78,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Axar Patel',
    fullName: 'Akshar Rajeshbhai Patel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 135,
    runs: 1200,
    battingAverage: 20.5,
    strikeRate: 135.8,
    hundreds: 0,
    fifties: 3,
    wickets: 95,
    bowlingAverage: 28.5,
    economy: 7.35,
    bowlingStrikeRate: 23.2,
    bestBowling: '3/15',
    catches: 42,
    stumpings: 0,
    overallRating: 83,
    battingRating: 65,
    bowlingRating: 82,
    fieldingRating: 72,
    fitnessRating: 85,
    formRating: 82,
    marketDemand: 80,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Yuzvendra Chahal',
    fullName: 'Yuzvendra Singh Chahal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 145,
    runs: 55,
    battingAverage: 5.5,
    strikeRate: 72.5,
    hundreds: 0,
    fifties: 0,
    wickets: 187,
    bowlingAverage: 22.5,
    economy: 7.62,
    bowlingStrikeRate: 17.8,
    bestBowling: '5/40',
    catches: 28,
    stumpings: 0,
    overallRating: 85,
    battingRating: 8,
    bowlingRating: 92,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 82,
    marketDemand: 82,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Kuldeep Yadav',
    fullName: 'Kuldeep Yadav',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 29,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_CHINAMAN',
    matches: 80,
    runs: 42,
    battingAverage: 6.0,
    strikeRate: 78.2,
    hundreds: 0,
    fifties: 0,
    wickets: 72,
    bowlingAverage: 28.5,
    economy: 8.15,
    bowlingStrikeRate: 21.0,
    bestBowling: '4/14',
    catches: 18,
    stumpings: 0,
    overallRating: 83,
    battingRating: 10,
    bowlingRating: 88,
    fieldingRating: 58,
    fitnessRating: 82,
    formRating: 85,
    marketDemand: 80,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Mohammed Siraj',
    fullName: 'Mohammed Siraj',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 90,
    runs: 25,
    battingAverage: 3.5,
    strikeRate: 65.0,
    hundreds: 0,
    fifties: 0,
    wickets: 82,
    bowlingAverage: 28.8,
    economy: 8.68,
    bowlingStrikeRate: 19.9,
    bestBowling: '4/21',
    catches: 15,
    stumpings: 0,
    overallRating: 82,
    battingRating: 8,
    bowlingRating: 86,
    fieldingRating: 62,
    fitnessRating: 82,
    formRating: 78,
    marketDemand: 78,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Bhuvneshwar Kumar',
    fullName: 'Bhuvneshwar Kumar Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 34,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 165,
    runs: 75,
    battingAverage: 4.8,
    strikeRate: 80.5,
    hundreds: 0,
    fifties: 0,
    wickets: 162,
    bowlingAverage: 26.2,
    economy: 7.29,
    bowlingStrikeRate: 21.6,
    bestBowling: '5/19',
    catches: 25,
    stumpings: 0,
    overallRating: 82,
    battingRating: 12,
    bowlingRating: 88,
    fieldingRating: 65,
    fitnessRating: 72,
    formRating: 72,
    marketDemand: 75,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Deepak Chahar',
    fullName: 'Deepak Lokendrasingh Chahar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 85,
    runs: 180,
    battingAverage: 12.5,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 72,
    bowlingAverage: 27.8,
    economy: 7.85,
    bowlingStrikeRate: 21.2,
    bestBowling: '4/13',
    catches: 20,
    stumpings: 0,
    overallRating: 80,
    battingRating: 28,
    bowlingRating: 82,
    fieldingRating: 62,
    fitnessRating: 70,
    formRating: 72,
    marketDemand: 72,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Shardul Thakur',
    fullName: 'Shardul Narendra Thakur',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 95,
    runs: 380,
    battingAverage: 14.2,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 0,
    wickets: 78,
    bowlingAverage: 31.2,
    economy: 8.92,
    bowlingStrikeRate: 21.0,
    bestBowling: '3/22',
    catches: 22,
    stumpings: 0,
    overallRating: 79,
    battingRating: 38,
    bowlingRating: 78,
    fieldingRating: 65,
    fitnessRating: 75,
    formRating: 72,
    marketDemand: 70,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Devdutt Padikkal',
    fullName: 'Devdutt Padikkal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 24,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 65,
    runs: 1500,
    battingAverage: 25.8,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 10,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 22,
    stumpings: 0,
    overallRating: 78,
    battingRating: 80,
    bowlingRating: 5,
    fieldingRating: 70,
    fitnessRating: 82,
    formRating: 75,
    marketDemand: 72,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Tilak Varma',
    fullName: 'Tilak Varma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 21,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 55,
    runs: 1500,
    battingAverage: 33.5,
    strikeRate: 142.8,
    hundreds: 1,
    fifties: 8,
    wickets: 5,
    bowlingAverage: 42.0,
    economy: 8.8,
    bowlingStrikeRate: 28.6,
    bestBowling: '1/15',
    catches: 20,
    stumpings: 0,
    overallRating: 84,
    battingRating: 86,
    bowlingRating: 22,
    fieldingRating: 75,
    fitnessRating: 88,
    formRating: 90,
    marketDemand: 88,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Rinku Singh',
    fullName: 'Rinku Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 50,
    runs: 1100,
    battingAverage: 32.5,
    strikeRate: 148.2,
    hundreds: 0,
    fifties: 5,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 18,
    stumpings: 0,
    overallRating: 82,
    battingRating: 84,
    bowlingRating: 5,
    fieldingRating: 72,
    fitnessRating: 80,
    formRating: 85,
    marketDemand: 82,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Arshdeep Singh',
    fullName: 'Arshdeep Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 75,
    runs: 12,
    battingAverage: 3.0,
    strikeRate: 55.0,
    hundreds: 0,
    fifties: 0,
    wickets: 82,
    bowlingAverage: 26.5,
    economy: 8.78,
    bowlingStrikeRate: 18.1,
    bestBowling: '5/32',
    catches: 10,
    stumpings: 0,
    overallRating: 83,
    battingRating: 5,
    bowlingRating: 88,
    fieldingRating: 55,
    fitnessRating: 85,
    formRating: 85,
    marketDemand: 82,
    basePrice: 175,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Harshal Patel',
    fullName: 'Harshal Vikram Patel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 110,
    runs: 120,
    battingAverage: 8.5,
    strikeRate: 105.8,
    hundreds: 0,
    fifties: 0,
    wickets: 130,
    bowlingAverage: 24.8,
    economy: 8.42,
    bowlingStrikeRate: 17.7,
    bestBowling: '5/27',
    catches: 22,
    stumpings: 0,
    overallRating: 82,
    battingRating: 18,
    bowlingRating: 88,
    fieldingRating: 60,
    fitnessRating: 78,
    formRating: 78,
    marketDemand: 78,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Varun Chakravarthy',
    fullName: 'Varun Chakravarthy',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 55,
    runs: 8,
    battingAverage: 2.5,
    strikeRate: 42.0,
    hundreds: 0,
    fifties: 0,
    wickets: 58,
    bowlingAverage: 25.2,
    economy: 7.15,
    bowlingStrikeRate: 21.2,
    bestBowling: '5/17',
    catches: 12,
    stumpings: 0,
    overallRating: 81,
    battingRating: 5,
    bowlingRating: 86,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 80,
    marketDemand: 78,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  },
  {
    name: 'Rahul Chahar',
    fullName: 'Rahul Chahar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 55,
    runs: 15,
    battingAverage: 3.5,
    strikeRate: 68.5,
    hundreds: 0,
    fifties: 0,
    wickets: 52,
    bowlingAverage: 27.8,
    economy: 7.82,
    bowlingStrikeRate: 21.4,
    bestBowling: '4/17',
    catches: 10,
    stumpings: 0,
    overallRating: 78,
    battingRating: 8,
    bowlingRating: 82,
    fieldingRating: 55,
    fitnessRating: 78,
    formRating: 72,
    marketDemand: 70,
    basePrice: 150,
    isMarquee: false,
    isCapped: true,
  }
];
