export const part4d = [
  // 1. Mohammed Azharuddeen
  {
    name: 'Mohammed Azharuddeen',
    fullName: 'Mohammed Azharuddeen',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'OPENER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 12,
    runs: 220,
    battingAverage: 18.3,
    strikeRate: 135.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 2,
    overallRating: 54,
    battingRating: 55,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 70,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 2. Vishnu Vinod
  {
    name: 'Vishnu Vinod',
    fullName: 'Vishnu Vinod',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 15,
    runs: 280,
    battingAverage: 21.5,
    strikeRate: 140.2,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 3,
    overallRating: 58,
    battingRating: 60,
    bowlingRating: 5,
    fieldingRating: 62,
    fitnessRating: 72,
    formRating: 56,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 3. Urvil Patel
  {
    name: 'Urvil Patel',
    fullName: 'Urvil Patel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'OPENER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 8,
    runs: 160,
    battingAverage: 20.0,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 1,
    overallRating: 52,
    battingRating: 54,
    bowlingRating: 5,
    fieldingRating: 56,
    fitnessRating: 68,
    formRating: 50,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 4. Het Patel
  {
    name: 'Het Patel',
    fullName: 'Het Patel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 10,
    runs: 180,
    battingAverage: 18.0,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 2,
    overallRating: 50,
    battingRating: 51,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 66,
    formRating: 48,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 5. Kumar Kushagra
  {
    name: 'Kumar Kushagra',
    fullName: 'Kumar Kushagra',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 18,
    runs: 410,
    battingAverage: 25.6,
    strikeRate: 132.8,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 4,
    overallRating: 60,
    battingRating: 62,
    bowlingRating: 5,
    fieldingRating: 64,
    fitnessRating: 75,
    formRating: 58,
    marketDemand: 52,
    basePrice: 40,
    isMarquee: false,
    isCapped: false
  },
  // 6. Robin Minz
  {
    name: 'Robin Minz',
    fullName: 'Robin Minz',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 14,
    runs: 280,
    battingAverage: 21.5,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 2,
    overallRating: 55,
    battingRating: 57,
    bowlingRating: 5,
    fieldingRating: 60,
    fitnessRating: 72,
    formRating: 54,
    marketDemand: 40,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 7. Avanish Rao Aravelly
  {
    name: 'Avanish Rao Aravelly',
    fullName: 'Aravelly Avanish Rao',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 21,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 6,
    runs: 95,
    battingAverage: 15.8,
    strikeRate: 128.4,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 1,
    overallRating: 50,
    battingRating: 50,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 74,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 8. Dinesh Bana
  {
    name: 'Dinesh Bana',
    fullName: 'Dinesh Bana',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 8,
    runs: 110,
    battingAverage: 15.7,
    strikeRate: 135.2,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 2,
    overallRating: 51,
    battingRating: 52,
    bowlingRating: 5,
    fieldingRating: 58,
    fitnessRating: 72,
    formRating: 51,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 9. Luvnith Sisodia
  {
    name: 'Luvnith Sisodia',
    fullName: 'Luvnith Sisodia',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'OPENER',
    age: 26,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 5,
    runs: 85,
    battingAverage: 17.0,
    strikeRate: 125.4,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 1,
    overallRating: 48,
    battingRating: 48,
    bowlingRating: 5,
    fieldingRating: 54,
    fitnessRating: 68,
    formRating: 46,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 10. Aaradhya Yadav
  {
    name: 'Aaradhya Yadav',
    fullName: 'Aaradhya Yadav',
    country: 'India',
    nationality: 'INDIAN',
    role: 'WICKET_KEEPER',
    subRole: 'KEEPER_BATSMAN',
    age: 22,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 5,
    runs: 75,
    battingAverage: 15.0,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 1,
    overallRating: 47,
    battingRating: 47,
    bowlingRating: 5,
    fieldingRating: 55,
    fitnessRating: 70,
    formRating: 47,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 11. Rohan Kunnummal
  {
    name: 'Rohan Kunnummal',
    fullName: 'Rohan Kunnummal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 15,
    runs: 380,
    battingAverage: 25.3,
    strikeRate: 135.2,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 0,
    overallRating: 56,
    battingRating: 58,
    bowlingRating: 10,
    fieldingRating: 55,
    fitnessRating: 70,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 12. Harpreet Singh
  {
    name: 'Harpreet Singh',
    fullName: 'Harpreet Singh Bhatia',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 34,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 22,
    runs: 520,
    battingAverage: 28.9,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 3,
    wickets: 1,
    bowlingAverage: 45.0,
    economy: 9.0,
    bowlingStrikeRate: 30.0,
    bestBowling: '1/18',
    catches: 8,
    stumpings: 0,
    overallRating: 59,
    battingRating: 62,
    bowlingRating: 15,
    fieldingRating: 56,
    fitnessRating: 68,
    formRating: 57,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 13. Ricky Bhui
  {
    name: 'Ricky Bhui',
    fullName: 'Ricky Bhui',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 25,
    runs: 620,
    battingAverage: 28.2,
    strikeRate: 136.4,
    hundreds: 0,
    fifties: 4,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 10,
    stumpings: 0,
    overallRating: 62,
    battingRating: 65,
    bowlingRating: 8,
    fieldingRating: 58,
    fitnessRating: 72,
    formRating: 60,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 14. Ankit Kumar
  {
    name: 'Ankit Kumar',
    fullName: 'Ankit Kumar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 12,
    runs: 260,
    battingAverage: 21.7,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 53,
    battingRating: 55,
    bowlingRating: 10,
    fieldingRating: 50,
    fitnessRating: 68,
    formRating: 52,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 15. Bipin Singh
  {
    name: 'Bipin Singh',
    fullName: 'Bipin Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 26,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 8,
    runs: 140,
    battingAverage: 17.5,
    strikeRate: 118.2,
    hundreds: 0,
    fifties: 0,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 49,
    battingRating: 50,
    bowlingRating: 5,
    fieldingRating: 48,
    fitnessRating: 66,
    formRating: 47,
    marketDemand: 28,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 16. Baba Indrajith
  {
    name: 'Baba Indrajith',
    fullName: 'Baba Indrajith',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 24,
    runs: 580,
    battingAverage: 29.0,
    strikeRate: 126.8,
    hundreds: 0,
    fifties: 4,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 12,
    stumpings: 0,
    overallRating: 61,
    battingRating: 64,
    bowlingRating: 8,
    fieldingRating: 58,
    fitnessRating: 70,
    formRating: 59,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 17. Himanshu Rana
  {
    name: 'Himanshu Rana',
    fullName: 'Himanshu Rana',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 15,
    runs: 310,
    battingAverage: 20.7,
    strikeRate: 124.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 6,
    stumpings: 0,
    overallRating: 54,
    battingRating: 56,
    bowlingRating: 10,
    fieldingRating: 52,
    fitnessRating: 68,
    formRating: 52,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 18. Shaik Rasheed
  {
    name: 'Shaik Rasheed',
    fullName: 'Shaik Rasheed',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 12,
    runs: 280,
    battingAverage: 25.5,
    strikeRate: 130.5,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 58,
    battingRating: 60,
    bowlingRating: 8,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 56,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 19. Priyam Garg
  {
    name: 'Priyam Garg',
    fullName: 'Priyam Garg',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 22,
    runs: 460,
    battingAverage: 23.0,
    strikeRate: 128.2,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 9,
    stumpings: 0,
    overallRating: 59,
    battingRating: 61,
    bowlingRating: 10,
    fieldingRating: 54,
    fitnessRating: 72,
    formRating: 57,
    marketDemand: 42,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 20. Priyank Panchal
  {
    name: 'Priyank Panchal',
    fullName: 'Priyank Kirit Panchal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 36,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 30,
    runs: 720,
    battingAverage: 25.7,
    strikeRate: 121.2,
    hundreds: 0,
    fifties: 5,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 15,
    stumpings: 0,
    overallRating: 60,
    battingRating: 63,
    bowlingRating: 8,
    fieldingRating: 54,
    fitnessRating: 62,
    formRating: 55,
    marketDemand: 40,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 21. Abhimanyu Easwaran
  {
    name: 'Abhimanyu Easwaran',
    fullName: 'Abhimanyu Easwaran',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 28,
    runs: 780,
    battingAverage: 30.0,
    strikeRate: 124.5,
    hundreds: 0,
    fifties: 6,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 12,
    stumpings: 0,
    overallRating: 63,
    battingRating: 66,
    bowlingRating: 8,
    fieldingRating: 55,
    fitnessRating: 70,
    formRating: 61,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 22. Sudip Gharami
  {
    name: 'Sudip Gharami',
    fullName: 'Sudip Kumar Gharami',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 14,
    runs: 300,
    battingAverage: 21.4,
    strikeRate: 122.0,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 54,
    battingRating: 56,
    bowlingRating: 8,
    fieldingRating: 50,
    fitnessRating: 68,
    formRating: 52,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 23. Anustup Majumdar
  {
    name: 'Anustup Majumdar',
    fullName: 'Anustup Majumdar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 41,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 40,
    runs: 980,
    battingAverage: 28.8,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 7,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 18,
    stumpings: 0,
    overallRating: 64,
    battingRating: 67,
    bowlingRating: 8,
    fieldingRating: 52,
    fitnessRating: 58,
    formRating: 62,
    marketDemand: 42,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 24. Armaan Jaffer
  {
    name: 'Armaan Jaffer',
    fullName: 'Armaan Jaffer',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'TOP_ORDER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 12,
    runs: 250,
    battingAverage: 20.8,
    strikeRate: 124.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 53,
    battingRating: 55,
    bowlingRating: 10,
    fieldingRating: 48,
    fitnessRating: 68,
    formRating: 52,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 25. Divyansh Saxena
  {
    name: 'Divyansh Saxena',
    fullName: 'Divyansh Saxena',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'NONE',
    matches: 8,
    runs: 155,
    battingAverage: 19.3,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 3,
    stumpings: 0,
    overallRating: 50,
    battingRating: 52,
    bowlingRating: 5,
    fieldingRating: 48,
    fitnessRating: 72,
    formRating: 49,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 26. Harnoor Singh
  {
    name: 'Harnoor Singh',
    fullName: 'Harnoor Singh Pannu',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 10,
    runs: 210,
    battingAverage: 21.0,
    strikeRate: 120.4,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 54,
    battingRating: 56,
    bowlingRating: 8,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 52,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 27. Swastik Chikara
  {
    name: 'Swastik Chikara',
    fullName: 'Swastik Chikara',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'OPENER',
    age: 21,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 11,
    runs: 240,
    battingAverage: 21.8,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 1,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 4,
    stumpings: 0,
    overallRating: 55,
    battingRating: 57,
    bowlingRating: 8,
    fieldingRating: 54,
    fitnessRating: 74,
    formRating: 54,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 28. Ripal Patel
  {
    name: 'Ripal Patel',
    fullName: 'Ripal Patel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'FINISHER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 18,
    runs: 310,
    battingAverage: 20.6,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 1,
    wickets: 1,
    bowlingAverage: 35.0,
    economy: 8.8,
    bowlingStrikeRate: 24.0,
    bestBowling: '1/15',
    catches: 6,
    stumpings: 0,
    overallRating: 57,
    battingRating: 59,
    bowlingRating: 20,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 55,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 29. Subhranshu Senapati
  {
    name: 'Subhranshu Senapati',
    fullName: 'Subhranshu Senapati',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 14,
    runs: 280,
    battingAverage: 21.4,
    strikeRate: 125.0,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 5,
    stumpings: 0,
    overallRating: 54,
    battingRating: 56,
    bowlingRating: 10,
    fieldingRating: 52,
    fitnessRating: 70,
    formRating: 52,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 30. Aksh Deep Nath
  {
    name: 'Aksh Deep Nath',
    fullName: 'Aksh Deep Nath',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BATSMAN',
    subRole: 'MIDDLE_ORDER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 20,
    runs: 410,
    battingAverage: 22.7,
    strikeRate: 128.4,
    hundreds: 0,
    fifties: 2,
    wickets: 0,
    bowlingAverage: 0,
    economy: 0,
    bowlingStrikeRate: 0,
    bestBowling: '0/0',
    catches: 8,
    stumpings: 0,
    overallRating: 56,
    battingRating: 58,
    bowlingRating: 12,
    fieldingRating: 52,
    fitnessRating: 68,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 31. Prerak Mankad
  {
    name: 'Prerak Mankad',
    fullName: 'Prerak Mankad',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 18,
    runs: 280,
    battingAverage: 20.0,
    strikeRate: 128.5,
    hundreds: 0,
    fifties: 1,
    wickets: 12,
    bowlingAverage: 28.5,
    economy: 8.4,
    bowlingStrikeRate: 20.3,
    bestBowling: '3/22',
    catches: 8,
    stumpings: 0,
    overallRating: 58,
    battingRating: 55,
    bowlingRating: 52,
    fieldingRating: 56,
    fitnessRating: 72,
    formRating: 56,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 32. Chirag Jani
  {
    name: 'Chirag Jani',
    fullName: 'Chirag Jani',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 36,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 28,
    runs: 420,
    battingAverage: 19.1,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 2,
    wickets: 18,
    bowlingAverage: 30.5,
    economy: 7.9,
    bowlingStrikeRate: 23.1,
    bestBowling: '3/18',
    catches: 10,
    stumpings: 0,
    overallRating: 61,
    battingRating: 56,
    bowlingRating: 58,
    fieldingRating: 55,
    fitnessRating: 70,
    formRating: 59,
    marketDemand: 42,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 33. Baba Aparajith
  {
    name: 'Baba Aparajith',
    fullName: 'Baba Aparajith',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 25,
    runs: 480,
    battingAverage: 24.0,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 2,
    wickets: 15,
    bowlingAverage: 28.5,
    economy: 7.5,
    bowlingStrikeRate: 22.8,
    bestBowling: '3/15',
    catches: 12,
    stumpings: 0,
    overallRating: 60,
    battingRating: 58,
    bowlingRating: 54,
    fieldingRating: 58,
    fitnessRating: 70,
    formRating: 58,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 34. Shams Mulani
  {
    name: 'Shams Mulani',
    fullName: 'Shams Zakir Mulani',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 29,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 32,
    runs: 460,
    battingAverage: 20.9,
    strikeRate: 126.5,
    hundreds: 0,
    fifties: 2,
    wickets: 28,
    bowlingAverage: 25.8,
    economy: 7.6,
    bowlingStrikeRate: 20.3,
    bestBowling: '4/22',
    catches: 10,
    stumpings: 0,
    overallRating: 63,
    battingRating: 55,
    bowlingRating: 62,
    fieldingRating: 56,
    fitnessRating: 74,
    formRating: 62,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 35. Shubham Sharma
  {
    name: 'Shubham Sharma',
    fullName: 'Shubham Sharma',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 22,
    runs: 350,
    battingAverage: 19.4,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 1,
    wickets: 15,
    bowlingAverage: 29.5,
    economy: 7.8,
    bowlingStrikeRate: 22.6,
    bestBowling: '3/20',
    catches: 8,
    stumpings: 0,
    overallRating: 59,
    battingRating: 55,
    bowlingRating: 54,
    fieldingRating: 54,
    fitnessRating: 68,
    formRating: 56,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 36. Lalit Yadav
  {
    name: 'Lalit Yadav',
    fullName: 'Lalit Yadav',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 30,
    runs: 480,
    battingAverage: 20.0,
    strikeRate: 132.8,
    hundreds: 0,
    fifties: 2,
    wickets: 18,
    bowlingAverage: 31.5,
    economy: 8.2,
    bowlingStrikeRate: 23.0,
    bestBowling: '3/25',
    catches: 12,
    stumpings: 0,
    overallRating: 62,
    battingRating: 58,
    bowlingRating: 56,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 60,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 37. Aman Khan
  {
    name: 'Aman Khan',
    fullName: 'Aman Hakim Khan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 22,
    runs: 310,
    battingAverage: 18.2,
    strikeRate: 138.5,
    hundreds: 0,
    fifties: 1,
    wickets: 10,
    bowlingAverage: 32.5,
    economy: 8.8,
    bowlingStrikeRate: 22.1,
    bestBowling: '2/18',
    catches: 6,
    stumpings: 0,
    overallRating: 59,
    battingRating: 56,
    bowlingRating: 50,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 57,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 38. Manoj Bhandage
  {
    name: 'Manoj Bhandage',
    fullName: 'Manoj Bhandage',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 12,
    runs: 160,
    battingAverage: 16.0,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 28.5,
    economy: 8.6,
    bowlingStrikeRate: 19.8,
    bestBowling: '2/15',
    catches: 4,
    stumpings: 0,
    overallRating: 56,
    battingRating: 52,
    bowlingRating: 48,
    fieldingRating: 52,
    fitnessRating: 74,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 39. Swapnil Singh
  {
    name: 'Swapnil Singh',
    fullName: 'Swapnil Singh',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 35,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 25,
    runs: 320,
    battingAverage: 17.8,
    strikeRate: 124.5,
    hundreds: 0,
    fifties: 1,
    wickets: 18,
    bowlingAverage: 28.8,
    economy: 7.9,
    bowlingStrikeRate: 21.8,
    bestBowling: '3/20',
    catches: 8,
    stumpings: 0,
    overallRating: 60,
    battingRating: 54,
    bowlingRating: 56,
    fieldingRating: 55,
    fitnessRating: 70,
    formRating: 58,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 40. Atit Sheth
  {
    name: 'Atit Sheth',
    fullName: 'Atit Sheth',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 20,
    runs: 280,
    battingAverage: 18.7,
    strikeRate: 126.8,
    hundreds: 0,
    fifties: 1,
    wickets: 14,
    bowlingAverage: 30.5,
    economy: 8.2,
    bowlingStrikeRate: 22.3,
    bestBowling: '3/25',
    catches: 6,
    stumpings: 0,
    overallRating: 59,
    battingRating: 54,
    bowlingRating: 52,
    fieldingRating: 54,
    fitnessRating: 72,
    formRating: 57,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 41. Naman Dhir
  {
    name: 'Naman Dhir',
    fullName: 'Naman Dhir',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'BATTING_ALL_ROUNDER',
    age: 26,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 20,
    runs: 410,
    battingAverage: 24.1,
    strikeRate: 142.5,
    hundreds: 0,
    fifties: 2,
    wickets: 6,
    bowlingAverage: 32.5,
    economy: 8.8,
    bowlingStrikeRate: 22.1,
    bestBowling: '2/18',
    catches: 8,
    stumpings: 0,
    overallRating: 62,
    battingRating: 64,
    bowlingRating: 48,
    fieldingRating: 56,
    fitnessRating: 78,
    formRating: 61,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 42. Raj Bawa
  {
    name: 'Raj Bawa',
    fullName: 'Raj Angad Bawa',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 12,
    runs: 180,
    battingAverage: 18.0,
    strikeRate: 124.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 32.5,
    economy: 8.9,
    bowlingStrikeRate: 21.9,
    bestBowling: '3/24',
    catches: 4,
    stumpings: 0,
    overallRating: 57,
    battingRating: 54,
    bowlingRating: 50,
    fieldingRating: 52,
    fitnessRating: 75,
    formRating: 55,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 43. Nishant Sindhu
  {
    name: 'Nishant Sindhu',
    fullName: 'Nishant Sindhu',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 22,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 15,
    runs: 240,
    battingAverage: 20.0,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 1,
    wickets: 10,
    bowlingAverage: 28.5,
    economy: 7.9,
    bowlingStrikeRate: 21.6,
    bestBowling: '3/18',
    catches: 5,
    stumpings: 0,
    overallRating: 58,
    battingRating: 55,
    bowlingRating: 52,
    fieldingRating: 54,
    fitnessRating: 74,
    formRating: 56,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 44. Aneeshwar Gautam
  {
    name: 'Aneeshwar Gautam',
    fullName: 'Aneeshwar Gautam',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 6,
    runs: 75,
    battingAverage: 15.0,
    strikeRate: 115.4,
    hundreds: 0,
    fifties: 0,
    wickets: 4,
    bowlingAverage: 32.0,
    economy: 8.2,
    bowlingStrikeRate: 23.4,
    bestBowling: '2/15',
    catches: 2,
    stumpings: 0,
    overallRating: 50,
    battingRating: 48,
    bowlingRating: 46,
    fieldingRating: 50,
    fitnessRating: 70,
    formRating: 49,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 45. Kaushal Tambe
  {
    name: 'Kaushal Tambe',
    fullName: 'Kaushal Tambe',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 8,
    runs: 110,
    battingAverage: 15.7,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 5,
    bowlingAverage: 30.5,
    economy: 8.0,
    bowlingStrikeRate: 22.8,
    bestBowling: '2/18',
    catches: 3,
    stumpings: 0,
    overallRating: 51,
    battingRating: 49,
    bowlingRating: 47,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 50,
    marketDemand: 30,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 46. Shubhang Hegde
  {
    name: 'Shubhang Hegde',
    fullName: 'Shubhang Hegde',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 25,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 10,
    runs: 140,
    battingAverage: 17.5,
    strikeRate: 120.4,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 28.5,
    economy: 7.8,
    bowlingStrikeRate: 21.9,
    bestBowling: '2/20',
    catches: 4,
    stumpings: 0,
    overallRating: 53,
    battingRating: 51,
    bowlingRating: 49,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 52,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 47. Ninad Rathva
  {
    name: 'Ninad Rathva',
    fullName: 'Ninad Rathva',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 27,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 12,
    runs: 180,
    battingAverage: 18.0,
    strikeRate: 125.4,
    hundreds: 0,
    fifties: 1,
    wickets: 9,
    bowlingAverage: 28.8,
    economy: 7.9,
    bowlingStrikeRate: 21.8,
    bestBowling: '3/22',
    catches: 5,
    stumpings: 0,
    overallRating: 55,
    battingRating: 53,
    bowlingRating: 51,
    fieldingRating: 54,
    fitnessRating: 70,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 48. Sumit Kumar
  {
    name: 'Sumit Kumar',
    fullName: 'Sumit Kumar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 18,
    runs: 260,
    battingAverage: 18.6,
    strikeRate: 130.5,
    hundreds: 0,
    fifties: 1,
    wickets: 12,
    bowlingAverage: 30.5,
    economy: 8.5,
    bowlingStrikeRate: 21.5,
    bestBowling: '3/20',
    catches: 6,
    stumpings: 0,
    overallRating: 58,
    battingRating: 54,
    bowlingRating: 52,
    fieldingRating: 54,
    fitnessRating: 74,
    formRating: 56,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 49. Saurabh Kumar
  {
    name: 'Saurabh Kumar',
    fullName: 'Saurabh Kumar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SPIN_ALL_ROUNDER',
    age: 33,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 28,
    runs: 380,
    battingAverage: 19.0,
    strikeRate: 122.5,
    hundreds: 0,
    fifties: 2,
    wickets: 25,
    bowlingAverage: 26.5,
    economy: 7.5,
    bowlingStrikeRate: 21.2,
    bestBowling: '4/25',
    catches: 10,
    stumpings: 0,
    overallRating: 62,
    battingRating: 54,
    bowlingRating: 60,
    fieldingRating: 55,
    fitnessRating: 70,
    formRating: 60,
    marketDemand: 45,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 50. Harsh Patel
  {
    name: 'Harsh Patel',
    fullName: 'Harsh Patel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'ALL_ROUNDER',
    subRole: 'SEAM_ALL_ROUNDER',
    age: 29,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 10,
    runs: 120,
    battingAverage: 15.0,
    strikeRate: 118.5,
    hundreds: 0,
    fifties: 0,
    wickets: 8,
    bowlingAverage: 32.5,
    economy: 8.8,
    bowlingStrikeRate: 22.1,
    bestBowling: '2/18',
    catches: 3,
    stumpings: 0,
    overallRating: 52,
    battingRating: 48,
    bowlingRating: 48,
    fieldingRating: 50,
    fitnessRating: 72,
    formRating: 51,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 51. Tanush Kotian
  {
    name: 'Tanush Kotian',
    fullName: 'Tanush Kotian',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 22,
    runs: 180,
    battingAverage: 15.0,
    strikeRate: 110.2,
    hundreds: 0,
    fifties: 1,
    wickets: 25,
    bowlingAverage: 24.5,
    economy: 7.2,
    bowlingStrikeRate: 20.4,
    bestBowling: '4/18',
    catches: 8,
    stumpings: 0,
    overallRating: 64,
    battingRating: 25,
    bowlingRating: 66,
    fieldingRating: 58,
    fitnessRating: 75,
    formRating: 62,
    marketDemand: 52,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 52. Pravin Dubey
  {
    name: 'Pravin Dubey',
    fullName: 'Pravin Dubey',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 18,
    runs: 95,
    battingAverage: 9.5,
    strikeRate: 98.4,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 28.5,
    economy: 7.8,
    bowlingStrikeRate: 21.9,
    bestBowling: '3/22',
    catches: 6,
    stumpings: 0,
    overallRating: 58,
    battingRating: 15,
    bowlingRating: 60,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 56,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 53. Vicky Ostwal
  {
    name: 'Vicky Ostwal',
    fullName: 'Vicky Ostwal',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 23,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 12,
    runs: 45,
    battingAverage: 6.4,
    strikeRate: 80.5,
    hundreds: 0,
    fifties: 0,
    wickets: 11,
    bowlingAverage: 29.5,
    economy: 7.9,
    bowlingStrikeRate: 22.4,
    bestBowling: '3/20',
    catches: 4,
    stumpings: 0,
    overallRating: 56,
    battingRating: 10,
    bowlingRating: 58,
    fieldingRating: 52,
    fitnessRating: 74,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 54. Murugan Ashwin
  {
    name: 'Murugan Ashwin',
    fullName: 'Murugan Ashwin',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 35,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 28,
    runs: 85,
    battingAverage: 8.5,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 24,
    bowlingAverage: 29.8,
    economy: 8.2,
    bowlingStrikeRate: 21.8,
    bestBowling: '3/21',
    catches: 8,
    stumpings: 0,
    overallRating: 61,
    battingRating: 12,
    bowlingRating: 63,
    fieldingRating: 54,
    fitnessRating: 70,
    formRating: 59,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 55. KC Cariappa
  {
    name: 'KC Cariappa',
    fullName: 'Konganda Charamanna Cariappa',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 32,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_OFFBREAK',
    matches: 15,
    runs: 42,
    battingAverage: 4.2,
    strikeRate: 75.0,
    hundreds: 0,
    fifties: 0,
    wickets: 12,
    bowlingAverage: 32.5,
    economy: 8.4,
    bowlingStrikeRate: 23.2,
    bestBowling: '2/18',
    catches: 5,
    stumpings: 0,
    overallRating: 55,
    battingRating: 8,
    bowlingRating: 57,
    fieldingRating: 50,
    fitnessRating: 68,
    formRating: 53,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 56. Jagadeesha Suchith
  {
    name: 'Jagadeesha Suchith',
    fullName: 'Jagadeesha Suchith',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 32,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 24,
    runs: 110,
    battingAverage: 11.0,
    strikeRate: 115.4,
    hundreds: 0,
    fifties: 0,
    wickets: 20,
    bowlingAverage: 30.5,
    economy: 8.0,
    bowlingStrikeRate: 22.8,
    bestBowling: '3/22',
    catches: 10,
    stumpings: 0,
    overallRating: 59,
    battingRating: 20,
    bowlingRating: 61,
    fieldingRating: 55,
    fitnessRating: 70,
    formRating: 57,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 57. Vidwath Kaverappa
  {
    name: 'Vidwath Kaverappa',
    fullName: 'Vidwath Kaverappa',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 25,
    battingAverage: 5.0,
    strikeRate: 60.5,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 24.5,
    economy: 7.8,
    bowlingStrikeRate: 18.8,
    bestBowling: '3/20',
    catches: 5,
    stumpings: 0,
    overallRating: 63,
    battingRating: 10,
    bowlingRating: 65,
    fieldingRating: 54,
    fitnessRating: 78,
    formRating: 61,
    marketDemand: 48,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 58. V Koushik
  {
    name: 'V Koushik',
    fullName: 'Vasuki Koushik',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM',
    matches: 18,
    runs: 30,
    battingAverage: 5.0,
    strikeRate: 58.0,
    hundreds: 0,
    fifties: 0,
    wickets: 20,
    bowlingAverage: 26.2,
    economy: 7.4,
    bowlingStrikeRate: 21.2,
    bestBowling: '4/25',
    catches: 6,
    stumpings: 0,
    overallRating: 60,
    battingRating: 10,
    bowlingRating: 62,
    fieldingRating: 52,
    fitnessRating: 70,
    formRating: 58,
    marketDemand: 42,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 59. Arjun Tendulkar
  {
    name: 'Arjun Tendulkar',
    fullName: 'Arjun Sachin Tendulkar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 26,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 8,
    runs: 45,
    battingAverage: 9.0,
    strikeRate: 110.2,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 35.8,
    economy: 8.9,
    bowlingStrikeRate: 24.1,
    bestBowling: '1/15',
    catches: 3,
    stumpings: 0,
    overallRating: 53,
    battingRating: 18,
    bowlingRating: 55,
    fieldingRating: 50,
    fitnessRating: 75,
    formRating: 52,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 60. Mohit Avasthi
  {
    name: 'Mohit Avasthi',
    fullName: 'Mohit Avasthi',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 14,
    runs: 22,
    battingAverage: 4.4,
    strikeRate: 65.0,
    hundreds: 0,
    fifties: 0,
    wickets: 15,
    bowlingAverage: 28.5,
    economy: 8.2,
    bowlingStrikeRate: 20.8,
    bestBowling: '3/24',
    catches: 4,
    stumpings: 0,
    overallRating: 58,
    battingRating: 10,
    bowlingRating: 60,
    fieldingRating: 52,
    fitnessRating: 72,
    formRating: 56,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 61. Roosh Kalaria
  {
    name: 'Roosh Kalaria',
    fullName: 'Roosh Kalaria',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 33,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_MEDIUM',
    matches: 12,
    runs: 35,
    battingAverage: 5.8,
    strikeRate: 78.4,
    hundreds: 0,
    fifties: 0,
    wickets: 11,
    bowlingAverage: 30.5,
    economy: 8.1,
    bowlingStrikeRate: 22.5,
    bestBowling: '3/28',
    catches: 4,
    stumpings: 0,
    overallRating: 55,
    battingRating: 12,
    bowlingRating: 57,
    fieldingRating: 50,
    fitnessRating: 68,
    formRating: 53,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 62. Lukman Meriwala
  {
    name: 'Lukman Meriwala',
    fullName: 'Lukman Meriwala',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 34,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 22,
    runs: 15,
    battingAverage: 2.5,
    strikeRate: 50.0,
    hundreds: 0,
    fifties: 0,
    wickets: 24,
    bowlingAverage: 27.5,
    economy: 8.3,
    bowlingStrikeRate: 19.8,
    bestBowling: '4/20',
    catches: 6,
    stumpings: 0,
    overallRating: 59,
    battingRating: 5,
    bowlingRating: 61,
    fieldingRating: 52,
    fitnessRating: 70,
    formRating: 57,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 63. Arzan Nagwaswalla
  {
    name: 'Arzan Nagwaswalla',
    fullName: 'Arzan Rohinton Nagwaswalla',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 28,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_FAST_MEDIUM',
    matches: 20,
    runs: 28,
    battingAverage: 3.5,
    strikeRate: 62.5,
    hundreds: 0,
    fifties: 0,
    wickets: 22,
    bowlingAverage: 26.8,
    economy: 7.9,
    bowlingStrikeRate: 20.3,
    bestBowling: '3/22',
    catches: 7,
    stumpings: 0,
    overallRating: 61,
    battingRating: 10,
    bowlingRating: 63,
    fieldingRating: 54,
    fitnessRating: 74,
    formRating: 59,
    marketDemand: 45,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 64. Siddharth Desai
  {
    name: 'Siddharth Desai',
    fullName: 'Siddharth Desai',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 12,
    runs: 32,
    battingAverage: 4.0,
    strikeRate: 70.0,
    hundreds: 0,
    fifties: 0,
    wickets: 13,
    bowlingAverage: 28.5,
    economy: 7.8,
    bowlingStrikeRate: 21.9,
    bestBowling: '3/24',
    catches: 3,
    stumpings: 0,
    overallRating: 56,
    battingRating: 8,
    bowlingRating: 58,
    fieldingRating: 50,
    fitnessRating: 72,
    formRating: 54,
    marketDemand: 35,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 65. Chintan Gaja
  {
    name: 'Chintan Gaja',
    fullName: 'Chintan Gaja',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 31,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_MEDIUM_FAST',
    matches: 18,
    runs: 48,
    battingAverage: 6.0,
    strikeRate: 85.0,
    hundreds: 0,
    fifties: 0,
    wickets: 16,
    bowlingAverage: 30.5,
    economy: 8.2,
    bowlingStrikeRate: 22.3,
    bestBowling: '3/25',
    catches: 6,
    stumpings: 0,
    overallRating: 58,
    battingRating: 12,
    bowlingRating: 60,
    fieldingRating: 52,
    fitnessRating: 70,
    formRating: 56,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 66. Ishan Porel
  {
    name: 'Ishan Porel',
    fullName: 'Ishan Porel',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 27,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 15,
    runs: 10,
    battingAverage: 2.0,
    strikeRate: 45.2,
    hundreds: 0,
    fifties: 0,
    wickets: 14,
    bowlingAverage: 31.2,
    economy: 8.6,
    bowlingStrikeRate: 21.7,
    bestBowling: '3/24',
    catches: 4,
    stumpings: 0,
    overallRating: 58,
    battingRating: 5,
    bowlingRating: 60,
    fieldingRating: 50,
    fitnessRating: 72,
    formRating: 56,
    marketDemand: 38,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 67. Tanay Thyagarajan
  {
    name: 'Tanay Thyagarajan',
    fullName: 'Tanay Thyagarajan',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 30,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 18,
    runs: 62,
    battingAverage: 7.7,
    strikeRate: 88.5,
    hundreds: 0,
    fifties: 0,
    wickets: 18,
    bowlingAverage: 28.5,
    economy: 7.6,
    bowlingStrikeRate: 22.5,
    bestBowling: '3/18',
    catches: 6,
    stumpings: 0,
    overallRating: 59,
    battingRating: 15,
    bowlingRating: 61,
    fieldingRating: 54,
    fitnessRating: 70,
    formRating: 57,
    marketDemand: 40,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 68. Anshul Kamboj
  {
    name: 'Anshul Kamboj',
    fullName: 'Anshul Kamboj',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'PACE_BOWLER',
    age: 25,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_FAST_MEDIUM',
    matches: 12,
    runs: 20,
    battingAverage: 4.0,
    strikeRate: 75.0,
    hundreds: 0,
    fifties: 0,
    wickets: 14,
    bowlingAverage: 24.8,
    economy: 7.9,
    bowlingStrikeRate: 18.8,
    bestBowling: '3/22',
    catches: 4,
    stumpings: 0,
    overallRating: 61,
    battingRating: 10,
    bowlingRating: 63,
    fieldingRating: 54,
    fitnessRating: 76,
    formRating: 59,
    marketDemand: 45,
    basePrice: 30,
    isMarquee: false,
    isCapped: false
  },
  // 69. Manav Suthar
  {
    name: 'Manav Suthar',
    fullName: 'Manav Suthar',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 23,
    battingStyle: 'LEFT_HAND_BAT',
    bowlingStyle: 'LEFT_ARM_ORTHODOX',
    matches: 15,
    runs: 55,
    battingAverage: 6.8,
    strikeRate: 90.5,
    hundreds: 0,
    fifties: 0,
    wickets: 17,
    bowlingAverage: 26.5,
    economy: 7.5,
    bowlingStrikeRate: 21.2,
    bestBowling: '3/20',
    catches: 5,
    stumpings: 0,
    overallRating: 60,
    battingRating: 15,
    bowlingRating: 62,
    fieldingRating: 55,
    fitnessRating: 75,
    formRating: 58,
    marketDemand: 42,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  },
  // 70. Tejas Baroka
  {
    name: 'Tejas Baroka',
    fullName: 'Tejas Baroka',
    country: 'India',
    nationality: 'INDIAN',
    role: 'BOWLER',
    subRole: 'SPINNER',
    age: 30,
    battingStyle: 'RIGHT_HAND_BAT',
    bowlingStyle: 'RIGHT_ARM_LEGBREAK',
    matches: 8,
    runs: 12,
    battingAverage: 2.4,
    strikeRate: 60.0,
    hundreds: 0,
    fifties: 0,
    wickets: 6,
    bowlingAverage: 35.5,
    economy: 8.5,
    bowlingStrikeRate: 25.0,
    bestBowling: '2/18',
    catches: 3,
    stumpings: 0,
    overallRating: 52,
    battingRating: 8,
    bowlingRating: 54,
    fieldingRating: 50,
    fitnessRating: 68,
    formRating: 51,
    marketDemand: 32,
    basePrice: 20,
    isMarquee: false,
    isCapped: false
  }
];
