export const teamsSeed = [
  {
    name: 'Chennai Super Kings',
    shortName: 'CSK',
    fullName: 'Chennai Super Kings',
    primaryColor: '#FDB913',
    secondaryColor: '#F36F21',
    logoUrl: null,
    homeGround: 'M. A. Chidambaram Stadium',
    city: 'Chennai',
    owner: 'Chennai Super Kings Cricket Ltd.',
    coach: 'Stephen Fleming',
  },
  {
    name: 'Mumbai Indians',
    shortName: 'MI',
    fullName: 'Mumbai Indians',
    primaryColor: '#004BA0',
    secondaryColor: '#D1AB3E',
    logoUrl: null,
    homeGround: 'Wankhede Stadium',
    city: 'Mumbai',
    owner: 'Reliance Industries',
    coach: 'Mark Boucher',
  },
  {
    name: 'Royal Challengers Bengaluru',
    shortName: 'RCB',
    fullName: 'Royal Challengers Bengaluru',
    primaryColor: '#EC1C24',
    secondaryColor: '#2B2A29',
    logoUrl: null,
    homeGround: 'M. Chinnaswamy Stadium',
    city: 'Bengaluru',
    owner: 'United Spirits (Diageo)',
    coach: 'Andy Flower',
  },
  {
    name: 'Delhi Capitals',
    shortName: 'DC',
    fullName: 'Delhi Capitals',
    primaryColor: '#17479E',
    secondaryColor: '#EF1B23',
    logoUrl: null,
    homeGround: 'Arun Jaitley Stadium',
    city: 'Delhi',
    owner: 'GMR Group & JSW Group',
    coach: 'Ricky Ponting',
  },
  {
    name: 'Kolkata Knight Riders',
    shortName: 'KKR',
    fullName: 'Kolkata Knight Riders',
    primaryColor: '#3A225D',
    secondaryColor: '#FDB913',
    logoUrl: null,
    homeGround: 'Eden Gardens',
    city: 'Kolkata',
    owner: 'Red Chillies Entertainment',
    coach: 'Chandrakant Pandit',
  },
  {
    name: 'Punjab Kings',
    shortName: 'PBKS',
    fullName: 'Punjab Kings',
    primaryColor: '#ED1B24',
    secondaryColor: '#A7A9AC',
    logoUrl: null,
    homeGround: 'IS Bindra Stadium',
    city: 'Mohali',
    owner: 'Mohit Burman, Ness Wadia, Preity Zinta, Karan Paul',
    coach: 'Trevor Bayliss',
  },
  {
    name: 'Rajasthan Royals',
    shortName: 'RR',
    fullName: 'Rajasthan Royals',
    primaryColor: '#EA1A85',
    secondaryColor: '#254AA5',
    logoUrl: null,
    homeGround: 'Sawai Mansingh Stadium',
    city: 'Jaipur',
    owner: 'Manoj Badale',
    coach: 'Kumar Sangakkara',
  },
  {
    name: 'Gujarat Titans',
    shortName: 'GT',
    fullName: 'Gujarat Titans',
    primaryColor: '#1C1C1C',
    secondaryColor: '#B0D1E8',
    logoUrl: null,
    homeGround: 'Narendra Modi Stadium',
    city: 'Ahmedabad',
    owner: 'CVC Capital Partners',
    coach: 'Ashish Nehra',
  },
  {
    name: 'Lucknow Super Giants',
    shortName: 'LSG',
    fullName: 'Lucknow Super Giants',
    primaryColor: '#A72056',
    secondaryColor: '#FFCC00',
    logoUrl: null,
    homeGround: 'BRSABV Ekana Cricket Stadium',
    city: 'Lucknow',
    owner: 'RPSG Group',
    coach: 'Justin Langer',
  },
  {
    name: 'Sunrisers Hyderabad',
    shortName: 'SRH',
    fullName: 'Sunrisers Hyderabad',
    primaryColor: '#FF822A',
    secondaryColor: '#F44336',
    logoUrl: null,
    homeGround: 'Rajiv Gandhi International Cricket Stadium',
    city: 'Hyderabad',
    owner: 'Sun TV Network',
    coach: 'Daniel Vettori',
  },
];
